#!/usr/bin/env python3
"""
make_single_header.py: build single-header versions of WCtoolkit components.

    include/<name>.h + src/<name>.c  ->  single_header/<name>_single.h

Usage (from anywhere; paths resolve from the repo root):
    python3 tools/make_single_header.py --all
    python3 tools/make_single_header.py arena hashmap
    python3 tools/make_single_header.py --list

Each output holds the component's header and the headers of everything it
depends on, then every needed .c file inside one #ifdef WC_IMPLEMENTATION block.
In exactly one .c file:

    #define WC_IMPLEMENTATION
    #include "hashmap_single.h"

Several single headers can be included in the same file. Headers keep their own
include guards and each implementation has a WC_<NAME>_IMPL guard, so shared
dependencies (common, wc_allocator, ...) are emitted once.

Dependencies are read from the #include "..." lines of include/ and src/, so the
graph never goes stale. The only hand-written edges are EXTRA_DEPS below.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Support headers: inlined wherever needed, never built as a file of their own.
INTERNAL = {"common", "wc_errno", "map_setup"}

# Always part of every output: common.h's FATAL/WARN call wc_errno.c, and
# common.h includes wc_allocator.h.
CORE = ["wc_allocator", "common", "wc_errno"]

# Edges the #include graph can't see. wc_macros.h expands to HashMap_*,
# HashSet_*, Queue_* and Stack_* calls without including their headers.
EXTRA_DEPS = {
    "wc_macros": ["hashmap", "hashset", "queue", "stack"],
}

# Never part of the library.
EXCLUDED_SOURCES = {"main"}

LOCAL_INCLUDE = re.compile(r'^[ \t]*#[ \t]*include[ \t]+"([^"]+)\.h"[^\n]*', re.MULTILINE)
FILE_MACRO = re.compile(r'^[ \t]*#[ \t]*define[ \t]+(\w+)', re.MULTILINE)


def read(path: Path) -> str:
    # utf-8-sig drops a byte-order mark, which would otherwise land mid-file.
    return path.read_text(encoding="utf-8-sig") if path.exists() else ""


def discover(include_dir: Path, src_dir: Path) -> dict[str, list[str]]:
    """Component name -> direct dependencies, from the #include graph."""
    names = sorted(p.stem for p in include_dir.glob("*.h"))
    known = set(names)
    deps: dict[str, list[str]] = {}
    for name in names:
        text = read(include_dir / f"{name}.h") + read(src_dir / f"{name}.c")
        found = [m.group(1) for m in LOCAL_INCLUDE.finditer(text)]
        unknown = [d for d in found if d not in known]
        if unknown:
            sys.exit(f"[error] {name} includes unknown header(s): {', '.join(unknown)}")
        ordered = dict.fromkeys(d for d in found + EXTRA_DEPS.get(name, []) if d != name)
        deps[name] = list(ordered)
    return deps


def resolve(targets: list[str], deps: dict[str, list[str]]) -> list[str]:
    """Targets plus their transitive dependencies, dependencies first."""
    order: list[str] = []
    active: set[str] = set()

    def visit(name: str, path: list[str]) -> None:
        if name in order:
            return
        if name in active:
            sys.exit(f"[error] include cycle: {' -> '.join(path + [name])}")
        active.add(name)
        for d in deps[name]:
            visit(d, path + [name])
        active.discard(name)
        order.append(name)

    for t in CORE + targets:
        visit(t, [])
    return order


def section(label: str, path: Path, text: str) -> list[str]:
    # Blank the include lines instead of deleting them, so #line 1 stays exact.
    body = LOCAL_INCLUDE.sub("", text).rstrip()
    rel = path.relative_to(ROOT) if path.is_relative_to(ROOT) else path
    # #line keeps compiler errors and __FILE__ (used by FATAL/WARN) pointing at the real file.
    return [f"/* ===== {label} ===== */", f'#line 1 "{rel.as_posix()}"', body, ""]


def build(target: str, deps: dict[str, list[str]], include_dir: Path, src_dir: Path) -> str:
    chain = resolve([target], deps)
    guard = f"WC_{target.upper()}_SINGLE_H"

    out = [
        f"/* {target}_single.h: generated by tools/make_single_header.py. Do not edit.",
        f" * Contains: {', '.join(chain)}",
        " *",
        " * In exactly one .c file:",
        " *     #define WC_IMPLEMENTATION",
        f' *     #include "{target}_single.h"',
        " */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
    ]
    for name in chain:
        out += section(f"{name}.h", include_dir / f"{name}.h", read(include_dir / f"{name}.h"))

    out += ["#ifdef WC_IMPLEMENTATION", ""]
    for name in chain:
        c_path = src_dir / f"{name}.c"
        if not c_path.exists():
            continue  # header-only
        impl = f"WC_{name.upper()}_IMPL"
        out += [f"#ifndef {impl}", f"#define {impl}"]
        c_src = read(c_path)
        out += section(f"{name}.c", c_path, c_src)
        # A .c file's macros are private to it. Undefine them so two sources
        # that both define, say, GET_PSL don't collide in one translation unit.
        out += [f"#undef {m}" for m in dict.fromkeys(FILE_MACRO.findall(c_src))]
        out += [f"#endif /* {impl} */", ""]
    out += ["#endif /* WC_IMPLEMENTATION */", "", f"#endif /* {guard} */", ""]
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate single-header versions of WCtoolkit components.")
    ap.add_argument("components", nargs="*", metavar="COMPONENT")
    ap.add_argument("--all", action="store_true", help="build every public component")
    ap.add_argument("--list", action="store_true", help="list components and their dependencies")
    ap.add_argument("--include-dir", type=Path, default=ROOT / "include")
    ap.add_argument("--src-dir", type=Path, default=ROOT / "src")
    ap.add_argument("--out-dir", type=Path, default=ROOT / "single_header")
    args = ap.parse_args()

    for d in (args.include_dir, args.src_dir):
        if not d.is_dir():
            sys.exit(f"[error] directory not found: {d}")

    deps = discover(args.include_dir, args.src_dir)
    stray = sorted(p.stem for p in args.src_dir.glob("*.c")
                   if p.stem not in deps and p.stem not in EXCLUDED_SOURCES)
    if stray:
        sys.exit(f"[error] source(s) without a header: {', '.join(stray)}")
    public = [n for n in deps if n not in INTERNAL]

    if args.list:
        for name in public:
            print(f"  {name:<16} {', '.join(deps[name]) or '-'}")
        return

    targets = public if args.all else args.components
    if not targets:
        ap.print_help()
        sys.exit(1)
    bad = [t for t in targets if t not in public]
    if bad:
        sys.exit(f"[error] not a public component: {', '.join(bad)} (see --list)")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    for t in targets:
        path = args.out_dir / f"{t}_single.h"
        path.write_text(build(t, deps, args.include_dir, args.src_dir), encoding="utf-8")
        print(f"  {path.name:<26} {path.stat().st_size / 1024:6.1f} KB")


if __name__ == "__main__":
    main()
