/* hashmap_single.h: generated by tools/make_single_header.py. Do not edit.
 * Contains: wc_allocator, common, wc_errno, wc_hash, wc_specialize, hashmap
 *
 * In exactly one .c file:
 *     #define WC_IMPLEMENTATION
 *     #include "hashmap_single.h"
 */
#ifndef WC_HASHMAP_SINGLE_H
#define WC_HASHMAP_SINGLE_H

/* ===== wc_allocator.h ===== */
#line 1 "include/wc_allocator.h"
#ifndef WC_ALLOCATOR_H
#define WC_ALLOCATOR_H

#include <assert.h>
#include <stdalign.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>


#define WC_MAX_ALIGN alignof(max_align_t)

/* libc fallbacks */

static inline void* wc_libc_alloc(size_t n, size_t align)
{
    if (align <= WC_MAX_ALIGN) {
        return malloc(n);
    }

    size_t rounded = (n + align - 1) & ~(align - 1); // aligned_alloc: size % align == 0
    if (rounded < n) {
        return NULL; // overflow
    }
#ifdef _MSC_VER
    return _aligned_malloc(rounded, align);
#else
    return aligned_alloc(align, rounded);
#endif
}

static inline void wc_libc_free(void* p, size_t align)
{
#ifdef _MSC_VER
    if (align > WC_MAX_ALIGN) {
        _aligned_free(p); // MSVC can't free() these
        return;
    }
#endif
    (void)align;
    free(p); // POSIX/glibc: fine for both
}

static inline void* wc_libc_realloc(void* p, size_t old_n, size_t n, size_t align)
{
    if (align <= WC_MAX_ALIGN) {
        return realloc(p, n);
    }

    // libc realloc doesn't preserve alignment above max_align_t: alloc, copy, free
    void* q = wc_libc_alloc(n, align);
    if (!q) {
        return NULL; // p left untouched
    }
    memcpy(q, p, old_n < n ? old_n : n);
    wc_libc_free(p, align);
    return q;
}



/*
 * ALLOCATOR API
 *
 * No global allocator exists: every data structure receives its allocator at
 * construction, stores it, and uses it for every allocation.
 *
 * An allocator is a (vtable, ctx) pair. It is passed and stored as `const wc_allocator*`
 *   - the pointer is never NULL; libc is WC_LIBC, nothing else.
 *   - the pointed-to allocator must outlive every container that stores it.
 *     WC_LIBC and WC_BORROWED are static; Arena, ChainArena and wc_test_alloc
 *     embed their own allocator, so the arena's lifetime covers it
 *   - `const`: a call never changes the (vt, ctx) pair; ctx is what mutates
 *
 * Contract (the wc_* wrappers enforce it, backends may rely on it):
 *   - callbacks are never called with p == NULL or size == 0
 *   - `align` is a power of two >= 1 and is an ADDRESS alignment
 *   - `free` / `realloc` receive the exact size and align of the block's last
 *     alloc/realloc (wc_test_alloc verifies this; arenas ignore it)
 *   - `realloc` failure returns NULL and leaves p valid
 *   - missing `realloc` is emulated (alloc + copy + free); missing `free` is a no-op
 *   - wc_alloc(a, 0, ..) returns NULL without calling the backend
 *   - wc_realloc(a, NULL, 0, n, ..) == wc_alloc(a, n, ..)
 *   - wc_realloc(a, p, old, 0, ..) frees p and returns NULL
 *
*/
typedef struct {
    void* (*alloc)(void* ctx, size_t size, size_t align);
    void* (*realloc)(void* ctx, void* p, size_t old_size, size_t new_size, size_t align); // may be NULL
    void (*free)(void* ctx, void* p, size_t size, size_t align);                          // may be NULL
} wc_alloc_vtable;

typedef struct {
    const wc_alloc_vtable* vt;  // NULL => libc (only ever true for wc_libc)
    void*                  ctx; // Arena*, ChainArena*, test allocator, ...
} wc_allocator;

_Static_assert(sizeof(wc_allocator) == 16, "wc_allocator must stay 16 bytes");

// The libc allocator. Defined once in wc_allocator.c.
extern const wc_allocator wc_libc;
#define WC_LIBC (&wc_libc)

// Non-owning allocator: alloc -> NULL, free -> no-op. A container built on it
// wraps caller memory, cannot grow, and frees nothing on destroy.
extern const wc_allocator wc_borrowed;
#define WC_BORROWED (&wc_borrowed)

static inline __attribute__((nonnull(1))) int wc_is_libc(const wc_allocator* a)
{
    return a->vt == NULL;
}

// Same backend and same context: memory from one may be freed through the other.
static inline __attribute__((nonnull(1, 2))) int wc_same(const wc_allocator* a, const wc_allocator* b)
{
    return a == b || (a->vt == b->vt && a->ctx == b->ctx);
}

#define WC_ALLOC_ASSERT_ALIGN(align) \
    assert((align) != 0 && ((align) & ((align) - 1)) == 0 && "align must be a power of two >= 1")

static inline __attribute__((nonnull(1))) void* wc_alloc(const wc_allocator* a, size_t n, size_t align)
{
    WC_ALLOC_ASSERT_ALIGN(align);
    if (n == 0 || n > (size_t)PTRDIFF_MAX) { // > PTRDIFF_MAX: overflowed size (see wc_mul)
        return NULL;
    }
    return a->vt ? a->vt->alloc(a->ctx, n, align) : wc_libc_alloc(n, align);
}

static inline __attribute__((nonnull(1))) void wc_free(const wc_allocator* a, void* p, size_t n, size_t align)
{
    WC_ALLOC_ASSERT_ALIGN(align);
    if (!p) {
        return;
    }
    if (!a->vt) {
        wc_libc_free(p, align);
        return;
    }
    if (a->vt->free) {
        a->vt->free(a->ctx, p, n, align);
    }
}

static inline __attribute__((nonnull(1))) void* wc_realloc(const wc_allocator* a, void* p, size_t old_n, size_t n,
                                                           size_t align)
{
    WC_ALLOC_ASSERT_ALIGN(align);
    if (!p) {
        return wc_alloc(a, n, align);
    }
    if (n == 0) {
        wc_free(a, p, old_n, align);
        return NULL;
    }
    if (n > (size_t)PTRDIFF_MAX) {
        return NULL; // overflowed size: fail, p stays valid
    }
    if (!a->vt) {
        return wc_libc_realloc(p, old_n, n, align);
    }
    if (a->vt->realloc) {
        return a->vt->realloc(a->ctx, p, old_n, n, align);
    }

    // backend without realloc: emulate
    void* q = a->vt->alloc(a->ctx, n, align);
    if (!q) {
        return NULL; // p left untouched
    }
    memcpy(q, p, old_n < n ? old_n : n);
    wc_free(a, p, old_n, align);
    return q;
}

// count * size, saturating to SIZE_MAX on overflow. SIZE_MAX can never be
// satisfied, so an overflowing request fails in the backend instead of wrapping
// to a small size. (Returning 0 would be wrong: realloc to 0 means free.)
static inline size_t wc_mul(size_t count, size_t size)
{
    size_t r;
    return (int)__builtin_mul_overflow(count, size, &r) ? SIZE_MAX : r;
}

// Smallest safe alignment for elements of `elm_size` bytes: the
// largest power of two dividing elm_size, capped at WC_MAX_ALIGN. Valid because
// sizeof(T) is always a multiple of alignof(T).
static inline size_t wc_align_for_size(size_t elm_size)
{
    if (elm_size == 0) {
        return 1;
    }
    size_t lowbit = elm_size & (~elm_size + 1);
    return lowbit < WC_MAX_ALIGN ? lowbit : WC_MAX_ALIGN;
}


/* typed helpers (allocator first)
 * Free takes the POINTER, not a type: size and align come from *p, so a wrong
 * type can't be passed*/

#define WC_NEW(a, T)      ((T*)wc_alloc((a), sizeof(T), alignof(T)))
#define WC_NEW_N(a, T, n) ((T*)wc_alloc((a), wc_mul((n), sizeof(T)), alignof(T)))
#define WC_REALLOC_N(a, p, old_n, n)                                                               \
    ((__typeof__(p))wc_realloc((a), (p), wc_mul((old_n), sizeof(*(p))), wc_mul((n), sizeof(*(p))), \
                               alignof(__typeof__(*(p)))))
#define WC_FREE(a, p)      (wc_free((a), (p), sizeof(*(p)), alignof(__typeof__(*(p)))))
#define WC_FREE_N(a, p, n) (wc_free((a), (p), wc_mul((n), sizeof(*(p))), alignof(__typeof__(*(p)))))


#endif // WC_ALLOCATOR_H

/* ===== common.h ===== */
#line 1 "include/common.h"
#ifndef COMMON_H
#define COMMON_H



/*
 * WCtoolkit
 * Copyright (c) 2026 Wasi Ullah (PAKIWASI)
 * Licensed under the MIT License. See LICENSE file for details.
 */



// LOGGING/ERRORS

#include <stdalign.h>
#include <stdarg.h>
#include <stdio.h>
// #include <stdlib.h>

// ANSI Color Codes
#define WC_COLOR_RESET  "\033[0m"
#define WC_COLOR_RED    "\033[1;31m"
#define WC_COLOR_YELLOW "\033[1;33m"
#define WC_COLOR_GREEN  "\033[1;32m"
#define WC_COLOR_BLUE   "\033[1;34m"
#define WC_COLOR_CYAN   "\033[1;36m"



/*
 * DIAGNOSTICS
 *
 *   SURVIVES EVERY BUILD (Debug and Release)
 *     FATAL(fmt, ...)                 abort with a message
 *
 *     FATAL_IF(cond, fmt, ...)        abort if cond is TRUE. Absolute failures
 *                                     only: allocation failed, mutation of a
 *                                     zeroed (moved-from/destroyed) container.
 *
 *     WARN(fmt, ...)                  print a warning to stderr, continue
 *
 *     WARN_IF(cond, fmt, ...)         warn if cond is TRUE, continue
 *
 *     WARN_IF_RET(cond, ret, fmt, ...) warn and `return ret` if cond is TRUE
 *                                     (GNU statement expression can return)
 *
 *     LOG(fmt, ...)                   print to stderr
 *
 *     LOG_IF(cond, fmt, ...)          log if cond is TRUE
 *
 *   STRIPPED UNDER NDEBUG (Release)
 *
 *     WC_ASSERT(cond, fmt, ...)       abort if cond is FALSE. cond is the
 *                                     INVARIANT (`i < size`), not the failure.
 *                                     For programmer errors: bounds, API misuse.
 *                                     Release: cond is NOT evaluated (no side
 *                                     effects run) but still type-checked.
 *
 * The rule: if continuing past the failure would corrupt memory even in a
 * correct program (an allocator returned NULL), use FATAL_IF. If the failure
 * means the CALLER has a bug, use WC_ASSERT
 *
 * Branch prediction: failure paths are WC_UNLIKELY, and the reporters are
 * `cold, noinline` functions defined once in wc_errno.c. The compiler moves
 * every failure branch (argument setup + call) out of the hot path into
 * .text.unlikely, so a check costs one compare and one not-taken branch.
*/

#define WC_LIKELY(x)   __builtin_expect(!!(x), 1)
#define WC_UNLIKELY(x) __builtin_expect(!!(x), 0)

__attribute__((cold, noinline, noreturn, format(printf, 4, 5))) void
wc_fatal_report(const char* file, int line, const char* func, const char* fmt, ...);

/* Fatal handler. Every FATAL / FATAL_IF formats its message and calls the
 * installed handler. The handler must not return: abort, exit, or longjmp out
 * (tests can verify that something FATALs). If it does return, the program
 * exits. NULL restores the default (print to stderr, exit(EXIT_FAILURE)).
 * Returns the previous handler. Set it once at startup: it is not thread-local. */
typedef void (*wc_fatal_fn)(const char* file, int line, const char* func, const char* msg);
wc_fatal_fn wc_set_fatal_handler(wc_fatal_fn fn);

__attribute__((cold, noinline, format(printf, 4, 5))) void wc_warn_report(const char* file, int line, const char* func,
                                                                          const char* fmt, ...);


/* SURVIVES EVERY BUILD */

#define FATAL(fmt, ...) wc_fatal_report(__FILE__, __LINE__, __func__, fmt, ##__VA_ARGS__)

#define FATAL_IF(cond, fmt, ...) ((void)(WC_UNLIKELY(cond) && (FATAL("(%s): " fmt, #cond, ##__VA_ARGS__), 0)))

#define WARN(fmt, ...) wc_warn_report(__FILE__, __LINE__, __func__, fmt, ##__VA_ARGS__)

#define WARN_IF(cond, fmt, ...) ((void)(WC_UNLIKELY(cond) && (WARN("(%s): " fmt, #cond, ##__VA_ARGS__), 0)))

#define WARN_IF_RET(cond, ret, fmt, ...)              \
    ({                                                \
        if (WC_UNLIKELY(cond)) {                      \
            WARN("(%s): " fmt, #cond, ##__VA_ARGS__); \
            return ret;                               \
        }                                             \
        (void)0;                                      \
    })

// stderr, like WARN/FATAL: diagnostics never mix into program output.
#define LOG(fmt, ...) \
    ((void)fprintf(stderr, WC_COLOR_CYAN "[LOG] %s(): " fmt "\n" WC_COLOR_RESET, __func__, ##__VA_ARGS__))

#define LOG_IF(cond, fmt, ...) ((void)((cond) && (LOG(fmt, ##__VA_ARGS__), 0)))


/* STRIPPED UNDER NDEBUG */

#ifdef NDEBUG
// Not evaluated (sizeof of an int expression), still compiled: a stale field
// name or type error inside an assert breaks the Release build too, and
// variables used only in asserts don't trigger unused warnings.
#define WC_ASSERT(cond, fmt, ...) ((void)sizeof(!(cond)))
#else
#define WC_ASSERT(cond, fmt, ...) \
    ((void)(WC_LIKELY(cond) || (FATAL("assertion (%s) failed: " fmt, #cond, ##__VA_ARGS__), 0)))
#endif


// Token pasting that expands its arguments first. `a##b` pastes BEFORE expansion,
// so WC_CAT_(x, __LINE__) gives `x__LINE__`; the extra level expands __LINE__ to
// 42 first and then pastes, giving `x42`. Used for __COUNTER__/__LINE__ names.
#define WC_CAT_(a, b) a##b
#define WC_CAT(a, b)  WC_CAT_(a, b)


// TYPES

#include <stdbool.h>
#include <stdint.h>

typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;

typedef int8_t  i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;

// we are using unsigned indices/sizes
#define WC_NOT_FOUND ((u64) - 1)


// GENERIC FUNCTIONS


/* ELEMENT OPS
 *
 * Memory rule B5: every element is TRIVIALLY RELOCATABLE. A container may move
 * an element to another address with a raw memcpy (growth, insert/remove shifts,
 * hash table shuffles, queue compaction, taking an element out) and never asks
 * the element first. A type that holds a pointer to itself, or that something
 * outside points into, cannot be stored by value: store it by pointer.
 *
 */

// Deep-copy `src` INTO `dest`, allocating any owned resources from `dst`.
// `dest` is uninitialised raw slot memory: never read or free it (B3).
// Called ONLY when both sides keep the value (B8).
typedef void (*wc_copy_fn)(const wc_allocator* dst, void* dest, const void* src);
// Release owned resources of the element (not the slot). Elements that own
// memory store their own allocator, so no allocator argument is needed (B2).
typedef void (*wc_delete_fn)(void* elm);
typedef void (*wc_print_fn)(const void* elm);
typedef int (*wc_compare_fn)(const void* a, const void* b, u64 size);


// vtable: one instance shared across all objects of the same type.
// Pass NULL for any callback not needed (no copy_fn: copies are memcpy;
// no del_fn: nothing is freed per element). For plain data pass NULL ops.
typedef struct {
    wc_copy_fn   copy_fn; // Deep copy function for owned resources (or NULL)
    wc_delete_fn del_fn;  // Cleanup function for owned resources (or NULL)
} wc_container_ops;


// Heap-box a value-returning constructor through allocator A:
//   GenVec* v = WC_BOX_IN(A, GenVec, GenVec_create, 8, sizeof(int), NULL);
// Invariant: the shell comes from the same allocator the child stores, so a
// by-pointer delete can free the shell with the child's own allocator.
#define WC_BOX_IN(A, T, init_fn, ...)                              \
    ({                                                             \
        T* _wbx_p = wc_alloc(A, sizeof(T), alignof(T));            \
        FATAL_IF(!_wbx_p, "WC_BOX_IN(" #T "): allocation failed"); \
        *_wbx_p = init_fn(A, __VA_ARGS__);                         \
        _wbx_p;                                                    \
    })


// COMMON SIZES

#define KB (1 << 10)
#define MB (1 << 20)

#define nKB(n) ((u64)((n) * KB))
#define nMB(n) ((u64)((n) * MB))


// RAW BYTES TO HEX

static inline void print_hex(const u8* ptr, u64 size, u32 bytes_per_line)
{
    if (ptr == NULL || size == 0 || bytes_per_line == 0) {
        return;
    }

    // hex rep 0-15
    const char* hex = "0123456789ABCDEF";

    for (u64 i = 0; i < size; i++) {
        u8 val1 = ptr[i] >> 4;   // get upper 4 bits as num b/w 0-15
        u8 val2 = ptr[i] & 0x0F; // get lower 4 bits as num b/w 0-15

        printf("%c%c", hex[val1], hex[val2]);

        // Add space or newline appropriately
        if ((i + 1) % bytes_per_line == 0) {
            printf("\n");
        } else if (i < size - 1) {
            printf(" ");
        }
    }

    // Add final newline if we didn't just print one
    if (size % bytes_per_line != 0) {
        printf("\n");
    }
}


// TEST HELPERS

// Generic print functions for primitive types
static inline void wc_print_int(const void* elm)
{
    printf("%d ", *(int*)elm);
}
static inline void wc_print_u32(const void* elm)
{
    printf("%u ", *(u32*)elm);
}
static inline void wc_print_u64(const void* elm)
{
    printf("%llu ", (unsigned long long)*(u64*)elm);
}
static inline void wc_print_float(const void* elm)
{
    printf("%.2f ", (double)*(float*)elm);
}
static inline void wc_print_char(const void* elm)
{
    printf("%c ", *(char*)elm);
}
static inline void wc_print_cstr(const void* elm)
{
    printf("%s ", (const char*)elm);
}


#endif // COMMON_H

/* ===== wc_errno.h ===== */
#line 1 "include/wc_errno.h"
#ifndef WC_ERRNO_H
#define WC_ERRNO_H

#include <stdio.h>


/* wc_errno.h — Error reporting for WCtoolkit
 *
 * Three tiers:
 *
 *   FATAL_IF     Resource failures and dead state, in EVERY build: an
 *                allocator returned NULL, or a zeroed (moved-from/destroyed)
 *                container was mutated. Continuing would corrupt memory.
 *
 *   WC_ASSERT    Programmer errors: null pointer, out of bounds, size 0.
 *                Takes the INVARIANT (`i < size`). Crashes with a message in
 *                debug builds; compiled out under NDEBUG (condition not
 *                evaluated). Never use it for allocation failure.
 *
 *   (WARN_IF / LOG_IF report and continue, in every build. Full list and
 *    the release/debug split: the DIAGNOSTICS block in common.h.)
 *
 *   wc_errno     Expected conditions: pop on empty, Arena full.
 *                Function returns NULL / 0 / void. wc_errno says why.
 *                Ignore it if you don't care. Check it if you do.
 *
 *
 * USAGE
 * -----
 *   // Check a single call:
 *   wc_errno = WC_OK;
 *   void* p = Arena_alloc(Arena, size);
 *   if (!p && wc_errno == WC_ERR_FULL) { ... }
 *
 *   // Check a batch — wc_errno stays set if any call failed:
 *   wc_errno = WC_OK;
 *   float* a = Arena_alloc(Arena, 256);
 *   float* b = Arena_alloc(Arena, 256);
 *   if (wc_errno) { wc_perror("alloc"); }
 *
 *
 * RULES
 * -----
 *   1. Successful calls do NOT clear wc_errno — clear it yourself.
 *   2. Check the return value first. wc_errno tells you WHY, not WHETHER.
 *   3. wc_errno is thread-local. Each thread has its own copy.
 *
 *
 * WHAT SETS wc_errno
 * ------------------
 *   Arena_alloc, Arena_alloc_aligned      WC_ERR_FULL    Arena exhausted
 *   GenVec_pop, GenVec_front, GenVec_back WC_ERR_EMPTY   vec is empty
 *   Queue_pop, Queue_peek, Queue_peek_ptr WC_ERR_EMPTY   Queue is empty
 *   Stack_pop, Stack_peek                 WC_ERR_EMPTY   Stack is empty
 */


typedef enum {
    WC_OK = 0,
    WC_ERR_FULL,       // Arena exhausted / container at capacity
    WC_ERR_EMPTY,      // pop or peek on empty container
    WC_ERR_INVALID_OP, // call to a function with preconditions not met
} wc_err;

static inline const char* wc_strerror(wc_err e)
{
    switch (e) {
    case WC_OK:
        return "ok";
    case WC_ERR_FULL:
        return "full";
    case WC_ERR_EMPTY:
        return "empty";
    case WC_ERR_INVALID_OP:
        return "invalid op";
    default:
        return "unknown";
    }
}

/* Defined in wc_errno.c:
 *   _Thread_local wc_err wc_errno = WC_OK;
 */
extern _Thread_local wc_err wc_errno;

/* Print last error — same pattern as perror(3).
 *   wc_perror("Arena_alloc");  ->  "Arena_alloc: full"
 */
static inline void wc_perror(const char* prefix)
{
    if (prefix && prefix[0]) {
        fprintf(stderr, "%s: %s\n", prefix, wc_strerror(wc_errno));
    } else {
        fprintf(stderr, "%s\n", wc_strerror(wc_errno));
    }
}


/* Internal macros (library use only)
 * ------------------------------------
 * WC_SET_RET — for expected-condition sites (use WARN_IF_RET to also print).
 * Sets wc_errno silently and returns. No print.
 *
 *   WC_SET_RET(WC_ERR_EMPTY, vec->size == 0, );     void return
 *   WC_SET_RET(WC_ERR_FULL,  cond,           NULL); pointer return
 */
#define WC_SET_RET(err_code, cond, ret) \
    ({                                  \
        if (WC_UNLIKELY(cond)) {        \
            wc_errno = (err_code);      \
            return ret;                 \
        }                               \
    })

/* WC_PROPAGATE_RET — exit immediately if a callee already set wc_errno.
 *
 *   some_internal_fn(vec);
 *   WC_PROPAGATE_RET( );   // exits if some_internal_fn set wc_errno
 */
#define WC_PROPAGATE_RET(ret)                 \
    ({                                        \
        if (WC_UNLIKELY(wc_errno != WC_OK)) { \
            return ret;                       \
        }                                     \
    })

#endif // WC_ERRNO_H

/* ===== wc_hash.h ===== */
#line 1 "include/wc_hash.h"
#ifndef WC_HASH_H
#define WC_HASH_H


#include <string.h>


// Hash `size` bytes at `key`
typedef u64 (*wc_hash_fn)(const void* key, u64 size);

/*
====================HASH FUNCTIONS====================
*/

/* wc_hash: rapidhash V3, "nano" variant (the one tuned for short inputs).
 *
 * Based on wyhash by Wang Yi. Source: https://github.com/Nicoshev/rapidhash
 *
 * Copyright (C) 2025 Nicolas De Carli
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Changes from upstream: C only, default seed and secrets folded in, reads in
 * native byte order (hash values are for in-memory tables, never stored or
 * sent, so big-endian hosts need no byte swap). Output matches upstream
 * rapidhashNano() on little-endian hosts; tests/test_hashmap.c checks it.
 */

// 64 x 64 -> 128 bit multiply. *a gets the low half, *b the high half.
static inline __attribute__((always_inline)) void wc_rapid_mum(u64* a, u64* b)
{
    __uint128_t r = (__uint128_t)*a * *b;
    *a            = (u64)r;
    *b            = (u64)(r >> 64);
}

// Multiply, then fold the 128-bit product to 64 bits.
static inline __attribute__((always_inline)) u64 wc_rapid_mix(u64 a, u64 b)
{
    wc_rapid_mum(&a, &b);
    return a ^ b;
}

static inline __attribute__((always_inline)) u64 wc_rapid_read64(const u8* p)
{
    u64 v;
    memcpy(&v, p, 8);
    return v;
}

static inline __attribute__((always_inline)) u64 wc_rapid_read32(const u8* p)
{
    u32 v;
    memcpy(&v, p, 4);
    return v;
}

#define WC_RAPID_S0   0x2d358dccaa6c78a5ULL
#define WC_RAPID_S1   0x8bb84b93962eacc9ULL
#define WC_RAPID_S2   0x4b33a62ed433d4a3ULL
#define WC_RAPID_S7   0xaaaaaaaaaaaaaaaaULL
#define WC_RAPID_SEED 0ULL

// Hash `len` bytes. With a constant len (keys of a known size) every length
// branch folds away: a 4 or 8 byte key costs two 128-bit multiplies.
static inline __attribute__((always_inline)) u64 wc_hash(const void* key, u64 len)
{
    const u8* p    = key;
    u64       seed = WC_RAPID_SEED ^ wc_rapid_mix(WC_RAPID_SEED ^ WC_RAPID_S2, WC_RAPID_S1);
    u64       a    = 0;
    u64       b    = 0;
    u64       i    = len;

    if (WC_LIKELY(len <= 16)) {
        if (len >= 4) {
            seed ^= len;
            if (len >= 8) {
                a = wc_rapid_read64(p);
                b = wc_rapid_read64(p + len - 8);
            } else {
                a = wc_rapid_read32(p);
                b = wc_rapid_read32(p + len - 4);
            }
        } else if (len > 0) {
            a = ((u64)p[0] << 45) | p[len - 1];
            b = p[len >> 1];
        }
    } else {
        if (i > 48) {
            u64 see1 = seed;
            u64 see2 = seed;
            do {
                seed = wc_rapid_mix(wc_rapid_read64(p) ^ WC_RAPID_S0, wc_rapid_read64(p + 8) ^ seed);
                see1 = wc_rapid_mix(wc_rapid_read64(p + 16) ^ WC_RAPID_S1, wc_rapid_read64(p + 24) ^ see1);
                see2 = wc_rapid_mix(wc_rapid_read64(p + 32) ^ WC_RAPID_S2, wc_rapid_read64(p + 40) ^ see2);
                p += 48;
                i -= 48;
            } while (i > 48);
            seed ^= see1;
            seed ^= see2;
        }
        if (i > 16) {
            seed = wc_rapid_mix(wc_rapid_read64(p) ^ WC_RAPID_S2, wc_rapid_read64(p + 8) ^ seed);
            if (i > 32) {
                seed = wc_rapid_mix(wc_rapid_read64(p + 16) ^ WC_RAPID_S2, wc_rapid_read64(p + 24) ^ seed);
            }
        }
        a = wc_rapid_read64(p + i - 16) ^ i;
        b = wc_rapid_read64(p + i - 8);
    }

    a ^= WC_RAPID_S1;
    b ^= seed;
    wc_rapid_mum(&a, &b);
    return wc_rapid_mix(a ^ WC_RAPID_S7, b ^ WC_RAPID_S1 ^ i);
}


#endif // WC_HASH_H

/* ===== wc_specialize.h ===== */
#line 1 "include/wc_specialize.h"
#ifndef WC_SPECIALIZE_H
#define WC_SPECIALIZE_H



#include <string.h>

/*
 * SIZE SPECIALISATION
 * ===================
 *
 * Containers store elements as raw bytes and learn the element size at runtime
 * (a GenVec has a data_size field, a HashMap has key_size / val_size fields).
 * The copy routine is therefore memcpy(d, s, size) with `size` a variable, and
 * that is a call into libc: the compiler cannot see how many bytes move, so it
 * emits a call instead of a few plain loads and stores.
 *
 * This header turns those runtime sizes into compile-time constants, in two
 * levels:
 *
 *   1. wc_copy_n / wc_equal_n
 *      Drop-in for memcpy / (memcmp == 0). A switch sends the common sizes to
 *      a fixed-size copy. Use them anywhere: no setup, no change to the caller.
 *      On their own they only replace the libc call with a switch. They become
 *      free when the size is a constant at the call site, because then the
 *      switch folds away entirely (see level 2).
 *
 *   2. WC_SPECIALIZE(size, N, call)          - one runtime size
 *      WC_SPECIALIZE_2(s1, N1, s2, N2, call) - two runtime sizes
 *      A poor man's template. Each macro runs `call` once, with N (or N1/N2) a
 *      compile-time constant for each listed size, and with N bound to the
 *      runtime size otherwise. Use it to wrap a hot loop that lives in an
 *      always_inline function taking the size as a parameter. Each case gets
 *      its own inlined copy of the loop, so every wc_copy_n inside folds to a
 *      single fixed-size move, and the size switch runs once per call instead
 *      of once per element.
 *
 *      static inline __attribute__((always_inline))
 *      void fill_k(u8* dst, const u8* src, u64 n, u32 size)
 *      {
 *          for (u64 i = 0; i < n; i++) {
 *              wc_copy_n(dst + (i * size), src, size);
 *          }
 *      }
 *
 *      void fill(GenVec* v, const void* val, u64 n)
 *      {
 *          WC_SPECIALIZE(v->data_size, SZ, fill_k(v->data, val, n, SZ));
 *      }
 *
 * SIZE LISTS
 * ----------
 * Which sizes get their own copy is set by two lists (X-macros, see below):
 *
 *   WC_SPECIALIZE_SIZES      WC_SPECIALIZE, and the FIRST size of WC_SPECIALIZE_2
 *                            default: 4 8 16 48
 *   WC_SPECIALIZE_SIZES_2ND  the SECOND size of WC_SPECIALIZE_2
 *                            default: 0 4 8 16 48
 *
 *   0  - no value at all (a HashMap set): only in the second list
 *   4  - int, u32, float, small enum
 *   8  - u64, pointer, double
 *   16 - two words: a string view (ptr + len), a pair of u64
 *   48 - String, GenVec
 *
 * The defaults are measured. Widening
 * both lists to 1 2 4 8 16 24 32 48 64 cut instructions 8% for a 24-byte
 * value, but cost up to 6% more on EVERY hashmap lookup (a wider switch runs
 * per call) and doubled the hashmap's code. A list entry pays off only for a size that
 * is common in real use.
 *
 * Override either list for a translation unit by defining it before including
 * this header. Every size you add is one more copy of every wrapped body:
 *
 *   #define WC_SPECIALIZE_SIZES(X, ...) X(4, __VA_ARGS__) X(8, __VA_ARGS__)
 *   #include "wc_specialize.h"
 *
 * Keep every listed size also handled by wc_copy_n's switch. A listed size that
 * wc_copy_n does not fast-path still folds (the default memcpy gets a constant
 * size), so this is about clarity, not correctness.
 *
 * CODE SIZE
 * ---------
 * Every listed size is one more inlined copy of the wrapped code. That is the
 * entire trade: one switch per call and N copies of the body, in exchange for
 * removing a per-element branch or libc call.
 *
 *   - Wrap only hot loops. A function called once per program does not care.
 *   - WC_SPECIALIZE   makes |SIZES| + 1 copies of `call` (default: 5).
 *   - WC_SPECIALIZE_2 makes |SIZES| x |SIZES_2ND| + |SIZES| + 1 copies
 *     (default: 4 x 5 + 4 + 1 = 25): every listed pair, every listed first
 *     size with a runtime second size, and the fully runtime arm.
 *   - Use WC_SPECIALIZE_2 only where both sizes gate a copy inside the loop (a
 *     hashmap insert copies key AND value per slot). A lookup that only touches
 *     keys uses WC_SPECIALIZE on the key size.
 *   - Never put a WC_SPECIALIZE inside another one's body. WC_SPECIALIZE_2 is
 *     the 2-D form: one flat switch, one default arm.
 */


/*
 * wc_copy_n - fixed-size copy for common element sizes.
 *
 * Drop-in for memcpy(dst, src, n). Semantics match memcpy exactly, including
 * the restrict contract: dst and src must not overlap. If they may overlap,
 * use memmove instead; this function deliberately does not.
 *
 * The switch sends the common sizes to a memcpy with a literal size. Those
 * memcpy calls are themselves inlined by the compiler (a 1/2/4/8 byte memcpy
 * is just a load and a store), so the switch is really "pick a fixed-size move
 * or fall back to libc". When `n` is a compile-time constant (inside every
 * WC_SPECIALIZE / WC_SPECIALIZE_2 body) the whole switch folds away and only
 * the matching arm survives.
 *
 * n == 0 is a no-op on purpose. A set (HashMap with val_size 0) stores no
 * values and may pass a NULL src for its value copies. memcpy(dst, NULL, 0) is
 * UB (the standard requires valid pointers even for zero bytes, and glibc
 * declares memcpy nonnull, so the compiler may assume src != NULL afterwards).
 * The explicit 0 case avoids the call entirely.
 */
static inline __attribute__((always_inline)) void wc_copy_n(void* restrict dst, const void* restrict src, u64 n)
{
    switch (n) {
    case 0:
        break; // a set's value: src may be NULL, so no memcpy at all
    case 1:
        memcpy(dst, src, 1);
        break;
    case 2:
        memcpy(dst, src, 2);
        break;
    case 4:
        memcpy(dst, src, 4);
        break;
    case 8:
        memcpy(dst, src, 8);
        break;
    case 16:
        memcpy(dst, src, 16);
        break;
    case 24:
        memcpy(dst, src, 24);
        break;
    case 32:
        memcpy(dst, src, 32);
        break;
    case 48:
        memcpy(dst, src, 48);
        break;
    case 64:
        memcpy(dst, src, 64);
        break;
    default:
        memcpy(dst, src, n);
        break;
    }
}

/*
 * wc_equal_n - byte equality for common element sizes.
 *
 * Drop-in for (memcmp(a, b, n) == 0), returning true/false instead of the
 * memcmp tri-state. Use it in key comparisons and anywhere a memcmp would
 * otherwise be a libc call.
 *
 * 4 and 8 bytes compare as one integer instead of a memcmp. That is the common
 * case for hash keys (an int, a u64, a pointer) and the reason this function
 * exists: a memcmp call costs more than the comparison it performs. The memcpy
 * into a local u32/u64 is the standard type-punning idiom: it compiles to a
 * plain load and does not violate strict aliasing.
 *
 * 16 bytes is two 8-byte compares (a string view, a pair of u64).
 *
 * Other sizes fall back to memcmp. With a constant n the compiler already
 * turns a small memcmp into the same chain of loads and compares, so writing
 * them out gains nothing and keeps this function small enough to inline.
 *
 * n == 0 is true without touching either pointer, so both may be NULL.
 */
static inline __attribute__((always_inline)) bool wc_equal_n(const void* a, const void* b, u64 n)
{
    switch (n) {
    case 0:
        return true;
    case 4: {
        u32 x;
        u32 y;
        memcpy(&x, a, 4);
        memcpy(&y, b, 4);
        return x == y;
    }
    case 8: {
        u64 x;
        u64 y;
        memcpy(&x, a, 8);
        memcpy(&y, b, 8);
        return x == y;
    }
    case 16: {
        u64 x0;
        u64 x1;
        u64 y0;
        u64 y1;
        memcpy(&x0, a, 8);
        memcpy(&x1, (const u8*)a + 8, 8);
        memcpy(&y0, b, 8);
        memcpy(&y1, (const u8*)b + 8, 8);
        return (x0 == y0 && x1 == y1) != 0;
    }
    default:
        return memcmp(a, b, n) == 0;
    }
}


/*
 * SIZE LISTS (X-macros)
 *
 * A list is a macro that calls X once per size: X(size, args...). The case
 * macros below are the X. Define either list before including this header to
 * override it for that translation unit.
 */
#ifndef WC_SPECIALIZE_SIZES
#define WC_SPECIALIZE_SIZES(X, ...) X(4, __VA_ARGS__) X(8, __VA_ARGS__) X(16, __VA_ARGS__) X(48, __VA_ARGS__)
#endif

#ifndef WC_SPECIALIZE_SIZES_2ND
#define WC_SPECIALIZE_SIZES_2ND(X, ...) \
    X(0, __VA_ARGS__) X(4, __VA_ARGS__) X(8, __VA_ARGS__) X(16, __VA_ARGS__) X(48, __VA_ARGS__)
#endif


/*
 * MACRO MACHINERY
 * ==================
 * Call sites use only WC_SPECIALIZE and WC_SPECIALIZE_2 (plus wc_copy_n and
 * wc_equal_n above). Names ending in `_` are internal.
 *
 * `call` is variadic (...) in every macro, so code with unparenthesised commas
 * (a compound literal, a designated initialiser) passes through intact.
 */

/*
 * One switch arm: N is an enum constant equal to `value` inside `call`.
 *
 * An enum constant, not a `const u32`: only an enum constant is a true
 * compile-time constant in C. A `const u32` is a read-only variable whose value
 * the compiler MAY propagate. The enum guarantees wc_copy_n(..., N) folds.
 *
 * The braces are load-bearing: they scope the enum, so the next case can
 * declare its own N. N must stay unparenthesised: `enum { (N) = 4 }` is a
 * syntax error, whatever a macro-parentheses linter suggests.
 */
// NOLINTBEGIN(bugprone-macro-parentheses)
#define WC_SPECIALIZE_CASE_(value, N, ...) \
    case (value): {                        \
        enum { N = (value) };              \
        __VA_ARGS__;                       \
        break;                             \
    }

/*
 * WC_SPECIALIZE - run `call` with one runtime size turned into a constant.
 *
 * Usage:
 *   WC_SPECIALIZE(size_expr, NAME, code_using_NAME);
 *
 * Expands to a switch on `size_expr`. Each arm binds NAME to a compile-time
 * constant equal to that case's size, then runs the code. The default arm binds
 * NAME to the runtime size, so the macro is correct for any size, just not
 * faster for unlisted ones.
 *
 * Why the wrapped code must be always_inline
 * ------------------------------------------
 * The macro only makes NAME a constant inside the arm. For the constant to
 * reach the copies in the loop, the loop's function must be inlined into the
 * arm. If it is not inlined, NAME is passed as an ordinary argument and nothing
 * folds. For a data_size of 8 the fill() example above becomes, in effect:
 *
 *   case 8: {
 *       enum { SZ = 8 };
 *       for (u64 i = 0; i < n; i++) {
 *           wc_copy_n(v->data + i * 8, val, 8);   // one 8-byte move
 *       }
 *       break;
 *   }
 *
 * Pitfalls
 *   - `size_expr` is evaluated twice (switch and default). Pass a plain field
 *     or a local, never an expression with side effects.
 *   - NAME must not collide with any identifier in `call`.
 *   - The macro adds `break` after `call`. A bare `break` or `continue` inside
 *     `call` hits the switch, not an outer loop. `return` works.
 *   - It is a statement, not an expression.
 *   - The default arm casts `size_expr` to u32. Element sizes never exceed it.
 */
#define WC_SPECIALIZE(size, N, ...)                              \
    switch (size) {                                              \
        WC_SPECIALIZE_SIZES(WC_SPECIALIZE_CASE_, N, __VA_ARGS__) \
    default: {                                                   \
        const u32 N = (u32)(size);                               \
        __VA_ARGS__;                                             \
        break;                                                   \
    }                                                            \
    }


/*
 * One row of WC_SPECIALIZE_2: N1 is the constant v1, then an inner switch on
 * size2 over WC_SPECIALIZE_SIZES_2ND. The inner default keeps N1 constant and
 * binds N2 to the runtime size2: the one-dimension fallback.
 */
#define WC_SPECIALIZE_2_ROW_(v1, N1, size2, N2, ...)                      \
    case (v1): {                                                          \
        enum { N1 = (v1) };                                               \
        switch (size2) {                                                  \
            WC_SPECIALIZE_SIZES_2ND(WC_SPECIALIZE_CASE_, N2, __VA_ARGS__) \
        default: {                                                        \
            const u32 N2 = (u32)(size2);                                  \
            __VA_ARGS__;                                                  \
            break;                                                        \
        }                                                                 \
        }                                                                 \
        break;                                                            \
    }

/*
 * WC_SPECIALIZE_2 - run `call` with two runtime sizes turned into constants.
 *
 * Usage:
 *   WC_SPECIALIZE_2(size1_expr, NAME1, size2_expr, NAME2, code_using_both);
 *
 * The 2-D form of WC_SPECIALIZE, for a hot loop that copies two things whose
 * sizes are both runtime. A hashmap rehash copies a key of key_size and a value
 * of val_size for every element:
 *
 *   static void map_resize(HashMap* map, u64 new_capacity)
 *   {
 *       ...
 *       WC_SPECIALIZE_2(map->key_size, KS, map->val_size, VS,
 *                       map_rehash_k(map, old_keys, old_vals, old_psls, old_cap, KS, VS));
 *   }
 *
 * For key_size 8, val_size 4 that is, in effect:
 *
 *   case 8: {
 *       enum { KS = 8 };
 *       switch (map->val_size) {
 *       case 4: {
 *           enum { VS = 4 };
 *           map_rehash_k(..., KS, VS);   // 8- and 4-byte moves per element
 *           break;
 *       }
 *       ...
 *
 * Fallback, one dimension at a time
 *   size1 and size2 both listed  -> N1 and N2 constant
 *   only size1 listed            -> N1 constant, N2 runtime (the row's default)
 *   size1 not listed             -> both runtime
 *   The middle step matters: without it an int key with an unlisted 24-byte
 *   value lost the key constant too and ran 21% more instructions than
 *   WC_SPECIALIZE on the key alone, as many as no specialisation at all
 *   (docs/specialization.md). Put the size that matters more first. For a
 *   hashmap that is the key: it is hashed, compared AND copied.
 *
 * Dispatch
 *   Two small switches on 32-bit sizes, once per call. An earlier version
 *   switched once on the pair packed into a u64; its sparse labels compiled to
 *   a compare tree that cost about 18 more instructions per hashmap insert
 *   than the nested form, which made 2-D slower than 1-D for single inserts.
 *   Dispatch runs once per call, so wrap the function that owns the loop.
 *
 * Pitfalls: everything WC_SPECIALIZE warns about, for both sizes. size2 is
 *   evaluated once per row: pass a plain field. Do not nest.
 */
#define WC_SPECIALIZE_2(size1, N1, size2, N2, ...)                            \
    switch (size1) {                                                          \
        WC_SPECIALIZE_SIZES(WC_SPECIALIZE_2_ROW_, N1, size2, N2, __VA_ARGS__) \
    default: {                                                                \
        const u32 N1 = (u32)(size1);                                          \
        const u32 N2 = (u32)(size2);                                          \
        __VA_ARGS__;                                                          \
        break;                                                                \
    }                                                                         \
    }
// NOLINTEND(bugprone-macro-parentheses)


#endif // WC_SPECIALIZE_H

/* ===== hashmap.h ===== */
#line 1 "include/hashmap.h"
#ifndef HASHMAP_H
#define HASHMAP_H





#include <string.h>


/* Generic Hashmap with Ownership Semantics
  - Robin Hood Hashing
  - 3 arrays: keys, vals and psls, plus a scratch area for Robin Hood swaps.
    All four live in ONE allocation: [keys][vals][scratch][psls], each region
    aligned for its element. Create = 1 alloc, resize = 1 alloc + 1 free.
  - PSL: probe sequence length: the distance from hashing location
  - we actually store psl + 1 as psl = 0 means empty bucket
  - Robin Hood Invariant: all keys that hash to i come before keys that hash to i + 1
  - keys and vals are stored inline

  SETS: a HashMap with val_size == 0 is a set. The values region takes no
  memory, `val` arguments may be NULL, and val_ops must be NULL. Use
  HashMap_get_key_ptr to reach a stored element. SET_OF(K) in wc_macros.h
  declares one.

  Memory rules: put copies or moves, del MOVES the value into `out`,
  rehash and Robin Hood shuffles are memcpy only (B5). Zero state: capacity == 0.
*/



#ifndef HASHMAP_INIT_CAPACITY
#define HASHMAP_INIT_CAPACITY 16 // power of two; grows by doubling at load 0.75
#endif


typedef struct {
    u8*           keys; // start of the single block
    u8*           vals;
    u8*           scratch; // STAGE key/val + SWAP key/val, for Robin Hood insertion
    u8*           psls;
    u64           size;
    u64           capacity;
    u32           key_size;
    u32           val_size; // 0: a set
    wc_hash_fn    hash_fn;  // NULL: wc_hash over the key bytes
    wc_compare_fn cmp_fn;   // NULL: byte equality

    // Shared ops vtables for keys and values.
    // Pass NULL for POD types (int, float, flat structs).
    // For types with heap resources define one static ops per type:
    const wc_container_ops* key_ops;
    const wc_container_ops* val_ops;
    const wc_allocator*     alloc;
} HashMap;

_Static_assert(sizeof(HashMap) == 96, "HashMap must be 96 bytes");


// Safely extract callbacks, always NULL-safe on ops itself.
#define MAP_COPY(ops) ((ops) ? (ops)->copy_fn : NULL)
#define MAP_DEL(ops)  ((ops) ? (ops)->del_fn : NULL)


// Create a new HashMap by value.
// hash_fn NULL: wc_hash over the key bytes. cmp_fn NULL: byte equality.
// Both defaults are only correct for keys without pointers.
// key_ops / val_ops: pass NULL for POD types. val_size 0 makes a set.
HashMap HashMap_create(const wc_allocator* a, u32 key_size, u32 val_size, wc_hash_fn hash_fn, wc_compare_fn cmp_fn,
                       const wc_container_ops* key_ops, const wc_container_ops* val_ops)
    __attribute__((nonnull(1), warn_unused_result));

// Destroy all elements and free internal buffers via map->alloc.
// Safe on zeroed/moved-from maps. Leaves struct zeroed.
void HashMap_destroy(HashMap* map) __attribute__((nonnull(1)));

// Deep copy src into a new HashMap allocated from `a`.
HashMap HashMap_copy(const wc_allocator* a, const HashMap* src) __attribute__((nonnull(1, 2), warn_unused_result));

// Transfer ownership from src to dest. src is left zeroed.
void HashMap_move(HashMap* dest, HashMap* src) __attribute__((nonnull(1, 2)));

// Insert or update — COPY semantics. val may be NULL for a set.
// Returns 1 if key existed (updated), 0 if new key inserted.
bool HashMap_put(HashMap* map, const void* key, const void* val) __attribute__((nonnull(1, 2)));

// Insert or update, MOVE semantics: key and val point at the caller's elements, both left zeroed
// (a duplicate key is destroyed; the map keeps its own). val may be NULL for a set.
// Returns 1 if key existed (updated), 0 if new key inserted.
bool HashMap_put_move(HashMap* map, void* key, void* val) __attribute__((nonnull(1, 2)));

// Mixed: key copied, val moved.
bool HashMap_put_val_move(HashMap* map, const void* key, void* val) __attribute__((nonnull(1, 2)));

// Mixed: key moved, val copied.
bool HashMap_put_key_move(HashMap* map, void* key, const void* val) __attribute__((nonnull(1, 2)));

// Get value for key: deep COPY into val (the map keeps its own). Returns 1 if found.
// For owning values prefer HashMap_get_ptr: no copy, no allocation.
bool HashMap_get(const HashMap* map, const void* key, void* val) __attribute__((nonnull(1, 2, 3)));

// Pointer to the stored value, or NULL if key is absent.
const void* HashMap_get_ptr(const HashMap* map, const void* key) __attribute__((nonnull(1, 2)));

__attribute__((nonnull(1, 2))) static inline void* HashMap_get_ptr_mut(HashMap* map, const void* key)
{
    return (void*)HashMap_get_ptr(map, key);
}

// Pointer to the stored KEY equal to `key`, or NULL. For a set this is the
// element; for a map it is the canonical key (e.g. an interned String).
// Never change the bytes the hash or compare reads through it.
const void* HashMap_get_key_ptr(const HashMap* map, const void* key) __attribute__((nonnull(1, 2)));

// Bucket iteration accessors
__attribute__((nonnull(1))) static inline u64 HashMap_bucket_count(const HashMap* map)
{
    return map->capacity;
}

bool        HashMap_bucket_occupied(const HashMap* map, u64 i) __attribute__((nonnull(1)));
const void* HashMap_bucket_key_ptr(const HashMap* map, u64 i) __attribute__((nonnull(1)));
void*       HashMap_bucket_val_ptr(HashMap* map, u64 i) __attribute__((nonnull(1)));

// Delete key. out != NULL: the value is MOVED into it (caller owns it, B7).
// out == NULL: the value is deleted. The key is always deleted.
// Returns 1 if found and deleted, 0 if not found.
bool HashMap_del(HashMap* map, const void* key, void* out) __attribute__((nonnull(1, 2)));

// Check if key exists.
bool HashMap_has(const HashMap* map, const void* key) __attribute__((nonnull(1, 2)));

// Print all key-value pairs. val_print may be NULL (sets print keys only).
void HashMap_print(const HashMap* map, wc_print_fn key_print, wc_print_fn val_print) __attribute__((nonnull(1, 2)));

// Make room for n elements in total so that inserting up to n never resizes.
// No-op if the table is already large enough. Never shrinks.
void HashMap_reserve(HashMap* map, u64 n) __attribute__((nonnull(1)));

// Remove all elements, keep capacity.
void HashMap_clear(HashMap* map) __attribute__((nonnull(1)));

static inline __attribute__((nonnull(1))) u64 HashMap_size(const HashMap* map)
{
    return map->size;
}
static inline __attribute__((nonnull(1))) u64 HashMap_capacity(const HashMap* map)
{
    return map->capacity;
}
static inline __attribute__((nonnull(1))) bool HashMap_empty(const HashMap* map)
{
    return map->size == 0;
}


#endif // HASHMAP_H

#ifdef WC_IMPLEMENTATION

#ifndef WC_WC_ALLOCATOR_IMPL
#define WC_WC_ALLOCATOR_IMPL
/* ===== wc_allocator.c ===== */
#line 1 "src/wc_allocator.c"

#include <stddef.h>



/* wc_libc: the only allocator with vt == NULL */

const wc_allocator wc_libc = {.vt = NULL, .ctx = NULL};


/* wc_borrowed: non-owning allocator */

static void* wc_borrowed_alloc(void* ctx, size_t size, size_t align)
{
    (void)ctx;
    (void)size;
    (void)align;
    return NULL;
}

static void wc_borrowed_free(void* ctx, void* p, size_t size, size_t align)
{
    (void)ctx;
    (void)p;
    (void)size;
    (void)align;
}

static const wc_alloc_vtable wc_borrowed_vt = {
    .alloc   = wc_borrowed_alloc,
    .realloc = NULL, // emulated: alloc fails, so growth fails and p stays valid
    .free    = wc_borrowed_free,
};

const wc_allocator wc_borrowed = {.vt = &wc_borrowed_vt, .ctx = NULL};

#endif /* WC_WC_ALLOCATOR_IMPL */

#ifndef WC_WC_ERRNO_IMPL
#define WC_WC_ERRNO_IMPL
/* ===== wc_errno.c ===== */
#line 1 "src/wc_errno.c"



#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>


/* One definition of the thread-local error variable.
 * Every translation unit that includes wc_error.h sees the extern declaration.
 * This file provides the actual storage.
 */
_Thread_local wc_err wc_errno = WC_OK;


/* Diagnostics reporters (common.h). Defined once, out of line and `cold`:
 * the compiler places them, and every branch that calls them, away from hot
 * code. Both write to stderr so diagnostics never mix into program output. */

// The installed fatal handler; NULL means the default (print + exit).
static wc_fatal_fn g_fatal_handler = NULL;

wc_fatal_fn wc_set_fatal_handler(wc_fatal_fn fn)
{
    wc_fatal_fn prev = g_fatal_handler;
    g_fatal_handler  = fn;
    return prev;
}

void wc_fatal_report(const char* file, int line, const char* func, const char* fmt, ...)
{
    fflush(stdout); // keep ordering with anything already printed

    char    msg[512];
    va_list args;
    va_start(args, fmt);
    vsnprintf(msg, sizeof(msg), fmt, args);
    va_end(args);

    if (g_fatal_handler) {
        g_fatal_handler(file, line, func, msg); // must not return
    } else {
        fprintf(stderr, WC_COLOR_RED "[FATAL] %s:%d:%s(): %s\n" WC_COLOR_RESET, file, line, func, msg);
    }
    exit(EXIT_FAILURE); // default, and the backstop for a handler that returns
}

void wc_warn_report(const char* file, int line, const char* func, const char* fmt, ...)
{
    fflush(stdout);
    fprintf(stderr, WC_COLOR_YELLOW "[WARN] %s:%d:%s(): ", file, line, func);
    va_list args;
    va_start(args, fmt);
    vfprintf(stderr, fmt, args);
    va_end(args);
    fprintf(stderr, "\n" WC_COLOR_RESET);
}

#endif /* WC_WC_ERRNO_IMPL */

#ifndef WC_HASHMAP_IMPL
#define WC_HASHMAP_IMPL
/* ===== hashmap.c ===== */
#line 1 "src/hashmap.c"






#include <stdio.h>
#include <string.h>


#define GET_KEY(map, i) ((map)->keys + ((u64)(map)->key_size * (i)))
#define GET_PSL(map, i) ((map)->psls + (i))
#define GET_VAL(map, i) ((map)->vals + ((u64)(map)->val_size * (i)))

// capacity is always power-of-2 — use bitmask instead of %
#define MAP_MASK(map)    ((map)->capacity - 1)
#define MAP_NEXT(map, i) (((i) + 1) & MAP_MASK(map))

// PSL 0 == empty bucket; stored PSL is (real_psl + 1), starting at 1
#define BUCKET_EMPTY 0

// map_lookup result
typedef enum {
    NOT_FOUND = 0,
    FOUND,
    ROBINHOOD_EXIT, // stopped early: the Robin Hood invariant proves the key is absent
} LOOKUP_RES;

// Single block layout, every region aligned for what it holds:
//   [keys: cap * key_size][vals: cap * val_size][scratch][psls: cap bytes]
// keys/vals/scratch start on MAP_ALIGN; psls are bytes and go last.
//
// scratch layout (KPAD/VPAD = key/val size rounded up to MAP_ALIGN):
//   STAGE region: STAGE_KEY [0, KPAD), STAGE_VAL [KPAD, KPAD + VPAD)
//     used by put to stage the incoming key/val
//   SWAP region:  SWAP_KEY, SWAP_VAL, the same shape right after STAGE
//     used by map_insert for Robin Hood evictions
// The two regions must NOT overlap: map_insert is called with pointers INTO
// the STAGE region, and it writes displaced residents into the SWAP region.

static inline u64 map_align_up(u64 x, u64 a)
{
    return (x + (a - 1)) & ~(a - 1);
}

static inline u64 map_align(u32 key_size, u32 val_size)
{
    u64 ka = wc_align_for_size(key_size);
    u64 va = wc_align_for_size(val_size);
    return ka > va ? ka : va;
}

#define MAP_ALIGN(map) map_align((map)->key_size, (map)->val_size)
#define KPAD(map)      map_align_up((map)->key_size, MAP_ALIGN(map))
#define VPAD(map)      map_align_up((map)->val_size, MAP_ALIGN(map))

#define STAGE_KEY(map) ((map)->scratch)
#define STAGE_VAL(map) ((map)->scratch + KPAD(map))
#define SWAP_KEY(map)  ((map)->scratch + KPAD(map) + VPAD(map))
#define SWAP_VAL(map)  ((map)->scratch + KPAD(map) + VPAD(map) + KPAD(map))

static inline u64 map_scratch_size(u32 key_size, u32 val_size)
{
    u64 al = map_align(key_size, val_size);
    return 2 * (map_align_up(key_size, al) + map_align_up(val_size, al));
}

typedef struct {
    u64 vals, scratch, psls, total; // byte offsets from the block start, and its size
} map_layout;

static inline map_layout map_layout_for(u64 cap, u32 key_size, u32 val_size)
{
    u64        al = map_align(key_size, val_size);
    map_layout l;
    l.vals    = map_align_up(cap * key_size, al);
    l.scratch = map_align_up(l.vals + (cap * val_size), al);
    l.psls    = l.scratch + map_scratch_size(key_size, val_size);
    l.total   = l.psls + cap;
    return l;
}

// One allocation for the whole table; psls zeroed (all buckets empty).
static void map_alloc_block(HashMap* map, u64 cap)
{
    map_layout l = map_layout_for(cap, map->key_size, map->val_size);
    u8*        b = wc_alloc(map->alloc, l.total, MAP_ALIGN(map));
    FATAL_IF(!b, "HashMap: table allocation of %llu bytes failed", (unsigned long long)l.total);

    map->keys     = b;
    map->vals     = b + l.vals;
    map->scratch  = b + l.scratch;
    map->psls     = b + l.psls;
    map->capacity = cap;
    memset(map->psls, 0, cap);
}

static void map_free_block(const HashMap* map, u8* block, u64 cap)
{
    wc_free(map->alloc, block, map_layout_for(cap, map->key_size, map->val_size).total, MAP_ALIGN(map));
}

// Move one element into `dest` (memcpy). `src` is left zeroed.
// size 0 (a set's value): nothing to move, and src may be NULL.
static inline void map_move_into(u32 size, u8* dest, u8* src)
{
    if (size == 0) {
        return;
    }
    memcpy(dest, src, size);
    memset(src, 0, size);
}

// Copy one element into raw `dest`: copy_fn if any, else memcpy.
// size 0 (a set's value): nothing to copy, and src may be NULL.
static inline void map_copy_into(const HashMap* map, const wc_container_ops* ops, u32 size, u8* dest, const void* src)
{
    if (size == 0) {
        return;
    }
    wc_copy_fn cp = ops ? ops->copy_fn : NULL;
    if (cp) {
        cp(map->alloc, dest, src);
    } else {
        memcpy(dest, src, size);
    }
}

// Delete one element in place (if it owns anything).
static inline void map_delete_elm(const wc_container_ops* ops, u8* elm)
{
    wc_delete_fn del = ops ? ops->del_fn : NULL;
    if (del) {
        del(elm);
    }
}

// Destroy an incoming duplicate the container will not keep, and zero it.
static inline void map_consume_dup(const wc_container_ops* ops, u32 size, u8* elm)
{
    if (size == 0) {
        return;
    }
    map_delete_elm(ops, elm);
    memset(elm, 0, size);
}


// A stored PSL is a u8, and 0 means empty. If an insert would push a probe length
// past PSL_LIMIT the hash function is degenerate (a healthy hash at load <= 0.75
// stays under ~30). Die loudly instead of letting the u8 wrap to BUCKET_EMPTY and
// corrupt the table.
#define PSL_LIMIT      250
#define PSL_OVERFLOW() FATAL("HashMap: probe length overflow (degenerate hash function)")

// Home bucket = top log2(capacity) bits of the hash. Top bits make a doubling
// resize send bucket i to 2i or 2i+1, so rehash writes nearly in order.
//
// Default (hash_fn == NULL): wc_hash, called directly so it inlines; with a
// constant `ks` its length branches fold away. Its top bits are already fully
// mixed (tests/test_hashmap.c: hash.avalanche_short_keys), so it is used as is.
//
// Custom hash: multiplied by 2^64 / phi first (Fibonacci hashing). Custom hashes
// often have weak top bits (identity on ints, shifted ids); the multiply folds
// every input bit into the top bits, so any hash_fn spreads.
static inline __attribute__((always_inline)) u64 map_home(const HashMap* map, const void* key, u32 ks)
{
    u64 h = map->hash_fn ? map->hash_fn(key, ks) * 0x9E3779B97F4A7C15ULL : wc_hash(key, ks);
    return h >> (64 - __builtin_ctzll(map->capacity));
}

// The default (cmp_fn == NULL) is byte equality: 4 and 8 byte keys become one
// integer compare.
static inline __attribute__((always_inline)) bool map_key_eq(const HashMap* map, const u8* a, const u8* b, u32 ks)
{
    return (map->cmp_fn ? map->cmp_fn(a, b, ks) == 0 : (int)wc_equal_n(a, b, ks)) != 0;
}


/*
====================PRIVATE DECLARATIONS====================
*/

static u64         map_lookup(const HashMap* map, const u8* key, LOOKUP_RES* res, u8* out_psl);
static void        map_insert(HashMap* map, u8* key, u8* val, u8 psl, u64 idx);
static inline void map_maybe_resize(HashMap* map);
static void        map_resize(HashMap* map, u64 new_capacity);


/*
====================PUBLIC FUNCTIONS====================
*/

HashMap HashMap_create(const wc_allocator* a, u32 key_size, u32 val_size, wc_hash_fn hash_fn, wc_compare_fn cmp_fn,
                       const wc_container_ops* key_ops, const wc_container_ops* val_ops)
{
    FATAL_IF(key_size == 0, "HashMap: key size can't be 0");
    FATAL_IF(val_size == 0 && val_ops != NULL, "HashMap: a set (val_size 0) can't have val_ops");

    HashMap map = {
        .size     = 0,
        .key_size = key_size,
        .val_size = val_size,
        .hash_fn  = hash_fn,
        .cmp_fn   = cmp_fn,
        .key_ops  = key_ops,
        .val_ops  = val_ops,
        .alloc    = a,
    };
    map_alloc_block(&map, HASHMAP_INIT_CAPACITY); // the one allocation
    return map;
}

void HashMap_destroy(HashMap* map)
{
    if (map->capacity == 0) {
        return;
    }

    wc_delete_fn k_del = MAP_DEL(map->key_ops);
    wc_delete_fn v_del = MAP_DEL(map->val_ops);
    if (k_del || v_del) {
        for (u64 i = 0; i < map->capacity; i++) {
            if (*GET_PSL(map, i) == BUCKET_EMPTY) {
                continue;
            }
            if (k_del) {
                k_del(GET_KEY(map, i));
            }
            if (v_del) {
                v_del(GET_VAL(map, i));
            }
        }
    }

    map_free_block(map, map->keys, map->capacity);
    memset(map, 0, sizeof(HashMap));
}

void HashMap_move(HashMap* dest, HashMap* src)
{
    if (dest == src) {
        return;
    }
    *dest = *src;
    memset(src, 0, sizeof(HashMap));
}


// Insert the staged key/val (already owned by the map) at the lookup result.
static inline void map_commit(HashMap* map, u8 psl, u64 slot)
{
    map_insert(map, STAGE_KEY(map), STAGE_VAL(map), psl, slot);
    map_maybe_resize(map);
}

// TODO: do proper boolean returns!

// Insert or update — COPY semantics (B8: both sides keep the value).
// The map deep-copies key and val; the caller keeps its own.
// Returns 1 if key existed (updated), 0 if new key inserted.
bool HashMap_put(HashMap* map, const void* key, const void* val)
{
    FATAL_IF(map->capacity == 0, "HashMap mutation on zeroed/moved-from table");
    WC_ASSERT(val || map->val_size == 0, "val is NULL on a map with values");

    LOOKUP_RES res;
    u8         out_psl;
    u64        slot = map_lookup(map, key, &res, &out_psl);

    if (res == FOUND) {
        map_delete_elm(map->val_ops, GET_VAL(map, slot));
        map_copy_into(map, map->val_ops, map->val_size, GET_VAL(map, slot), val);
        return true;
    }

    map_copy_into(map, map->key_ops, map->key_size, STAGE_KEY(map), key);
    map_copy_into(map, map->val_ops, map->val_size, STAGE_VAL(map), val);
    map_commit(map, out_psl, slot);
    return false;
}


// Insert or update — MOVE semantics: the map takes *key and *val, both zeroed.
// A duplicate key is destroyed (the map keeps its own, B10).
bool HashMap_put_move(HashMap* map, void* key, void* val)
{
    FATAL_IF(map->capacity == 0, "HashMap mutation on zeroed/moved-from table");
    WC_ASSERT(val || map->val_size == 0, "val is NULL on a map with values");

    LOOKUP_RES res;
    u8         out_psl;
    u64        slot = map_lookup(map, key, &res, &out_psl);

    if (res == FOUND) {
        map_delete_elm(map->val_ops, GET_VAL(map, slot));
        map_move_into(map->val_size, GET_VAL(map, slot), val);
        map_consume_dup(map->key_ops, map->key_size, key);
        return true;
    }

    map_move_into(map->key_size, STAGE_KEY(map), key);
    map_move_into(map->val_size, STAGE_VAL(map), val);
    map_commit(map, out_psl, slot);
    return false;
}


// Mixed: key is COPIED, val is MOVED (*val zeroed).
bool HashMap_put_val_move(HashMap* map, const void* key, void* val)
{
    FATAL_IF(map->capacity == 0, "HashMap mutation on zeroed/moved-from table");
    WC_ASSERT(val || map->val_size == 0, "val is NULL on a map with values");

    LOOKUP_RES res;
    u8         out_psl;
    u64        slot = map_lookup(map, key, &res, &out_psl);

    if (res == FOUND) {
        map_delete_elm(map->val_ops, GET_VAL(map, slot));
        map_move_into(map->val_size, GET_VAL(map, slot), val);
        return true;
    }

    map_copy_into(map, map->key_ops, map->key_size, STAGE_KEY(map), key);
    map_move_into(map->val_size, STAGE_VAL(map), val);
    map_commit(map, out_psl, slot);
    return false;
}


// Mixed: key is MOVED (*key zeroed, or destroyed if already present), val is COPIED.
bool HashMap_put_key_move(HashMap* map, void* key, const void* val)
{
    FATAL_IF(map->capacity == 0, "HashMap mutation on zeroed/moved-from table");
    WC_ASSERT(val || map->val_size == 0, "val is NULL on a map with values");

    LOOKUP_RES res;
    u8         out_psl;
    u64        slot = map_lookup(map, key, &res, &out_psl);

    if (res == FOUND) {
        map_delete_elm(map->val_ops, GET_VAL(map, slot));
        map_copy_into(map, map->val_ops, map->val_size, GET_VAL(map, slot), val);
        map_consume_dup(map->key_ops, map->key_size, key);
        return true;
    }

    map_move_into(map->key_size, STAGE_KEY(map), key);
    map_copy_into(map, map->val_ops, map->val_size, STAGE_VAL(map), val);
    map_commit(map, out_psl, slot);
    return false;
}


// Get value for key — deep COPY into val (B8: the map keeps its own).
// Returns 1 if found, 0 if not. Caller owns the copy.
bool HashMap_get(const HashMap* map, const void* key, void* val)
{
    if (map->capacity == 0) {
        return false;
    }

    LOOKUP_RES res;
    u8         out_psl;
    u64        slot = map_lookup(map, key, &res, &out_psl);

    if (res != FOUND) {
        return false;
    }

    map_copy_into(map, map->val_ops, map->val_size, val, GET_VAL(map, slot));
    return true;
}


// Get pointer to value in-place (read-only). Returns NULL if not found.
// The pointer is valid until the next mutation (put/del/resize).
// Do NOT free the returned pointer — the map owns it.
const void* HashMap_get_ptr(const HashMap* map, const void* key)
{
    if (map->capacity == 0) {
        return NULL;
    }

    LOOKUP_RES res;
    u8         out_psl;
    u64        slot = map_lookup(map, key, &res, &out_psl);

    return (res == FOUND) ? GET_VAL(map, slot) : NULL;
}

const void* HashMap_get_key_ptr(const HashMap* map, const void* key)
{
    if (map->capacity == 0) {
        return NULL;
    }

    LOOKUP_RES res;
    u8         out_psl;
    u64        slot = map_lookup(map, key, &res, &out_psl);

    return (res == FOUND) ? GET_KEY(map, slot) : NULL;
}

bool HashMap_bucket_occupied(const HashMap* map, u64 i)
{
    WC_ASSERT(i < map->capacity, "index out of bounds");
    return *GET_PSL(map, i) != BUCKET_EMPTY;
}

const void* HashMap_bucket_key_ptr(const HashMap* map, u64 i)
{
    WC_ASSERT(i < map->capacity, "index out of bounds");
    return GET_KEY(map, i);
}

void* HashMap_bucket_val_ptr(HashMap* map, u64 i)
{
    WC_ASSERT(i < map->capacity, "index out of bounds");
    return GET_VAL(map, i);
}


// Delete key.
// If out != NULL, the value is MOVED into it before deletion (caller takes ownership).
// If out == NULL, the value is destroyed via del_fn (or simply discarded for POD).
// Returns 1 if found and deleted, 0 if not found.
//
// Uses Robin Hood backward-shift deletion to maintain the probe-sequence invariant
// without tombstones: after removing a slot, we shift subsequent entries back one
// position as long as they have PSL > 1 (i.e. they are not sitting at their home slot).
bool HashMap_del(HashMap* map, const void* key, void* out)
{
    FATAL_IF(map->capacity == 0, "HashMap mutation on zeroed/moved-from table");

    LOOKUP_RES res;
    u8         out_psl;
    u64        slot = map_lookup(map, key, &res, &out_psl);

    if (res != FOUND) {
        return false;
    }

    // B7: the value is MOVED into out (caller owns it), or deleted.
    if (out) {
        wc_copy_n(out, GET_VAL(map, slot), map->val_size);
    } else {
        map_delete_elm(map->val_ops, GET_VAL(map, slot));
    }
    map_delete_elm(map->key_ops, GET_KEY(map, slot));

    // Backward-shift deletion: pull subsequent entries one slot back as long as
    // they have PSL > 1.  Entries at their home slot (PSL == 1) must not move.
    // This restores the Robin Hood invariant without tombstones.
    u64 cur = slot;
    for (;;) {
        u64 next     = MAP_NEXT(map, cur);
        u8  next_psl = *GET_PSL(map, next);

        // Stop if next slot is empty or the next entry is already at its home slot.
        if (next_psl <= 1) {
            *GET_PSL(map, cur) = BUCKET_EMPTY;
            break;
        }

        // Shift next entry one slot back; its PSL decreases by 1.
        *GET_PSL(map, cur) = next_psl - 1;
        wc_copy_n(GET_KEY(map, cur), GET_KEY(map, next), map->key_size);
        wc_copy_n(GET_VAL(map, cur), GET_VAL(map, next), map->val_size);

        cur = next;
    }

    map->size--;
    return true;
}


// Check if key exists.
bool HashMap_has(const HashMap* map, const void* key)
{
    if (map->capacity == 0) {
        return false;
    }

    LOOKUP_RES res;
    u8         out_psl;
    map_lookup(map, key, &res, &out_psl);
    return res == FOUND;
}


// Print all key-value pairs.
void HashMap_print(const HashMap* map, wc_print_fn key_print, wc_print_fn val_print)
{
    printf("\t=========\n");
    printf("\tSize: %lu / Capacity: %lu\n", (unsigned long)map->size, (unsigned long)map->capacity);
    printf("\t=========\n");

    for (u64 i = 0; i < map->capacity; i++) {
        if (*GET_PSL(map, i) == BUCKET_EMPTY) {
            continue;
        }
        putchar('\t');
        key_print(GET_KEY(map, i));
        if (val_print) {
            printf(" => ");
            val_print(GET_VAL(map, i));
        }
        putchar('\n');
    }

    printf("\t=========\n");
}


// Remove all elements, keep capacity.
// Destroys all keys and values via their del_fn callbacks, then zeroes the arrays.
void HashMap_clear(HashMap* map)
{
    FATAL_IF(map->capacity == 0, "HashMap_clear on zeroed/moved-from table");

    wc_delete_fn k_del = MAP_DEL(map->key_ops);
    wc_delete_fn v_del = MAP_DEL(map->val_ops);
    if (k_del || v_del) {
        for (u64 i = 0; i < map->capacity; i++) {
            if (*GET_PSL(map, i) == BUCKET_EMPTY) {
                continue;
            }
            if (k_del) {
                k_del(GET_KEY(map, i));
            }
            if (v_del) {
                v_del(GET_VAL(map, i));
            }
        }
    }

    memset(map->psls, 0, map->capacity);
    map->size = 0;
}


// Make room for n elements total without any further resize.
void HashMap_reserve(HashMap* map, u64 n)
{
    FATAL_IF(map->capacity == 0, "HashMap_reserve on zeroed/moved-from table");
    FATAL_IF(n > ((u64)1 << 56), "HashMap_reserve: n too large");

    u64 need = map->capacity;
    while (n * 4 >= need * 3) {
        need *= 2;
    }
    if (need > map->capacity) {
        map_resize(map, need);
    }
}


// Deep copy src into a new map allocated from `a` (A14). Same capacity, so
// every element keeps its bucket: no rehash.
HashMap HashMap_copy(const wc_allocator* a, const HashMap* src)
{
    if (src->capacity == 0) {
        return (HashMap){0};
    }

    HashMap dest = *src; // sizes, functions, ops
    dest.alloc   = a;
    map_alloc_block(&dest, src->capacity);

    wc_copy_fn k_cp = MAP_COPY(src->key_ops);
    wc_copy_fn v_cp = MAP_COPY(src->val_ops);

    if (!k_cp && !v_cp) {
        // Nothing to deep-copy: the layout is identical, so one memcpy of the block.
        memcpy(dest.keys, src->keys, map_layout_for(src->capacity, src->key_size, src->val_size).total);
        return dest;
    }

    for (u64 i = 0; i < src->capacity; i++) {
        u8 psl = *GET_PSL(src, i);
        if (psl == BUCKET_EMPTY) {
            continue;
        }
        *GET_PSL(&dest, i) = psl;
        map_copy_into(&dest, src->key_ops, src->key_size, GET_KEY(&dest, i), GET_KEY(src, i));
        map_copy_into(&dest, src->val_ops, src->val_size, GET_VAL(&dest, i), GET_VAL(src, i));
    }

    return dest;
}


/*
====================PRIVATE FUNCTIONS====================
*/

static inline void map_maybe_resize(HashMap* map)
{
    // integer multiply avoids float — equivalent to load > 0.75
    if (map->size * 4 >= map->capacity * 3) {
        map_resize(map, map->capacity * 2);
    }
}

// Find `key`. Returns the slot where it is (FOUND) or where it would go
// (NOT_FOUND / ROBINHOOD_EXIT), and the probe length at that slot in out_psl.
// ks is the key size, a constant for common sizes (see map_lookup).
static inline __attribute__((always_inline)) u64 map_lookup_k(const HashMap* map, const u8* key, LOOKUP_RES* res,
                                                              u8* out_psl, u32 ks)
{
    u8 psl = 1; // stored PSL 1 = real probe distance 0 (home slot)

    for (u64 i = map_home(map, key, ks);; i = MAP_NEXT(map, i)) {
        u8 slot_psl = *GET_PSL(map, i);
        *out_psl    = psl;

        if (slot_psl == BUCKET_EMPTY) {
            *res = NOT_FOUND;
            return i;
        }

        if (slot_psl < psl) {
            // The resident is closer to its home than we are. Under Robin Hood our
            // key would have displaced it on insert, so it can't be further ahead.
            *res = ROBINHOOD_EXIT;
            return i;
        }

        if (map_key_eq(map, map->keys + ((u64)ks * i), key, ks)) {
            *res = FOUND;
            return i;
        }

        psl++;
    }
}

static u64 map_lookup(const HashMap* map, const u8* key, LOOKUP_RES* res, u8* out_psl)
{
    WC_SPECIALIZE(map->key_size, KS, return map_lookup_k(map, key, res, out_psl, KS));
}


// Place key/val (already owned by the map) starting at bucket idx with probe
// length psl. Only relocates raw bytes: never calls copy/del (B5).
//
// Walk to the first empty slot or the first resident we out-rank, copying
// nothing. An empty slot is filled straight from key/val. Only when a resident
// must be displaced does the element in hand move into scratch: it alternates
// between STAGE and SWAP, so it never aliases the slot being written.
//
// ks/vs are the key/val sizes. map_insert passes both as compile-time constants
// for the common size pairs (WC_SPECIALIZE_2), so every copy below is a
// fixed-size move and every slot address is a constant-stride multiply.
static inline __attribute__((always_inline)) void map_insert_k(HashMap* map, u8* key, u8* val, u8 psl0, u64 idx, u32 ks,
                                                               u32 vs)
{
#define KEY_AT(i) (map->keys + ((u64)ks * (i)))
#define VAL_AT(i) (map->vals + ((u64)vs * (i)))

    u32 psl = psl0;
    u64 i   = idx;

    for (;; i = MAP_NEXT(map, i)) {
        u8 slot_psl = *GET_PSL(map, i);

        if (slot_psl == BUCKET_EMPTY) {
            *GET_PSL(map, i) = (u8)psl;
            wc_copy_n(KEY_AT(i), key, ks);
            wc_copy_n(VAL_AT(i), val, vs);
            map->size++;
            return;
        }
        if (slot_psl < psl) {
            break;
        }
        if (++psl > PSL_LIMIT) {
            PSL_OVERFLOW();
        }
    }

    u8* cur_key = STAGE_KEY(map);
    u8* cur_val = STAGE_VAL(map);
    u8* swp_key = SWAP_KEY(map);
    u8* swp_val = SWAP_VAL(map);

    // key/val may already be STAGE (put): copy only if not
    if (key != cur_key) {
        wc_copy_n(cur_key, key, ks);
    }
    if (val != cur_val) {
        wc_copy_n(cur_val, val, vs);
    }

    for (;; i = MAP_NEXT(map, i)) {
        u8 slot_psl = *GET_PSL(map, i);

        if (slot_psl == BUCKET_EMPTY) {
            *GET_PSL(map, i) = (u8)psl;
            wc_copy_n(KEY_AT(i), cur_key, ks);
            wc_copy_n(VAL_AT(i), cur_val, vs);
            map->size++;
            return;
        }

        // Robin Hood: evict the resident closer to home, put ours in its slot
        if (slot_psl < psl) {
            wc_copy_n(swp_key, KEY_AT(i), ks);
            wc_copy_n(swp_val, VAL_AT(i), vs);

            *GET_PSL(map, i) = (u8)psl;
            wc_copy_n(KEY_AT(i), cur_key, ks);
            wc_copy_n(VAL_AT(i), cur_val, vs);

            // the evicted resident is the element in hand now
            u8* tmp = cur_key;
            cur_key = swp_key;
            swp_key = tmp;
            tmp     = cur_val;
            cur_val = swp_val;
            swp_val = tmp;
            psl     = slot_psl;
        }

        if (++psl > PSL_LIMIT) {
            PSL_OVERFLOW();
        }
    }

#undef KEY_AT
#undef VAL_AT
}

static void map_insert(HashMap* map, u8* key, u8* val, u8 psl0, u64 idx)
{
    WC_SPECIALIZE_2(map->key_size, KS, map->val_size, VS, map_insert_k(map, key, val, psl0, idx, KS, VS));
}


// Reinsert every element of the old block. Keys are already unique, so no
// lookup and no compare: each element starts at its home bucket and Robin Hood
// insertion does the rest. Raw bytes move, no copy/del (B5).
static inline __attribute__((always_inline)) void map_rehash_k(HashMap* map, u8* old_keys, u8* old_vals,
                                                               const u8* old_psls, u64 old_cap, u32 ks, u32 vs)
{
    for (u64 i = 0; i < old_cap; i++) {
        if (old_psls[i] == BUCKET_EMPTY) {
            continue;
        }
        u8* key = old_keys + ((u64)ks * i);
        u8* val = old_vals + ((u64)vs * i);
        map_insert_k(map, key, val, 1, map_home(map, key, ks), ks, vs);
    }
}

// Move everything into a new block of new_capacity (a power of two).
static void map_resize(HashMap* map, u64 new_capacity)
{
    if (new_capacity < HASHMAP_INIT_CAPACITY) {
        new_capacity = HASHMAP_INIT_CAPACITY;
    }

    u8* old_keys = map->keys;
    u8* old_vals = map->vals;
    u8* old_psls = map->psls;
    u64 old_cap  = map->capacity;

    map_alloc_block(map, new_capacity);
    map->size = 0;

    WC_SPECIALIZE_2(map->key_size, KS, map->val_size, VS,
                    map_rehash_k(map, old_keys, old_vals, old_psls, old_cap, KS, VS));

    map_free_block(map, old_keys, old_cap);
}

#undef GET_KEY
#undef GET_PSL
#undef GET_VAL
#undef MAP_MASK
#undef MAP_NEXT
#undef BUCKET_EMPTY
#undef MAP_ALIGN
#undef KPAD
#undef VPAD
#undef STAGE_KEY
#undef STAGE_VAL
#undef SWAP_KEY
#undef SWAP_VAL
#undef PSL_LIMIT
#undef PSL_OVERFLOW
#undef KEY_AT
#undef VAL_AT
#endif /* WC_HASHMAP_IMPL */

#endif /* WC_IMPLEMENTATION */

#endif /* WC_HASHMAP_SINGLE_H */
