/* matrix_single.h: generated by tools/make_single_header.py. Do not edit.
 * Contains: wc_allocator, common, wc_errno, matrix
 *
 * In exactly one .c file:
 *     #define WC_IMPLEMENTATION
 *     #include "matrix_single.h"
 */
#ifndef WC_MATRIX_SINGLE_H
#define WC_MATRIX_SINGLE_H

/* ===== wc_allocator.h ===== */
#line 1 "include/wc_allocator.h"
#ifndef WC_ALLOCATOR_H
#define WC_ALLOCATOR_H

#include <assert.h>
#include <stdalign.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>


#define WC_MAX_ALIGN alignof(max_align_t)

/* libc fallbacks */

static inline void* wc_libc_alloc(size_t n, size_t align)
{
    if (align <= WC_MAX_ALIGN) {
        return malloc(n);
    }

    size_t rounded = (n + align - 1) & ~(align - 1); // aligned_alloc: size % align == 0
    if (rounded < n) {
        return NULL; // overflow
    }
#ifdef _MSC_VER
    return _aligned_malloc(rounded, align);
#else
    return aligned_alloc(align, rounded);
#endif
}

static inline void wc_libc_free(void* p, size_t align)
{
#ifdef _MSC_VER
    if (align > WC_MAX_ALIGN) {
        _aligned_free(p); // MSVC can't free() these
        return;
    }
#endif
    (void)align;
    free(p); // POSIX/glibc: fine for both
}

static inline void* wc_libc_realloc(void* p, size_t old_n, size_t n, size_t align)
{
    if (align <= WC_MAX_ALIGN) {
        return realloc(p, n);
    }

    // libc realloc doesn't preserve alignment above max_align_t: alloc, copy, free
    void* q = wc_libc_alloc(n, align);
    if (!q) {
        return NULL; // p left untouched
    }
    memcpy(q, p, old_n < n ? old_n : n);
    wc_libc_free(p, align);
    return q;
}



/*
 * ALLOCATOR API
 *
 * No global allocator exists: every data structure receives its allocator at
 * construction, stores it, and uses it for every allocation.
 *
 * An allocator is a (vtable, ctx) pair. It is passed and stored as `const wc_allocator*`
 *   - the pointer is never NULL; libc is WC_LIBC, nothing else.
 *   - the pointed-to allocator must outlive every container that stores it.
 *     WC_LIBC and WC_BORROWED are static; Arena, ChainArena and wc_test_alloc
 *     embed their own allocator, so the arena's lifetime covers it
 *   - `const`: a call never changes the (vt, ctx) pair; ctx is what mutates
 *
 * Contract (the wc_* wrappers enforce it, backends may rely on it):
 *   - callbacks are never called with p == NULL or size == 0
 *   - `align` is a power of two >= 1 and is an ADDRESS alignment
 *   - `free` / `realloc` receive the exact size and align of the block's last
 *     alloc/realloc (wc_test_alloc verifies this; arenas ignore it)
 *   - `realloc` failure returns NULL and leaves p valid
 *   - missing `realloc` is emulated (alloc + copy + free); missing `free` is a no-op
 *   - wc_alloc(a, 0, ..) returns NULL without calling the backend
 *   - wc_realloc(a, NULL, 0, n, ..) == wc_alloc(a, n, ..)
 *   - wc_realloc(a, p, old, 0, ..) frees p and returns NULL
 *
*/
typedef struct {
    void* (*alloc)(void* ctx, size_t size, size_t align);
    void* (*realloc)(void* ctx, void* p, size_t old_size, size_t new_size, size_t align); // may be NULL
    void (*free)(void* ctx, void* p, size_t size, size_t align);                          // may be NULL
} wc_alloc_vtable;

typedef struct {
    const wc_alloc_vtable* vt;  // NULL => libc (only ever true for wc_libc)
    void*                  ctx; // Arena*, ChainArena*, test allocator, ...
} wc_allocator;

_Static_assert(sizeof(wc_allocator) == 16, "wc_allocator must stay 16 bytes");

// The libc allocator. Defined once in wc_allocator.c.
extern const wc_allocator wc_libc;
#define WC_LIBC (&wc_libc)

// Non-owning allocator: alloc -> NULL, free -> no-op. A container built on it
// wraps caller memory, cannot grow, and frees nothing on destroy.
extern const wc_allocator wc_borrowed;
#define WC_BORROWED (&wc_borrowed)

static inline __attribute__((nonnull(1))) int wc_is_libc(const wc_allocator* a)
{
    return a->vt == NULL;
}

// Same backend and same context: memory from one may be freed through the other.
static inline __attribute__((nonnull(1, 2))) int wc_same(const wc_allocator* a, const wc_allocator* b)
{
    return a == b || (a->vt == b->vt && a->ctx == b->ctx);
}

#define WC_ALLOC_ASSERT_ALIGN(align) \
    assert((align) != 0 && ((align) & ((align) - 1)) == 0 && "align must be a power of two >= 1")

static inline __attribute__((nonnull(1))) void* wc_alloc(const wc_allocator* a, size_t n, size_t align)
{
    WC_ALLOC_ASSERT_ALIGN(align);
    if (n == 0 || n > (size_t)PTRDIFF_MAX) { // > PTRDIFF_MAX: overflowed size (see wc_mul)
        return NULL;
    }
    return a->vt ? a->vt->alloc(a->ctx, n, align) : wc_libc_alloc(n, align);
}

static inline __attribute__((nonnull(1))) void wc_free(const wc_allocator* a, void* p, size_t n, size_t align)
{
    WC_ALLOC_ASSERT_ALIGN(align);
    if (!p) {
        return;
    }
    if (!a->vt) {
        wc_libc_free(p, align);
        return;
    }
    if (a->vt->free) {
        a->vt->free(a->ctx, p, n, align);
    }
}

static inline __attribute__((nonnull(1))) void* wc_realloc(const wc_allocator* a, void* p, size_t old_n, size_t n,
                                                           size_t align)
{
    WC_ALLOC_ASSERT_ALIGN(align);
    if (!p) {
        return wc_alloc(a, n, align);
    }
    if (n == 0) {
        wc_free(a, p, old_n, align);
        return NULL;
    }
    if (n > (size_t)PTRDIFF_MAX) {
        return NULL; // overflowed size: fail, p stays valid
    }
    if (!a->vt) {
        return wc_libc_realloc(p, old_n, n, align);
    }
    if (a->vt->realloc) {
        return a->vt->realloc(a->ctx, p, old_n, n, align);
    }

    // backend without realloc: emulate
    void* q = a->vt->alloc(a->ctx, n, align);
    if (!q) {
        return NULL; // p left untouched
    }
    memcpy(q, p, old_n < n ? old_n : n);
    wc_free(a, p, old_n, align);
    return q;
}

// count * size, saturating to SIZE_MAX on overflow. SIZE_MAX can never be
// satisfied, so an overflowing request fails in the backend instead of wrapping
// to a small size. (Returning 0 would be wrong: realloc to 0 means free.)
static inline size_t wc_mul(size_t count, size_t size)
{
    size_t r;
    return (int)__builtin_mul_overflow(count, size, &r) ? SIZE_MAX : r;
}

// Smallest safe alignment for elements of `elm_size` bytes: the
// largest power of two dividing elm_size, capped at WC_MAX_ALIGN. Valid because
// sizeof(T) is always a multiple of alignof(T).
static inline size_t wc_align_for_size(size_t elm_size)
{
    if (elm_size == 0) {
        return 1;
    }
    size_t lowbit = elm_size & (~elm_size + 1);
    return lowbit < WC_MAX_ALIGN ? lowbit : WC_MAX_ALIGN;
}


/* typed helpers (allocator first)
 * Free takes the POINTER, not a type: size and align come from *p, so a wrong
 * type can't be passed*/

#define WC_NEW(a, T)      ((T*)wc_alloc((a), sizeof(T), alignof(T)))
#define WC_NEW_N(a, T, n) ((T*)wc_alloc((a), wc_mul((n), sizeof(T)), alignof(T)))
#define WC_REALLOC_N(a, p, old_n, n)                                                               \
    ((__typeof__(p))wc_realloc((a), (p), wc_mul((old_n), sizeof(*(p))), wc_mul((n), sizeof(*(p))), \
                               alignof(__typeof__(*(p)))))
#define WC_FREE(a, p)      (wc_free((a), (p), sizeof(*(p)), alignof(__typeof__(*(p)))))
#define WC_FREE_N(a, p, n) (wc_free((a), (p), wc_mul((n), sizeof(*(p))), alignof(__typeof__(*(p)))))


#endif // WC_ALLOCATOR_H

/* ===== common.h ===== */
#line 1 "include/common.h"
#ifndef COMMON_H
#define COMMON_H



/*
 * WCtoolkit
 * Copyright (c) 2026 Wasi Ullah (PAKIWASI)
 * Licensed under the MIT License. See LICENSE file for details.
 */



// LOGGING/ERRORS

#include <stdalign.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>

// ANSI Color Codes
#define WC_COLOR_RESET  "\033[0m"
#define WC_COLOR_RED    "\033[1;31m"
#define WC_COLOR_YELLOW "\033[1;33m"
#define WC_COLOR_GREEN  "\033[1;32m"
#define WC_COLOR_BLUE   "\033[1;34m"
#define WC_COLOR_CYAN   "\033[1;36m"



/*
 * DIAGNOSTICS
 *
 *   SURVIVES EVERY BUILD (Debug and Release)
 *     FATAL(fmt, ...)                 abort with a message
 *
 *     FATAL_IF(cond, fmt, ...)        abort if cond is TRUE. Absolute failures
 *                                     only: allocation failed, mutation of a
 *                                     zeroed (moved-from/destroyed) container.
 *
 *     WARN(fmt, ...)                  print a warning to stderr, continue
 *
 *     WARN_IF(cond, fmt, ...)         warn if cond is TRUE, continue
 *
 *     WARN_IF_RET(cond, ret, fmt, ...) warn and `return ret` if cond is TRUE
 *                                     (GNU statement expression can return)
 *
 *     LOG(fmt, ...)                   print to stderr
 *
 *     LOG_IF(cond, fmt, ...)          log if cond is TRUE
 *
 *   STRIPPED UNDER NDEBUG (Release)
 *
 *     WC_ASSERT(cond, fmt, ...)       abort if cond is FALSE. cond is the
 *                                     INVARIANT (`i < size`), not the failure.
 *                                     For programmer errors: bounds, API misuse.
 *                                     Release: cond is NOT evaluated (no side
 *                                     effects run) but still type-checked.
 *
 * The rule: if continuing past the failure would corrupt memory even in a
 * correct program (an allocator returned NULL), use FATAL_IF. If the failure
 * means the CALLER has a bug, use WC_ASSERT
 *
 * Branch prediction: failure paths are WC_UNLIKELY, and the reporters are
 * `cold, noinline` functions defined once in wc_errno.c. The compiler moves
 * every failure branch (argument setup + call) out of the hot path into
 * .text.unlikely, so a check costs one compare and one not-taken branch.
*/

#define WC_LIKELY(x)   __builtin_expect(!!(x), 1)
#define WC_UNLIKELY(x) __builtin_expect(!!(x), 0)

__attribute__((cold, noinline, noreturn, format(printf, 4, 5))) void
wc_fatal_report(const char* file, int line, const char* func, const char* fmt, ...);

/* Fatal handler. Every FATAL / FATAL_IF formats its message and calls the
 * installed handler. The handler must not return: abort, exit, or longjmp out
 * (tests can verify that something FATALs). If it does return, the program
 * exits. NULL restores the default (print to stderr, exit(EXIT_FAILURE)).
 * Returns the previous handler. Set it once at startup: it is not thread-local. */
typedef void (*wc_fatal_fn)(const char* file, int line, const char* func, const char* msg);
wc_fatal_fn wc_set_fatal_handler(wc_fatal_fn fn);

__attribute__((cold, noinline, format(printf, 4, 5))) void wc_warn_report(const char* file, int line, const char* func,
                                                                          const char* fmt, ...);


/* SURVIVES EVERY BUILD */

#define FATAL(fmt, ...) wc_fatal_report(__FILE__, __LINE__, __func__, fmt, ##__VA_ARGS__)

#define FATAL_IF(cond, fmt, ...) ((void)(WC_UNLIKELY(cond) && (FATAL("(%s): " fmt, #cond, ##__VA_ARGS__), 0)))

#define WARN(fmt, ...) wc_warn_report(__FILE__, __LINE__, __func__, fmt, ##__VA_ARGS__)

#define WARN_IF(cond, fmt, ...) ((void)(WC_UNLIKELY(cond) && (WARN("(%s): " fmt, #cond, ##__VA_ARGS__), 0)))

#define WARN_IF_RET(cond, ret, fmt, ...)              \
    ({                                                \
        if (WC_UNLIKELY(cond)) {                      \
            WARN("(%s): " fmt, #cond, ##__VA_ARGS__); \
            return ret;                               \
        }                                             \
        (void)0;                                      \
    })

// stderr, like WARN/FATAL: diagnostics never mix into program output.
#define LOG(fmt, ...) \
    ((void)fprintf(stderr, WC_COLOR_CYAN "[LOG] %s(): " fmt "\n" WC_COLOR_RESET, __func__, ##__VA_ARGS__))

#define LOG_IF(cond, fmt, ...) ((void)((cond) && (LOG(fmt, ##__VA_ARGS__), 0)))


/* STRIPPED UNDER NDEBUG */

#ifdef NDEBUG
// Not evaluated (sizeof of an int expression), still compiled: a stale field
// name or type error inside an assert breaks the Release build too, and
// variables used only in asserts don't trigger unused warnings.
#define WC_ASSERT(cond, fmt, ...) ((void)sizeof(!(cond)))
#else
#define WC_ASSERT(cond, fmt, ...) \
    ((void)(WC_LIKELY(cond) || (FATAL("assertion (%s) failed: " fmt, #cond, ##__VA_ARGS__), 0)))
#endif


// Token pasting that expands its arguments first. `a##b` pastes BEFORE expansion,
// so WC_CAT_(x, __LINE__) gives `x__LINE__`; the extra level expands __LINE__ to
// 42 first and then pastes, giving `x42`. Used for __COUNTER__/__LINE__ names.
#define WC_CAT_(a, b) a##b
#define WC_CAT(a, b)  WC_CAT_(a, b)


// TYPES

#include <stdbool.h>
#include <stdint.h>

typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;

typedef int8_t  i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;

// we are using unsigned indices/sizes
#define WC_NOT_FOUND ((u64) - 1)


// GENERIC FUNCTIONS


/* ELEMENT OPS
 *
 * Memory rule B5: every element is TRIVIALLY RELOCATABLE. A container may move
 * an element to another address with a raw memcpy (growth, insert/remove shifts,
 * hash table shuffles, queue compaction, taking an element out) and never asks
 * the element first. A type that holds a pointer to itself, or that something
 * outside points into, cannot be stored by value: store it by pointer.
 *
 */

// Deep-copy `src` INTO `dest`, allocating any owned resources from `dst`.
// `dest` is uninitialised raw slot memory: never read or free it (B3).
// Called ONLY when both sides keep the value (B8).
typedef void (*wc_copy_fn)(const wc_allocator* dst, void* dest, const void* src);
// Release owned resources of the element (not the slot). Elements that own
// memory store their own allocator, so no allocator argument is needed (B2).
typedef void (*wc_delete_fn)(void* elm);
typedef void (*wc_print_fn)(const void* elm);
typedef int (*wc_compare_fn)(const void* a, const void* b, u64 size);


// vtable: one instance shared across all objects of the same type.
// Pass NULL for any callback not needed (no copy_fn: copies are memcpy;
// no del_fn: nothing is freed per element). For plain data pass NULL ops.
typedef struct {
    wc_copy_fn   copy_fn; // Deep copy function for owned resources (or NULL)
    wc_delete_fn del_fn;  // Cleanup function for owned resources (or NULL)
} wc_container_ops;


// Heap-box a value-returning constructor through allocator A:
//   GenVec* v = WC_BOX_IN(A, GenVec, GenVec_create, 8, sizeof(int), NULL);
// Invariant: the shell comes from the same allocator the child stores, so a
// by-pointer delete can free the shell with the child's own allocator.
#define WC_BOX_IN(A, T, init_fn, ...)                              \
    ({                                                             \
        T* _wbx_p = wc_alloc(A, sizeof(T), alignof(T));            \
        FATAL_IF(!_wbx_p, "WC_BOX_IN(" #T "): allocation failed"); \
        *_wbx_p = init_fn(A, __VA_ARGS__);                         \
        _wbx_p;                                                    \
    })


// COMMON SIZES

#define KB (1 << 10)
#define MB (1 << 20)

#define nKB(n) ((u64)((n) * KB))
#define nMB(n) ((u64)((n) * MB))


// RAW BYTES TO HEX

static inline void print_hex(const u8* ptr, u64 size, u32 bytes_per_line)
{
    if (ptr == NULL || size == 0 || bytes_per_line == 0) {
        return;
    }

    // hex rep 0-15
    const char* hex = "0123456789ABCDEF";

    for (u64 i = 0; i < size; i++) {
        u8 val1 = ptr[i] >> 4;   // get upper 4 bits as num b/w 0-15
        u8 val2 = ptr[i] & 0x0F; // get lower 4 bits as num b/w 0-15

        printf("%c%c", hex[val1], hex[val2]);

        // Add space or newline appropriately
        if ((i + 1) % bytes_per_line == 0) {
            printf("\n");
        } else if (i < size - 1) {
            printf(" ");
        }
    }

    // Add final newline if we didn't just print one
    if (size % bytes_per_line != 0) {
        printf("\n");
    }
}


// TEST HELPERS

// Generic print functions for primitive types
static inline void wc_print_int(const void* elm)
{
    printf("%d ", *(int*)elm);
}
static inline void wc_print_u32(const void* elm)
{
    printf("%u ", *(u32*)elm);
}
static inline void wc_print_u64(const void* elm)
{
    printf("%llu ", (unsigned long long)*(u64*)elm);
}
static inline void wc_print_float(const void* elm)
{
    printf("%.2f ", (double)*(float*)elm);
}
static inline void wc_print_char(const void* elm)
{
    printf("%c ", *(char*)elm);
}
static inline void wc_print_cstr(const void* elm)
{
    printf("%s ", (const char*)elm);
}


#endif // COMMON_H

/* ===== wc_errno.h ===== */
#line 1 "include/wc_errno.h"
#ifndef WC_ERRNO_H
#define WC_ERRNO_H

#include <stdio.h>


/* wc_errno.h — Error reporting for WCtoolkit
 *
 * Three tiers:
 *
 *   FATAL_IF     Resource failures and dead state, in EVERY build: an
 *                allocator returned NULL, or a zeroed (moved-from/destroyed)
 *                container was mutated. Continuing would corrupt memory.
 *
 *   WC_ASSERT    Programmer errors: null pointer, out of bounds, size 0.
 *                Takes the INVARIANT (`i < size`). Crashes with a message in
 *                debug builds; compiled out under NDEBUG (condition not
 *                evaluated). Never use it for allocation failure.
 *
 *   (WARN_IF / LOG_IF report and continue, in every build. Full list and
 *    the release/debug split: the DIAGNOSTICS block in common.h.)
 *
 *   wc_errno     Expected conditions: pop on empty, Arena full.
 *                Function returns NULL / 0 / void. wc_errno says why.
 *                Ignore it if you don't care. Check it if you do.
 *
 *
 * USAGE
 * -----
 *   // Check a single call:
 *   wc_errno = WC_OK;
 *   void* p = Arena_alloc(Arena, size);
 *   if (!p && wc_errno == WC_ERR_FULL) { ... }
 *
 *   // Check a batch — wc_errno stays set if any call failed:
 *   wc_errno = WC_OK;
 *   float* a = Arena_alloc(Arena, 256);
 *   float* b = Arena_alloc(Arena, 256);
 *   if (wc_errno) { wc_perror("alloc"); }
 *
 *
 * RULES
 * -----
 *   1. Successful calls do NOT clear wc_errno — clear it yourself.
 *   2. Check the return value first. wc_errno tells you WHY, not WHETHER.
 *   3. wc_errno is thread-local. Each thread has its own copy.
 *
 *
 * WHAT SETS wc_errno
 * ------------------
 *   Arena_alloc, Arena_alloc_aligned      WC_ERR_FULL    Arena exhausted
 *   GenVec_pop, GenVec_front, GenVec_back WC_ERR_EMPTY   vec is empty
 *   Queue_pop, Queue_peek, Queue_peek_ptr WC_ERR_EMPTY   Queue is empty
 *   Stack_pop, Stack_peek                 WC_ERR_EMPTY   Stack is empty
 */


typedef enum {
    WC_OK = 0,
    WC_ERR_FULL,       // Arena exhausted / container at capacity
    WC_ERR_EMPTY,      // pop or peek on empty container
    WC_ERR_INVALID_OP, // call to a function with preconditions not met
} wc_err;

static inline const char* wc_strerror(wc_err e)
{
    switch (e) {
    case WC_OK:
        return "ok";
    case WC_ERR_FULL:
        return "full";
    case WC_ERR_EMPTY:
        return "empty";
    case WC_ERR_INVALID_OP:
        return "invalid op";
    default:
        return "unknown";
    }
}

/* Defined in wc_errno.c:
 *   _Thread_local wc_err wc_errno = WC_OK;
 */
extern _Thread_local wc_err wc_errno;

/* Print last error — same pattern as perror(3).
 *   wc_perror("Arena_alloc");  ->  "Arena_alloc: full"
 */
static inline void wc_perror(const char* prefix)
{
    if (prefix && prefix[0]) {
        fprintf(stderr, "%s: %s\n", prefix, wc_strerror(wc_errno));
    } else {
        fprintf(stderr, "%s\n", wc_strerror(wc_errno));
    }
}


/* Internal macros (library use only)
 * ------------------------------------
 * WC_SET_RET — for expected-condition sites (use WARN_IF_RET to also print).
 * Sets wc_errno silently and returns. No print.
 *
 *   WC_SET_RET(WC_ERR_EMPTY, vec->size == 0, );     void return
 *   WC_SET_RET(WC_ERR_FULL,  cond,           NULL); pointer return
 */
#define WC_SET_RET(err_code, cond, ret) \
    ({                                  \
        if (WC_UNLIKELY(cond)) {        \
            wc_errno = (err_code);      \
            return ret;                 \
        }                               \
    })

/* WC_PROPAGATE_RET — exit immediately if a callee already set wc_errno.
 *
 *   some_internal_fn(vec);
 *   WC_PROPAGATE_RET( );   // exits if some_internal_fn set wc_errno
 */
#define WC_PROPAGATE_RET(ret)                 \
    ({                                        \
        if (WC_UNLIKELY(wc_errno != WC_OK)) { \
            return ret;                       \
        }                                     \
    })

#endif // WC_ERRNO_H

/* ===== matrix.h ===== */
#line 1 "include/matrix.h"
#ifndef MATRIX_H
#define MATRIX_H






// ROW MAJOR 2D MATRIX
//
// Value type. Storage comes from `alloc`, which the matrix stores (32 bytes).
// Zero state (moved-from / destroyed) is dead: only destroy or re-create it.
// Every mutating op on a zeroed matrix (m == 0) is an unconditional FATAL.
typedef struct {
    float*       data;
    u64          m; // rows
    u64          n; // cols
    const wc_allocator* alloc;
} Matrixf;

_Static_assert(sizeof(Matrixf) == 32, "Matrixf layout: data + m + n + allocator pointer");


// CREATION AND DESTRUCTION
// ============================================================================

// m x n matrix, storage from `a`. Contents are uninitialised.
Matrixf matrix_create(const wc_allocator* a, u64 m, u64 n) __attribute__((nonnull(1), warn_unused_result));

// m x n matrix from `a`, filled from a row-major array of m * n floats.
Matrixf matrix_create_arr(const wc_allocator* a, u64 m, u64 n, const float* arr)
    __attribute__((nonnull(4), warn_unused_result));

// Wrap caller-owned memory (stack array, static buffer). Uses WC_BORROWED:
// destroy frees nothing. `data` must outlive the matrix.
Matrixf matrix_create_buf(u64 m, u64 n, float* data) __attribute__((nonnull(3), warn_unused_result));

// Free storage through mat->alloc and zero the struct. Safe on zeroed matrices.
void matrix_destroy(Matrixf* mat) __attribute__((nonnull(1)));

// Deep copy of `src` into a new matrix allocated from `a` (never inherits src->alloc).
Matrixf matrix_copy(const wc_allocator* a, const Matrixf* src) __attribute__((nonnull(1, 2), warn_unused_result));

// Transfer: dest takes src's storage and allocator, src is left zeroed.
// dest must be raw or already destroyed (it is overwritten, not freed).
void matrix_move(Matrixf* dest, Matrixf* src) __attribute__((nonnull(1, 2)));


// SETTERS
// ============================================================================

/* Preferred method for setting values from arrays
   For direct arrays (float[len]){...} ROW MAJOR or (float[row][col]){{...},{...}} MORE EXPLICIT
   
   Usage:
       matrix_set_val_arr(mat, 9, (float*)(float[3][3]){
           {1, 2, 3},
           {4, 5, 6},
           {7, 8, 9}
       });
*/
void matrix_set_val_arr(Matrixf* mat, u64 count, const float* arr) __attribute__((nonnull(1, 3)));

// for 2D arrays (array of pointers)
void matrix_set_val_arr2(Matrixf* mat, u64 m, u64 n, const float** arr2) __attribute__((nonnull(1, 4)));

// set the value at position (i, j) where i is row and j is column
void matrix_set_elm(Matrixf* mat, float elm, u64 i, u64 j) __attribute__((nonnull(1)));

float matrix_get_elm(const Matrixf* mat, u64 i, u64 j) __attribute__((nonnull(1)));


// BASIC OPERATIONS
// ============================================================================

// Matrix addition: out = a + b
// out must NOT alias a or b (restrict enables auto-vectorization)
void matrix_add(Matrixf* restrict out, const Matrixf* restrict a, const Matrixf* restrict b)
    __attribute__((nonnull(1, 2, 3)));

// Matrix subtraction: out = a - b
// out must NOT alias a or b (restrict enables auto-vectorization)
void matrix_sub(Matrixf* restrict out, const Matrixf* restrict a, const Matrixf* restrict b)
    __attribute__((nonnull(1, 2, 3)));

// Scalar multiplication: mat = mat * val
void matrix_scale(Matrixf* restrict mat, float val) __attribute__((nonnull(1)));

// Element wise division
void matrix_div(Matrixf* restrict mat, float val) __attribute__((nonnull(1)));


// MATRIX MULTIPLICATION
// ============================================================================

// Matrix multiplication: out = a × b
// (m×k) * (k×n) = (m×n)
// out must NOT alias a or b
// Uses blocked ikj multiplication for cache efficiency (good for small-medium matrices)
void matrix_xply(Matrixf* restrict out, const Matrixf* restrict a, const Matrixf* restrict b)
    __attribute__((nonnull(1, 2, 3)));

// Matrix multiplication variant 2: out = a × b
// Transposes b internally for better cache locality
// Takes more memory but can be faster for large matrices
// out must NOT alias a or b
void matrix_xply_2(Matrixf* restrict out, const Matrixf* restrict a, const Matrixf* restrict b)
    __attribute__((nonnull(1, 2, 3)));



// ADVANCED OPERATIONS
// ============================================================================

// Transpose: out = mat^T
// out must NOT alias mat
void matrix_T(Matrixf* restrict out, const Matrixf* restrict mat) __attribute__((nonnull(1, 2)));

// LU Decomposition: mat = L × U
// Decomposes square matrix into Lower and Upper triangular matrices
void matrix_LU_Decomp(Matrixf* restrict L, Matrixf* restrict U, const Matrixf* restrict mat)
    __attribute__((nonnull(1, 2, 3)));

// Calculate determinant using LU decomposition
float matrix_det(const Matrixf* mat) __attribute__((nonnull(1)));

// Matrix inverse: out = mat^(-1). Gauss-Jordan with partial pivoting, done in
// place in `out` (no allocation). Returns false if mat is singular; out is
// then unspecified. out and mat may not alias.
bool matrix_inv(Matrixf* restrict out, const Matrixf* restrict mat) __attribute__((nonnull(1, 2)));


// UTILITIES
// ============================================================================

// print the formatted, aligned matrix to stdout
void matrix_print(const Matrixf* mat) __attribute__((nonnull(1)));


#define MATRIX_TOTAL(mat)    ((u64)((mat)->n * (mat)->m))
#define IDX(mat, i, j)       (((i) * (mat)->n) + (j))
#define MATRIX_AT(mat, i, j) ((mat)->data[((i) * (mat)->n) + (j)])

#define ZEROS_1D(n)    ((float[n]){0})
#define ZEROS_2D(m, n) ((float[m][n]){0})



// CONSTRUCTION MACROS
// ============================================================================
// MATRIX(m, n)         libc-backed
// MATRIX_IN(A, m, n)   any allocator, e.g. MATRIX_IN(Arena_allocator(&arena), 3, 3)
#define MATRIX_IN(A, m, n) matrix_create((A), (m), (n))
#define MATRIX(m, n)       MATRIX_IN(WC_LIBC, (m), (n))


#endif // MATRIX_H

#ifdef WC_IMPLEMENTATION

#ifndef WC_WC_ALLOCATOR_IMPL
#define WC_WC_ALLOCATOR_IMPL
/* ===== wc_allocator.c ===== */
#line 1 "src/wc_allocator.c"

#include <stddef.h>



/* wc_libc: the only allocator with vt == NULL */

const wc_allocator wc_libc = {.vt = NULL, .ctx = NULL};


/* wc_borrowed: non-owning allocator */

static void* wc_borrowed_alloc(void* ctx, size_t size, size_t align)
{
    (void)ctx;
    (void)size;
    (void)align;
    return NULL;
}

static void wc_borrowed_free(void* ctx, void* p, size_t size, size_t align)
{
    (void)ctx;
    (void)p;
    (void)size;
    (void)align;
}

static const wc_alloc_vtable wc_borrowed_vt = {
    .alloc   = wc_borrowed_alloc,
    .realloc = NULL, // emulated: alloc fails, so growth fails and p stays valid
    .free    = wc_borrowed_free,
};

const wc_allocator wc_borrowed = {.vt = &wc_borrowed_vt, .ctx = NULL};

#endif /* WC_WC_ALLOCATOR_IMPL */

#ifndef WC_WC_ERRNO_IMPL
#define WC_WC_ERRNO_IMPL
/* ===== wc_errno.c ===== */
#line 1 "src/wc_errno.c"



#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>


/* One definition of the thread-local error variable.
 * Every translation unit that includes wc_error.h sees the extern declaration.
 * This file provides the actual storage.
 */
_Thread_local wc_err wc_errno = WC_OK;


/* Diagnostics reporters (common.h). Defined once, out of line and `cold`:
 * the compiler places them, and every branch that calls them, away from hot
 * code. Both write to stderr so diagnostics never mix into program output. */

// The installed fatal handler; NULL means the default (print + exit).
static wc_fatal_fn g_fatal_handler = NULL;

wc_fatal_fn wc_set_fatal_handler(wc_fatal_fn fn)
{
    wc_fatal_fn prev = g_fatal_handler;
    g_fatal_handler  = fn;
    return prev;
}

void wc_fatal_report(const char* file, int line, const char* func, const char* fmt, ...)
{
    fflush(stdout); // keep ordering with anything already printed

    char    msg[512];
    va_list args;
    va_start(args, fmt);
    vsnprintf(msg, sizeof(msg), fmt, args);
    va_end(args);

    if (g_fatal_handler) {
        g_fatal_handler(file, line, func, msg); // must not return
    } else {
        fprintf(stderr, WC_COLOR_RED "[FATAL] %s:%d:%s(): %s\n" WC_COLOR_RESET, file, line, func, msg);
    }
    exit(EXIT_FAILURE); // default, and the backstop for a handler that returns
}

void wc_warn_report(const char* file, int line, const char* func, const char* fmt, ...)
{
    fflush(stdout);
    fprintf(stderr, WC_COLOR_YELLOW "[WARN] %s:%d:%s(): ", file, line, func);
    va_list args;
    va_start(args, fmt);
    vfprintf(stderr, fmt, args);
    va_end(args);
    fprintf(stderr, "\n" WC_COLOR_RESET);
}

#endif /* WC_WC_ERRNO_IMPL */

#ifndef WC_MATRIX_IMPL
#define WC_MATRIX_IMPL
/* ===== matrix.c ===== */
#line 1 "src/matrix.c"



#include <stdalign.h>
#include <stdio.h>
#include <string.h>



#define MAT_BYTES(m, n) wc_mul(wc_mul((m), (n)), sizeof(float))

// Tile edge for the blocked transpose.
#ifndef WC_MAT_BLOCK
#define WC_MAT_BLOCK 16
#endif

// D4: a zeroed matrix is dead. Unconditional in every build.
#define MAT_LIVE(mat, fn) FATAL_IF((mat)->m == 0, fn " on zeroed/moved-from matrix")


Matrixf matrix_create(const wc_allocator* a, u64 m, u64 n)
{
    FATAL_IF(m == 0 || n == 0, "matrix_create: dims must be > 0 (got %llu x %llu)", (unsigned long long)m,
             (unsigned long long)n);

    float* data = wc_alloc(a, MAT_BYTES(m, n), alignof(float));
    FATAL_IF(!data, "matrix_create: data allocation failed");

    return (Matrixf){.data = data, .m = m, .n = n, .alloc = a};
}

Matrixf matrix_create_arr(const wc_allocator* a, u64 m, u64 n, const float* arr)
{
    Matrixf mat = matrix_create(a, m, n);
    memcpy(mat.data, arr, sizeof(float) * m * n);
    return mat;
}

Matrixf matrix_create_buf(u64 m, u64 n, float* data)
{
    FATAL_IF(m == 0 || n == 0, "matrix_create_buf: dims must be > 0");
    return (Matrixf){.data = data, .m = m, .n = n, .alloc = WC_BORROWED};
}

void matrix_destroy(Matrixf* mat)
{
    if (mat->data) {
        const wc_allocator* a = mat->alloc; // read before zeroing
        wc_free(a, mat->data, MAT_BYTES(mat->m, mat->n), alignof(float));
    }
    memset(mat, 0, sizeof(*mat));
}


void matrix_set_val_arr(Matrixf* mat, u64 count, const float* arr)
{
    MAT_LIVE(mat, "matrix_set_val_arr");
    WC_ASSERT(count == MATRIX_TOTAL(mat), "count doesn't match matrix size");

    memcpy(mat->data, arr, sizeof(float) * count);
}

void matrix_set_val_arr2(Matrixf* mat, u64 m, u64 n, const float** arr2)
{
    MAT_LIVE(mat, "matrix_set_val_arr2");
    WC_ASSERT(*arr2, "*arr is null");
    WC_ASSERT(m == mat->m && n == mat->n, "mat dimentions dont match passed arr2");

    u64 idx = 0;
    for (u64 i = 0; i < m; i++) {
        memcpy(mat->data + idx, arr2[i], sizeof(float) * n);
        idx += n;
    }
}

void matrix_set_elm(Matrixf* mat, float elm, u64 i, u64 j)
{
    MAT_LIVE(mat, "matrix_set_elm");
    WC_ASSERT(i < mat->m && j < mat->n, "index out of bounds");

    mat->data[IDX(mat, i, j)] = elm;
}

float matrix_get_elm(const Matrixf* mat, u64 i, u64 j)
{
    WC_ASSERT(i < mat->m && j < mat->n, "index out of bounds");

    return mat->data[IDX(mat, i, j)];
}

void matrix_add(Matrixf* restrict out, const Matrixf* restrict a, const Matrixf* restrict b)
{
    MAT_LIVE(out, "matrix_add");
    WC_ASSERT(a->m == b->m && a->n == b->n && a->m == out->m && a->n == out->n, "a, b, out mat dimentions dont match");

    u64 total = MATRIX_TOTAL(a);

    for (u64 i = 0; i < total; i++) {
        out->data[i] = a->data[i] + b->data[i];
    }
}


void matrix_sub(Matrixf* restrict out, const Matrixf* restrict a, const Matrixf* restrict b)
{
    MAT_LIVE(out, "matrix_sub");
    // FIXED: Added dimension check for 'out' matrix
    WC_ASSERT(a->m == b->m && a->n == b->n && a->m == out->m && a->n == out->n, "a, b, out mat dimentions dont match");

    u64 total = MATRIX_TOTAL(a);

    for (u64 i = 0; i < total; i++) {
        out->data[i] = a->data[i] - b->data[i];
    }
}

// ikj multiplication. (mxk) * (kxn) = (mxn)
// this is good for small to medium size matrices
void matrix_xply(Matrixf* restrict out, const Matrixf* restrict a, const Matrixf* restrict b)
{
    MAT_LIVE(out, "matrix_xply");
    WC_ASSERT(a->n == b->m, "incompatible matrix dimensions for multiplication");
    WC_ASSERT(out->m == a->m && out->n == b->n, "output matrix has wrong dimensions");

    u64 m = a->m; // rows of A
    u64 k = a->n; // cols of A = rows of B
    u64 n = b->n; // cols of B

    // Initialize output to zero
    memset(out->data, 0, sizeof(float) * m * n);

    // Block size for cache optimization
    const u64 BLOCK_SIZE = 16;

    // Blocked matrix multiplication (ikj order for cache efficiency)
    for (u64 i = 0; i < m; i += BLOCK_SIZE) {
        for (u64 k_outer = 0; k_outer < k; k_outer += BLOCK_SIZE) {
            for (u64 j = 0; j < n; j += BLOCK_SIZE) {
                // Block boundaries
                u64 i_max = (i + BLOCK_SIZE < m) ? i + BLOCK_SIZE : m;
                u64 k_max = (k_outer + BLOCK_SIZE < k) ? k_outer + BLOCK_SIZE : k;
                u64 j_max = (j + BLOCK_SIZE < n) ? j + BLOCK_SIZE : n;
                // Multiply this block
                for (u64 ii = i; ii < i_max; ii++) {
                    for (u64 kk = k_outer; kk < k_max; kk++) {

                        float a_val = a->data[IDX(a, ii, kk)];
                        for (u64 jj = j; jj < j_max; jj++) {
                            out->data[IDX(out, ii, jj)] += a_val * b->data[IDX(b, kk, jj)];
                        }
                    }
                }
            }
        }
    }
}


// this function transposes b for cache-friendly access
// takes more memory, good for large size matrices
void matrix_xply_2(Matrixf* restrict out, const Matrixf* restrict a, const Matrixf* restrict b)
{
    MAT_LIVE(out, "matrix_xply_2");
    WC_ASSERT(a->n == b->m, "incompatible matrix dimensions");
    WC_ASSERT(out->m == a->m && out->n == b->n, "output matrix has wrong dimensions");

    u64 m = a->m;
    u64 k = a->n;
    u64 n = b->n;

    // Transpose B for cache-friendly access
    float   data[n * k]; // random vals
    Matrixf b_T = matrix_create_buf(n, k, data);
    matrix_T(&b_T, b); // transpose sets all vals

    memset(out->data, 0, sizeof(float) * m * n);

    const u64 BLOCK_SIZE = 16;

    // Now both A and B^T are accessed row-wise
    for (u64 i = 0; i < m; i += BLOCK_SIZE) {
        for (u64 j = 0; j < n; j += BLOCK_SIZE) {
            u64 i_max = (i + BLOCK_SIZE < m) ? i + BLOCK_SIZE : m;
            u64 j_max = (j + BLOCK_SIZE < n) ? j + BLOCK_SIZE : n;

            for (u64 ii = i; ii < i_max; ii++) {
                for (u64 jj = j; jj < j_max; jj++) {

                    float sum = 0;
                    // Dot product of A[ii] and B_T[jj] (both row-wise)
                    for (u64 kk = 0; kk < k; kk++) {
                        sum += a->data[IDX(a, ii, kk)] *
                               // b_T->data[IDX(b_T, jj, kk)];
                               b_T.data[IDX(&b_T, jj, kk)];
                    }
                    out->data[IDX(out, ii, jj)] = sum;
                }
            }
        }
    }
}

/*
Doolittle algorithm computes U's i-th row, then L's i-th column, alternating.
For each element, you subtract the dot product of already-computed L and U values.
*/
void matrix_LU_Decomp(Matrixf* restrict L, Matrixf* restrict U, const Matrixf* restrict mat)
{
    MAT_LIVE(L, "matrix_LU_Decomp");
    MAT_LIVE(U, "matrix_LU_Decomp");
    WC_ASSERT(mat->n == mat->m, "mat is not a square matrix");
    WC_ASSERT(L->n == mat->n && L->m == mat->m, "L dimensions don't match");
    WC_ASSERT(U->n == mat->n && U->m == mat->m, "U dimensions don't match");

    const u64 n = mat->n;

    // 0 init matrices
    memset(L->data, 0, sizeof(float) * n * n);
    memset(U->data, 0, sizeof(float) * n * n);
    // L main diagonal is 1
    for (u64 i = 0; i < n; i++) {
        L->data[IDX(L, i, i)] = 1;
    }


    // Build U and L row by row
    for (u64 i = 0; i < n; i++) {
        // Upper triangular matrix U (row i, columns from i to n-1)
        for (u64 k = i; k < n; k++) {
            float sum = 0;
            for (u64 j = 0; j < i; j++) {
                sum += L->data[IDX(L, i, j)] * U->data[IDX(U, j, k)];
            }
            U->data[IDX(U, i, k)] = MATRIX_AT(mat, i, k) - sum;
        }

        // Lower triangular matrix L (column i, rows from i+1 to n-1)
        for (u64 k = i + 1; k < n; k++) {
            float sum = 0;
            for (u64 j = 0; j < i; j++) {
                sum += L->data[IDX(L, k, j)] * U->data[IDX(U, j, i)];
            }

            // Check for zero diagonal in U (would cause division by zero)
            if (U->data[IDX(U, i, i)] == 0) {
                WC_ASSERT(0, "Matrix is singular - LU decomposition failed");
            }

            L->data[IDX(L, k, i)] = (MATRIX_AT(mat, k, i) - sum) / U->data[IDX(U, i, i)];
        }
    }
}

/*
    det of triangular mat is product of main diagonal
    so det of a mat that is decomposed with LU method becomes
    product of elements on the diagonal of L and U
    det(A) = det(L) * det(U)
    
    Since L has 1s on diagonal: det(L) = 1
    So: det(A) = det(U) = product of U's diagonal elements
    
    LU Decomposition is when we make 2 triangular matrices from one,
    which when multiplied give original matrix: A = L * U
*/
float matrix_det(const Matrixf* mat)
{
    WC_ASSERT(mat->m == mat->n, "only square matrices have determinant");


    u64 n = mat->n;

    float   Ldata[n * n]; // random vals
    float   Udata[n * n];
    Matrixf L = matrix_create_buf(n, n, Ldata);
    Matrixf U = matrix_create_buf(n, n, Udata);

    // Perform LU decomposition
    matrix_LU_Decomp(&L, &U, mat); // L and U set to zero

    // Calculate determinant as product of U's diagonal
    float det = 1;
    for (u64 i = 0; i < n; i++) {
        det *= U.data[IDX(&U, i, i)];
    }

    return det;
}


/*
    In-place Gauss-Jordan with partial pivoting.
    For each column k: pick the row with the largest |a[i][k]| at or below k,
    swap it up, scale the pivot row so the pivot becomes 1 (storing 1/pivot in
    its place), and eliminate column k from every other row. Each row swap is
    recorded; undoing them as COLUMN swaps in reverse order leaves the inverse.
*/
bool matrix_inv(Matrixf* restrict out, const Matrixf* restrict mat)
{
    MAT_LIVE(out, "matrix_inv");
    WC_ASSERT(mat->m == mat->n, "only square matrices have an inverse");
    WC_ASSERT(out->m == mat->m && out->n == mat->n, "out dimensions don't match");

    const u64 n = mat->n;
    float*    a = out->data;
    memcpy(a, mat->data, sizeof(float) * n * n);

    u64 piv[n]; // row swapped into position k

    for (u64 k = 0; k < n; k++) {
        u64   p    = k;
        float best = a[(k * n) + k] < 0 ? -a[(k * n) + k] : a[(k * n) + k];
        for (u64 i = k + 1; i < n; i++) {
            float v = a[(i * n) + k] < 0 ? -a[(i * n) + k] : a[(i * n) + k];
            if (v > best) {
                best = v;
                p    = i;
            }
        }
        if (best == 0.0F) {
            return false; // singular
        }

        piv[k] = p;
        if (p != k) {
            for (u64 j = 0; j < n; j++) {
                float t          = a[(k * n) + j];
                a[(k * n) + j]   = a[(p * n) + j];
                a[(p * n) + j]   = t;
            }
        }

        float inv_p    = 1.0F / a[(k * n) + k];
        a[(k * n) + k] = 1.0F;
        for (u64 j = 0; j < n; j++) {
            a[(k * n) + j] *= inv_p;
        }

        for (u64 i = 0; i < n; i++) {
            if (i == k) {
                continue;
            }
            float f        = a[(i * n) + k];
            a[(i * n) + k] = 0.0F;
            if (f != 0.0F) {
                for (u64 j = 0; j < n; j++) {
                    a[(i * n) + j] -= f * a[(k * n) + j];
                }
            }
        }
    }

    // undo the row swaps as column swaps, last first
    for (u64 k = n; k-- > 0;) {
        if (piv[k] != k) {
            for (u64 i = 0; i < n; i++) {
                float t                = a[(i * n) + k];
                a[(i * n) + k]         = a[(i * n) + piv[k]];
                a[(i * n) + piv[k]]    = t;
            }
        }
    }
    return true;
}


void matrix_T(Matrixf* restrict out, const Matrixf* restrict mat)
{
    MAT_LIVE(out, "matrix_T");
    WC_ASSERT(mat->m == out->n && mat->n == out->m, "incompatible matrix dimensions");

    // Block size for cache optimization (tune with -DWC_MAT_BLOCK=n)
    const u64 BLOCK_SIZE = WC_MAT_BLOCK;

    // Blocked transpose: process matrix in BLOCK_SIZE x BLOCK_SIZE tiles
    for (u64 i = 0; i < mat->m; i += BLOCK_SIZE) {
        for (u64 j = 0; j < mat->n; j += BLOCK_SIZE) {

            // Calculate block boundaries
            u64 i_max = (i + BLOCK_SIZE < mat->m) ? i + BLOCK_SIZE : mat->m;
            u64 j_max = (j + BLOCK_SIZE < mat->n) ? j + BLOCK_SIZE : mat->n;

            // Transpose the block
            for (u64 ii = i; ii < i_max; ii++) {
                for (u64 jj = j; jj < j_max; jj++) {
                    // mat[ii][jj] -> out[jj][ii]
                    out->data[IDX(out, jj, ii)] = mat->data[IDX(mat, ii, jj)];
                }
            }
        }
    }
}

void matrix_scale(Matrixf* restrict mat, float val)
{
    MAT_LIVE(mat, "matrix_scale");
    u64 total = MATRIX_TOTAL(mat);
    for (u64 i = 0; i < total; i++) {
        mat->data[i] *= val;
    }
}


void matrix_div(Matrixf* restrict mat, float val)
{
    MAT_LIVE(mat, "matrix_div");
    WC_ASSERT(val != 0, "division by zero!");

    u64 total = MATRIX_TOTAL(mat);
    for (u64 i = 0; i < total; i++) {
        mat->data[i] /= val;
    }
}

Matrixf matrix_copy(const wc_allocator* a, const Matrixf* src)
{
    MAT_LIVE(src, "matrix_copy");
    return matrix_create_arr(a, src->m, src->n, src->data);
}

void matrix_move(Matrixf* dest, Matrixf* src)
{
    if (dest == src) {
        return;
    }
    memcpy(dest, src, sizeof(Matrixf));
    memset(src, 0, sizeof(Matrixf));
}

void matrix_print(const Matrixf* mat)
{
    u64 total = mat->m * mat->n;

    // Single linear loop O(n)
    for (u64 i = 0; i < total; i++) {
        // Print row separator
        if (i % mat->n == 0) { // divide by columns to detect new row
            if (i > 0) {
                putchar('|');
            } // Close previous row
            putchar('\n');
            putchar('|');
            putchar(' ');
        }

        // Print element
        printf("%f ", mat->data[i]);
    }

    // Close last row
    putchar('|');
    putchar('\n');
}

#undef MAT_BYTES
#undef WC_MAT_BLOCK
#undef MAT_LIVE
#endif /* WC_MATRIX_IMPL */

#endif /* WC_IMPLEMENTATION */

#endif /* WC_MATRIX_SINGLE_H */
