/* wc_helpers_single.h: generated by tools/make_single_header.py. Do not edit.
 * Contains: wc_allocator, common, wc_errno, gen_vector, wc_string, wc_helpers
 *
 * In exactly one .c file:
 *     #define WC_IMPLEMENTATION
 *     #include "wc_helpers_single.h"
 */
#ifndef WC_WC_HELPERS_SINGLE_H
#define WC_WC_HELPERS_SINGLE_H

/* ===== wc_allocator.h ===== */
#line 1 "include/wc_allocator.h"
#ifndef WC_ALLOCATOR_H
#define WC_ALLOCATOR_H

#include <assert.h>
#include <stdalign.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>


#define WC_MAX_ALIGN alignof(max_align_t)

/* libc fallbacks */

static inline void* wc_libc_alloc(size_t n, size_t align)
{
    if (align <= WC_MAX_ALIGN) {
        return malloc(n);
    }

    size_t rounded = (n + align - 1) & ~(align - 1); // aligned_alloc: size % align == 0
    if (rounded < n) {
        return NULL; // overflow
    }
#ifdef _MSC_VER
    return _aligned_malloc(rounded, align);
#else
    return aligned_alloc(align, rounded);
#endif
}

static inline void wc_libc_free(void* p, size_t align)
{
#ifdef _MSC_VER
    if (align > WC_MAX_ALIGN) {
        _aligned_free(p); // MSVC can't free() these
        return;
    }
#endif
    (void)align;
    free(p); // POSIX/glibc: fine for both
}

static inline void* wc_libc_realloc(void* p, size_t old_n, size_t n, size_t align)
{
    if (align <= WC_MAX_ALIGN) {
        return realloc(p, n);
    }

    // libc realloc doesn't preserve alignment above max_align_t: alloc, copy, free
    void* q = wc_libc_alloc(n, align);
    if (!q) {
        return NULL; // p left untouched
    }
    memcpy(q, p, old_n < n ? old_n : n);
    wc_libc_free(p, align);
    return q;
}



/*
 * ALLOCATOR API
 *
 * No global allocator exists: every data structure receives its allocator at
 * construction, stores it, and uses it for every allocation.
 *
 * An allocator is a (vtable, ctx) pair. It is passed and stored as `const wc_allocator*`
 *   - the pointer is never NULL; libc is WC_LIBC, nothing else.
 *   - the pointed-to allocator must outlive every container that stores it.
 *     WC_LIBC and WC_BORROWED are static; Arena, ChainArena and wc_test_alloc
 *     embed their own allocator, so the arena's lifetime covers it
 *   - `const`: a call never changes the (vt, ctx) pair; ctx is what mutates
 *
 * Contract (the wc_* wrappers enforce it, backends may rely on it):
 *   - callbacks are never called with p == NULL or size == 0
 *   - `align` is a power of two >= 1 and is an ADDRESS alignment
 *   - `free` / `realloc` receive the exact size and align of the block's last
 *     alloc/realloc (wc_test_alloc verifies this; arenas ignore it)
 *   - `realloc` failure returns NULL and leaves p valid
 *   - missing `realloc` is emulated (alloc + copy + free); missing `free` is a no-op
 *   - wc_alloc(a, 0, ..) returns NULL without calling the backend
 *   - wc_realloc(a, NULL, 0, n, ..) == wc_alloc(a, n, ..)
 *   - wc_realloc(a, p, old, 0, ..) frees p and returns NULL
 *
*/
typedef struct {
    void* (*alloc)(void* ctx, size_t size, size_t align);
    void* (*realloc)(void* ctx, void* p, size_t old_size, size_t new_size, size_t align); // may be NULL
    void (*free)(void* ctx, void* p, size_t size, size_t align);                          // may be NULL
} wc_alloc_vtable;

typedef struct {
    const wc_alloc_vtable* vt;  // NULL => libc (only ever true for wc_libc)
    void*                  ctx; // Arena*, ChainArena*, test allocator, ...
} wc_allocator;

_Static_assert(sizeof(wc_allocator) == 16, "wc_allocator must stay 16 bytes");

// The libc allocator. Defined once in wc_allocator.c.
extern const wc_allocator wc_libc;
#define WC_LIBC (&wc_libc)

// Non-owning allocator: alloc -> NULL, free -> no-op. A container built on it
// wraps caller memory, cannot grow, and frees nothing on destroy.
extern const wc_allocator wc_borrowed;
#define WC_BORROWED (&wc_borrowed)

static inline __attribute__((nonnull(1))) int wc_is_libc(const wc_allocator* a)
{
    return a->vt == NULL;
}

// Same backend and same context: memory from one may be freed through the other.
static inline __attribute__((nonnull(1, 2))) int wc_same(const wc_allocator* a, const wc_allocator* b)
{
    return a == b || (a->vt == b->vt && a->ctx == b->ctx);
}

#define WC_ALLOC_ASSERT_ALIGN(align) \
    assert((align) != 0 && ((align) & ((align) - 1)) == 0 && "align must be a power of two >= 1")

static inline __attribute__((nonnull(1))) void* wc_alloc(const wc_allocator* a, size_t n, size_t align)
{
    WC_ALLOC_ASSERT_ALIGN(align);
    if (n == 0 || n > (size_t)PTRDIFF_MAX) { // > PTRDIFF_MAX: overflowed size (see wc_mul)
        return NULL;
    }
    return a->vt ? a->vt->alloc(a->ctx, n, align) : wc_libc_alloc(n, align);
}

static inline __attribute__((nonnull(1))) void wc_free(const wc_allocator* a, void* p, size_t n, size_t align)
{
    WC_ALLOC_ASSERT_ALIGN(align);
    if (!p) {
        return;
    }
    if (!a->vt) {
        wc_libc_free(p, align);
        return;
    }
    if (a->vt->free) {
        a->vt->free(a->ctx, p, n, align);
    }
}

static inline __attribute__((nonnull(1))) void* wc_realloc(const wc_allocator* a, void* p, size_t old_n, size_t n,
                                                           size_t align)
{
    WC_ALLOC_ASSERT_ALIGN(align);
    if (!p) {
        return wc_alloc(a, n, align);
    }
    if (n == 0) {
        wc_free(a, p, old_n, align);
        return NULL;
    }
    if (n > (size_t)PTRDIFF_MAX) {
        return NULL; // overflowed size: fail, p stays valid
    }
    if (!a->vt) {
        return wc_libc_realloc(p, old_n, n, align);
    }
    if (a->vt->realloc) {
        return a->vt->realloc(a->ctx, p, old_n, n, align);
    }

    // backend without realloc: emulate
    void* q = a->vt->alloc(a->ctx, n, align);
    if (!q) {
        return NULL; // p left untouched
    }
    memcpy(q, p, old_n < n ? old_n : n);
    wc_free(a, p, old_n, align);
    return q;
}

// count * size, saturating to SIZE_MAX on overflow. SIZE_MAX can never be
// satisfied, so an overflowing request fails in the backend instead of wrapping
// to a small size. (Returning 0 would be wrong: realloc to 0 means free.)
static inline size_t wc_mul(size_t count, size_t size)
{
    size_t r;
    return (int)__builtin_mul_overflow(count, size, &r) ? SIZE_MAX : r;
}

// Smallest safe alignment for elements of `elm_size` bytes: the
// largest power of two dividing elm_size, capped at WC_MAX_ALIGN. Valid because
// sizeof(T) is always a multiple of alignof(T).
static inline size_t wc_align_for_size(size_t elm_size)
{
    if (elm_size == 0) {
        return 1;
    }
    size_t lowbit = elm_size & (~elm_size + 1);
    return lowbit < WC_MAX_ALIGN ? lowbit : WC_MAX_ALIGN;
}


/* typed helpers (allocator first)
 * Free takes the POINTER, not a type: size and align come from *p, so a wrong
 * type can't be passed*/

#define WC_NEW(a, T)      ((T*)wc_alloc((a), sizeof(T), alignof(T)))
#define WC_NEW_N(a, T, n) ((T*)wc_alloc((a), wc_mul((n), sizeof(T)), alignof(T)))
#define WC_REALLOC_N(a, p, old_n, n)                                                               \
    ((__typeof__(p))wc_realloc((a), (p), wc_mul((old_n), sizeof(*(p))), wc_mul((n), sizeof(*(p))), \
                               alignof(__typeof__(*(p)))))
#define WC_FREE(a, p)      (wc_free((a), (p), sizeof(*(p)), alignof(__typeof__(*(p)))))
#define WC_FREE_N(a, p, n) (wc_free((a), (p), wc_mul((n), sizeof(*(p))), alignof(__typeof__(*(p)))))


#endif // WC_ALLOCATOR_H

/* ===== common.h ===== */
#line 1 "include/common.h"
#ifndef COMMON_H
#define COMMON_H



/*
 * WCtoolkit
 * Copyright (c) 2026 Wasi Ullah (PAKIWASI)
 * Licensed under the MIT License. See LICENSE file for details.
 */



// LOGGING/ERRORS

#include <stdalign.h>
#include <stdarg.h>
#include <stdio.h>
// #include <stdlib.h>

// ANSI Color Codes
#define WC_COLOR_RESET  "\033[0m"
#define WC_COLOR_RED    "\033[1;31m"
#define WC_COLOR_YELLOW "\033[1;33m"
#define WC_COLOR_GREEN  "\033[1;32m"
#define WC_COLOR_BLUE   "\033[1;34m"
#define WC_COLOR_CYAN   "\033[1;36m"



/*
 * DIAGNOSTICS
 *
 *   SURVIVES EVERY BUILD (Debug and Release)
 *     FATAL(fmt, ...)                 abort with a message
 *
 *     FATAL_IF(cond, fmt, ...)        abort if cond is TRUE. Absolute failures
 *                                     only: allocation failed, mutation of a
 *                                     zeroed (moved-from/destroyed) container.
 *
 *     WARN(fmt, ...)                  print a warning to stderr, continue
 *
 *     WARN_IF(cond, fmt, ...)         warn if cond is TRUE, continue
 *
 *     WARN_IF_RET(cond, ret, fmt, ...) warn and `return ret` if cond is TRUE
 *                                     (GNU statement expression can return)
 *
 *     LOG(fmt, ...)                   print to stderr
 *
 *     LOG_IF(cond, fmt, ...)          log if cond is TRUE
 *
 *   STRIPPED UNDER NDEBUG (Release)
 *
 *     WC_ASSERT(cond, fmt, ...)       abort if cond is FALSE. cond is the
 *                                     INVARIANT (`i < size`), not the failure.
 *                                     For programmer errors: bounds, API misuse.
 *                                     Release: cond is NOT evaluated (no side
 *                                     effects run) but still type-checked.
 *
 * The rule: if continuing past the failure would corrupt memory even in a
 * correct program (an allocator returned NULL), use FATAL_IF. If the failure
 * means the CALLER has a bug, use WC_ASSERT
 *
 * Branch prediction: failure paths are WC_UNLIKELY, and the reporters are
 * `cold, noinline` functions defined once in wc_errno.c. The compiler moves
 * every failure branch (argument setup + call) out of the hot path into
 * .text.unlikely, so a check costs one compare and one not-taken branch.
*/

#define WC_LIKELY(x)   __builtin_expect(!!(x), 1)
#define WC_UNLIKELY(x) __builtin_expect(!!(x), 0)

__attribute__((cold, noinline, noreturn, format(printf, 4, 5))) void
wc_fatal_report(const char* file, int line, const char* func, const char* fmt, ...);

/* Fatal handler. Every FATAL / FATAL_IF formats its message and calls the
 * installed handler. The handler must not return: abort, exit, or longjmp out
 * (tests can verify that something FATALs). If it does return, the program
 * exits. NULL restores the default (print to stderr, exit(EXIT_FAILURE)).
 * Returns the previous handler. Set it once at startup: it is not thread-local. */
typedef void (*wc_fatal_fn)(const char* file, int line, const char* func, const char* msg);
wc_fatal_fn wc_set_fatal_handler(wc_fatal_fn fn);

__attribute__((cold, noinline, format(printf, 4, 5))) void wc_warn_report(const char* file, int line, const char* func,
                                                                          const char* fmt, ...);


/* SURVIVES EVERY BUILD */

#define FATAL(fmt, ...) wc_fatal_report(__FILE__, __LINE__, __func__, fmt, ##__VA_ARGS__)

#define FATAL_IF(cond, fmt, ...) ((void)(WC_UNLIKELY(cond) && (FATAL("(%s): " fmt, #cond, ##__VA_ARGS__), 0)))

#define WARN(fmt, ...) wc_warn_report(__FILE__, __LINE__, __func__, fmt, ##__VA_ARGS__)

#define WARN_IF(cond, fmt, ...) ((void)(WC_UNLIKELY(cond) && (WARN("(%s): " fmt, #cond, ##__VA_ARGS__), 0)))

#define WARN_IF_RET(cond, ret, fmt, ...)              \
    ({                                                \
        if (WC_UNLIKELY(cond)) {                      \
            WARN("(%s): " fmt, #cond, ##__VA_ARGS__); \
            return ret;                               \
        }                                             \
        (void)0;                                      \
    })

// stderr, like WARN/FATAL: diagnostics never mix into program output.
#define LOG(fmt, ...) \
    ((void)fprintf(stderr, WC_COLOR_CYAN "[LOG] %s(): " fmt "\n" WC_COLOR_RESET, __func__, ##__VA_ARGS__))

#define LOG_IF(cond, fmt, ...) ((void)((cond) && (LOG(fmt, ##__VA_ARGS__), 0)))


/* STRIPPED UNDER NDEBUG */

#ifdef NDEBUG
// Not evaluated (sizeof of an int expression), still compiled: a stale field
// name or type error inside an assert breaks the Release build too, and
// variables used only in asserts don't trigger unused warnings.
#define WC_ASSERT(cond, fmt, ...) ((void)sizeof(!(cond)))
#else
#define WC_ASSERT(cond, fmt, ...) \
    ((void)(WC_LIKELY(cond) || (FATAL("assertion (%s) failed: " fmt, #cond, ##__VA_ARGS__), 0)))
#endif


// Token pasting that expands its arguments first. `a##b` pastes BEFORE expansion,
// so WC_CAT_(x, __LINE__) gives `x__LINE__`; the extra level expands __LINE__ to
// 42 first and then pastes, giving `x42`. Used for __COUNTER__/__LINE__ names.
#define WC_CAT_(a, b) a##b
#define WC_CAT(a, b)  WC_CAT_(a, b)


// TYPES

#include <stdbool.h>
#include <stdint.h>

typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;

typedef int8_t  i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;

// we are using unsigned indices/sizes
#define WC_NOT_FOUND ((u64) - 1)


// GENERIC FUNCTIONS


/* ELEMENT OPS
 *
 * Memory rule B5: every element is TRIVIALLY RELOCATABLE. A container may move
 * an element to another address with a raw memcpy (growth, insert/remove shifts,
 * hash table shuffles, queue compaction, taking an element out) and never asks
 * the element first. A type that holds a pointer to itself, or that something
 * outside points into, cannot be stored by value: store it by pointer.
 *
 */

// Deep-copy `src` INTO `dest`, allocating any owned resources from `dst`.
// `dest` is uninitialised raw slot memory: never read or free it (B3).
// Called ONLY when both sides keep the value (B8).
typedef void (*wc_copy_fn)(const wc_allocator* dst, void* dest, const void* src);
// Release owned resources of the element (not the slot). Elements that own
// memory store their own allocator, so no allocator argument is needed (B2).
typedef void (*wc_delete_fn)(void* elm);
typedef void (*wc_print_fn)(const void* elm);
typedef int (*wc_compare_fn)(const void* a, const void* b, u64 size);


// vtable: one instance shared across all objects of the same type.
// Pass NULL for any callback not needed (no copy_fn: copies are memcpy;
// no del_fn: nothing is freed per element). For plain data pass NULL ops.
typedef struct {
    wc_copy_fn   copy_fn; // Deep copy function for owned resources (or NULL)
    wc_delete_fn del_fn;  // Cleanup function for owned resources (or NULL)
} wc_container_ops;


// Heap-box a value-returning constructor through allocator A:
//   GenVec* v = WC_BOX_IN(A, GenVec, GenVec_create, 8, sizeof(int), NULL);
// Invariant: the shell comes from the same allocator the child stores, so a
// by-pointer delete can free the shell with the child's own allocator.
#define WC_BOX_IN(A, T, init_fn, ...)                              \
    ({                                                             \
        T* _wbx_p = wc_alloc(A, sizeof(T), alignof(T));            \
        FATAL_IF(!_wbx_p, "WC_BOX_IN(" #T "): allocation failed"); \
        *_wbx_p = init_fn(A, __VA_ARGS__);                         \
        _wbx_p;                                                    \
    })


// COMMON SIZES

#define KB (1 << 10)
#define MB (1 << 20)

#define nKB(n) ((u64)((n) * KB))
#define nMB(n) ((u64)((n) * MB))


// RAW BYTES TO HEX

static inline void print_hex(const u8* ptr, u64 size, u32 bytes_per_line)
{
    if (ptr == NULL || size == 0 || bytes_per_line == 0) {
        return;
    }

    // hex rep 0-15
    const char* hex = "0123456789ABCDEF";

    for (u64 i = 0; i < size; i++) {
        u8 val1 = ptr[i] >> 4;   // get upper 4 bits as num b/w 0-15
        u8 val2 = ptr[i] & 0x0F; // get lower 4 bits as num b/w 0-15

        printf("%c%c", hex[val1], hex[val2]);

        // Add space or newline appropriately
        if ((i + 1) % bytes_per_line == 0) {
            printf("\n");
        } else if (i < size - 1) {
            printf(" ");
        }
    }

    // Add final newline if we didn't just print one
    if (size % bytes_per_line != 0) {
        printf("\n");
    }
}


// TEST HELPERS

// Generic print functions for primitive types
static inline void wc_print_int(const void* elm)
{
    printf("%d ", *(int*)elm);
}
static inline void wc_print_u32(const void* elm)
{
    printf("%u ", *(u32*)elm);
}
static inline void wc_print_u64(const void* elm)
{
    printf("%llu ", (unsigned long long)*(u64*)elm);
}
static inline void wc_print_float(const void* elm)
{
    printf("%.2f ", (double)*(float*)elm);
}
static inline void wc_print_char(const void* elm)
{
    printf("%c ", *(char*)elm);
}
static inline void wc_print_cstr(const void* elm)
{
    printf("%s ", (const char*)elm);
}


#endif // COMMON_H

/* ===== wc_errno.h ===== */
#line 1 "include/wc_errno.h"
#ifndef WC_ERRNO_H
#define WC_ERRNO_H

#include <stdio.h>


/* wc_errno.h — Error reporting for WCtoolkit
 *
 * Three tiers:
 *
 *   FATAL_IF     Resource failures and dead state, in EVERY build: an
 *                allocator returned NULL, or a zeroed (moved-from/destroyed)
 *                container was mutated. Continuing would corrupt memory.
 *
 *   WC_ASSERT    Programmer errors: null pointer, out of bounds, size 0.
 *                Takes the INVARIANT (`i < size`). Crashes with a message in
 *                debug builds; compiled out under NDEBUG (condition not
 *                evaluated). Never use it for allocation failure.
 *
 *   (WARN_IF / LOG_IF report and continue, in every build. Full list and
 *    the release/debug split: the DIAGNOSTICS block in common.h.)
 *
 *   wc_errno     Expected conditions: pop on empty, Arena full.
 *                Function returns NULL / 0 / void. wc_errno says why.
 *                Ignore it if you don't care. Check it if you do.
 *
 *
 * USAGE
 * -----
 *   // Check a single call:
 *   wc_errno = WC_OK;
 *   void* p = Arena_alloc(Arena, size);
 *   if (!p && wc_errno == WC_ERR_FULL) { ... }
 *
 *   // Check a batch — wc_errno stays set if any call failed:
 *   wc_errno = WC_OK;
 *   float* a = Arena_alloc(Arena, 256);
 *   float* b = Arena_alloc(Arena, 256);
 *   if (wc_errno) { wc_perror("alloc"); }
 *
 *
 * RULES
 * -----
 *   1. Successful calls do NOT clear wc_errno — clear it yourself.
 *   2. Check the return value first. wc_errno tells you WHY, not WHETHER.
 *   3. wc_errno is thread-local. Each thread has its own copy.
 *
 *
 * WHAT SETS wc_errno
 * ------------------
 *   Arena_alloc, Arena_alloc_aligned      WC_ERR_FULL    Arena exhausted
 *   GenVec_pop, GenVec_front, GenVec_back WC_ERR_EMPTY   vec is empty
 *   Queue_pop, Queue_peek, Queue_peek_ptr WC_ERR_EMPTY   Queue is empty
 *   Stack_pop, Stack_peek                 WC_ERR_EMPTY   Stack is empty
 */


typedef enum {
    WC_OK = 0,
    WC_ERR_FULL,       // Arena exhausted / container at capacity
    WC_ERR_EMPTY,      // pop or peek on empty container
    WC_ERR_INVALID_OP, // call to a function with preconditions not met
} wc_err;

static inline const char* wc_strerror(wc_err e)
{
    switch (e) {
    case WC_OK:
        return "ok";
    case WC_ERR_FULL:
        return "full";
    case WC_ERR_EMPTY:
        return "empty";
    case WC_ERR_INVALID_OP:
        return "invalid op";
    default:
        return "unknown";
    }
}

/* Defined in wc_errno.c:
 *   _Thread_local wc_err wc_errno = WC_OK;
 */
extern _Thread_local wc_err wc_errno;

/* Print last error — same pattern as perror(3).
 *   wc_perror("Arena_alloc");  ->  "Arena_alloc: full"
 */
static inline void wc_perror(const char* prefix)
{
    if (prefix && prefix[0]) {
        fprintf(stderr, "%s: %s\n", prefix, wc_strerror(wc_errno));
    } else {
        fprintf(stderr, "%s\n", wc_strerror(wc_errno));
    }
}


/* Internal macros (library use only)
 * ------------------------------------
 * WC_SET_RET — for expected-condition sites (use WARN_IF_RET to also print).
 * Sets wc_errno silently and returns. No print.
 *
 *   WC_SET_RET(WC_ERR_EMPTY, vec->size == 0, );     void return
 *   WC_SET_RET(WC_ERR_FULL,  cond,           NULL); pointer return
 */
#define WC_SET_RET(err_code, cond, ret) \
    ({                                  \
        if (WC_UNLIKELY(cond)) {        \
            wc_errno = (err_code);      \
            return ret;                 \
        }                               \
    })

/* WC_PROPAGATE_RET — exit immediately if a callee already set wc_errno.
 *
 *   some_internal_fn(vec);
 *   WC_PROPAGATE_RET( );   // exits if some_internal_fn set wc_errno
 */
#define WC_PROPAGATE_RET(ret)                 \
    ({                                        \
        if (WC_UNLIKELY(wc_errno != WC_OK)) { \
            return ret;                       \
        }                                     \
    })

#endif // WC_ERRNO_H

/* ===== gen_vector.h ===== */
#line 1 "include/gen_vector.h"
#ifndef GEN_VECTOR_H
#define GEN_VECTOR_H




/*          TLDR
 * GenVec is a value-based generic vector.
 * Elements are stored inline and managed via user-supplied
 * copy/move/destructor callbacks (a shared wc_container_ops vtable).
 *
 * The vector is a VALUE: create returns it, destroy never frees the struct.
 * It stores the allocator it was created with and uses it for every
 * allocation, reallocation and free
 *
 *   GenVec v = GenVec_create(WC_LIBC, 8, sizeof(int), NULL);        // libc
 *   GenVec w = GenVec_create(Arena_allocator(&arena), 8, sizeof(int), NULL);
 *   GenVec_push(&v, &x);
 *   GenVec_destroy(&v);                                             // v is zeroed
 *
 * Moves take a pointer to the source ELEMENT and leave it zeroed:
 *   String s = ...;  GenVec_push_move(&v, &s);                 // s is zeroed
 *
 * Taking an element out (pop, remove, swap_pop) MOVES it into `out`: no copy,
 * no allocation, and the vector forgets the slot (memory rule B7). The value
 * keeps the vector's allocator (B9). With out == NULL the element is deleted.
 *
 * Input aliasing (D4): the element passed to push/insert/replace must not live
 * inside this vector's own buffer (growth would free it before the copy).
 * Debug builds check this.
 *
 * Zero state: a zeroed GenVec (moved-from or destroyed) may only be destroyed
 * or re-created. Growing or inserting into it is a FATAL in every build
 */


// GenVec growth settings

#ifndef GENVEC_MIN_CAPACITY
#define GENVEC_MIN_CAPACITY 8
#endif

// TODO: genvec growth as a compile time option?


// generic vector container
typedef struct {
    u8* data; // pointer to generic data

    // Pointer to shared type-ops vtable (or NULL for POD types)
    const wc_container_ops* ops;

    const wc_allocator* alloc; // every data allocation goes through this

    u64 size;     // Number of elements currently in vector
    u64 capacity; // Total allocated capacity (in elements)


    u32 data_size; // Size of each element in bytes (0 = zero state)

    // Cache: 1 if ops==NULL (POD fast path)
    bool is_pod;
} GenVec;



// 8 8 8 8 8 4 1 '3'  = 48 bytes
_Static_assert(sizeof(GenVec) == 48, "GenVec layout drifted from expected 48 bytes");


// Convenience: access ops callbacks safely
#define VEC_COPY_FN(vec) ((vec)->ops ? (vec)->ops->copy_fn : NULL)
#define VEC_DEL_FN(vec)  ((vec)->ops ? (vec)->ops->del_fn : NULL)



// Memory Management
// ===========================

// Vector with capacity n, storage from `alloc`.
// ops: pointer to a shared wc_container_ops vtable, or NULL for POD types.
GenVec GenVec_create(const wc_allocator* alloc, u64 n, u32 data_size, const wc_container_ops* ops)
    __attribute__((nonnull(1), warn_unused_result));

// Vector of size n with every element a copy of val.
GenVec GenVec_create_val(const wc_allocator* alloc, u64 n, const void* val, u32 data_size, const wc_container_ops* ops)
    __attribute__((nonnull(1, 3), warn_unused_result));

// Vector over caller-owned storage of n elements (size 0, capacity n).
// Uses WC_BORROWED: it can never grow (growth is a FATAL) and destroy frees nothing.
GenVec GenVec_create_buf(void* buf, u64 n, u32 data_size, const wc_container_ops* ops)
    __attribute__((nonnull(1), warn_unused_result));

// Delete every element, free the storage through the stored allocator and
// zero the struct. Never frees the struct itself. Safe on a zeroed vector.
void GenVec_destroy(GenVec* vec) __attribute__((nonnull(1)));

// Remove all elements (calls del_fn on each), keep capacity.
void GenVec_clear(GenVec* vec) __attribute__((nonnull(1)));

// Remove all elements and free the storage; capacity 0, allocator kept.
void GenVec_reset(GenVec* vec) __attribute__((nonnull(1)));

// Ensure vector has at least new_capacity space (never shrinks).
void GenVec_reserve(GenVec* vec, u64 new_capacity) __attribute__((nonnull(1)));

// Grow to new_capacity and fill new slots with val.
void GenVec_reserve_val(GenVec* vec, u64 new_capacity, const void* val) __attribute__((nonnull(1, 3)));

// Shrink vector to its size (reallocates).
void GenVec_shrink_to_fit(GenVec* vec) __attribute__((nonnull(1)));



// Operations
// ===========================

// Append element to end (makes deep copy if copy_fn provided).
void GenVec_push(GenVec* vec, const void* data) __attribute__((nonnull(1, 2)));

// Append element to end, transfer ownership: *data is moved in and zeroed.
void GenVec_push_move(GenVec* vec, void* data) __attribute__((nonnull(1, 2)));

// Remove the last element. popped != NULL: the element is MOVED into it and the
// caller owns it. popped == NULL: the element is deleted.
void GenVec_pop(GenVec* vec, void* popped) __attribute__((nonnull(1)));

// O(1) removal from the middle when order doesn't matter: element i is moved
// into out (or deleted if out == NULL), the last element takes its place.
void GenVec_swap_pop(GenVec* vec, u64 i, void* out) __attribute__((nonnull(1)));

// Swap elements i and j in place. Never allocates.
void GenVec_swap(GenVec* vec, u64 i, u64 j) __attribute__((nonnull(1)));

// Deep COPY of element i into out (the vector keeps its own).
void GenVec_get(const GenVec* vec, u64 i, void* out) __attribute__((nonnull(1, 3)));

// Get pointer to element at index i.
// Note: Pointer invalidated by push/insert/remove operations.
const void* GenVec_get_ptr(const GenVec* vec, u64 i) __attribute__((nonnull(1)));

// Get MUTABLE pointer to element at index i.
// Note: Pointer invalidated by push/insert/remove operations.
void* GenVec_get_ptr_mut(GenVec* vec, u64 i) __attribute__((nonnull(1)));

// UNCHECKED variants: same as above but with the bounds WC_ASSERT elided, even in
// Debug. Preconditions are NOT validated: caller must guarantee i < vec->size.
// Use on hot paths where the check is provably redundant (macros, internal loops).
static inline __attribute__((nonnull(1))) const void* GenVec_get_ptr_unsafe(const GenVec* vec, u64 i)
{
    return (vec->data + (i * vec->data_size));
}

static inline __attribute__((nonnull(1))) void* GenVec_get_ptr_mut_unsafe(GenVec* vec, u64 i)
{
    return (vec->data + (i * vec->data_size));
}

// Replace element at index i with data (cleans up old element).
void GenVec_replace(GenVec* vec, u64 i, const void* data) __attribute__((nonnull(1, 3)));

// Replace element at index i, transfer ownership (cleans up old element, zeroes *data).
void GenVec_replace_move(GenVec* vec, u64 i, void* data) __attribute__((nonnull(1, 3)));

// Insert element at index i, shifting elements right.
void GenVec_insert(GenVec* vec, u64 i, const void* data) __attribute__((nonnull(1, 3)));

// Insert element at index i with ownership transfer (zeroes *data), shifting elements right.
void GenVec_insert_move(GenVec* vec, u64 i, void* data) __attribute__((nonnull(1, 3)));

// Insert num_data elements from data array into vec at index i.
void GenVec_insert_multi(GenVec* vec, u64 i, const void* data, u64 num_data) __attribute__((nonnull(1, 3)));

// Insert (move) num_data contiguous elements from data at index i; the source range is zeroed.
void GenVec_insert_multi_move(GenVec* vec, u64 i, void* data, u64 num_data) __attribute__((nonnull(1, 3)));

// Remove element at index i, shift elements left. out != NULL: the element is
// MOVED into it. out == NULL: the element is deleted.
void GenVec_remove(GenVec* vec, u64 i, void* out) __attribute__((nonnull(1)));

// Remove elements in range [start, start + len)
void GenVec_remove_range(GenVec* vec, u64 start, u64 len) __attribute__((nonnull(1)));

// Get pointer to first element.
const void* GenVec_front(const GenVec* vec) __attribute__((nonnull(1)));

// Get pointer to last element.
const void* GenVec_back(const GenVec* vec) __attribute__((nonnull(1)));

// Search
// ===========================

// if cmp_fn = NULL, then use memcmp
u64 GenVec_find(const GenVec* vec, void* elm, wc_compare_fn cmp_fn) __attribute__((nonnull(1, 2)));

// New vector (storage from `alloc`) holding deep copies of [start, start + len).
GenVec GenVec_subarr(const GenVec* vec, const wc_allocator* alloc, u64 start, u64 len)
    __attribute__((nonnull(1, 2), warn_unused_result));


// Utility
// ===========================

// Print all elements using provided print function.
void GenVec_print(const GenVec* vec, wc_print_fn fn) __attribute__((nonnull(1, 2)));

// Deep copy of src whose storage (and every element's owned resources, via
// copy_fn) comes from `alloc`. Never inherits src's allocator (A14).
// Capacity is max(size, GENVEC_MIN_CAPACITY), or 0 for an empty src: a copy
// does not carry the source's slack (F5).
GenVec GenVec_copy(const wc_allocator* alloc, const GenVec* src) __attribute__((nonnull(1, 2), warn_unused_result));

// Transfer everything from src to dest; src is left zeroed.
// dest must be uninitialised or destroyed (its old contents are overwritten, not freed).
void GenVec_move(GenVec* dest, GenVec* src) __attribute__((nonnull(1, 2)));


// Get number of elements in vector.
static inline __attribute__((nonnull(1))) u64 GenVec_size(const GenVec* vec)
{
    return vec->size;
}

// Get total capacity of vector.
static inline __attribute__((nonnull(1))) u64 GenVec_capacity(const GenVec* vec)
{
    return vec->capacity;
}

// Check if vector is empty
static inline __attribute__((nonnull(1))) bool GenVec_empty(const GenVec* vec)
{
    return vec->size == 0;
}



#endif // GEN_VECTOR_H

/* ===== wc_string.h ===== */
#line 1 "include/wc_string.h"
#ifndef STRING_H
#define STRING_H




#include <stdint.h>
#include <string.h>


#ifndef STRING_GROWTH
#define STRING_GROWTH 1.5F // capacity multiplier on grow
#endif

// SSO inline buffer size (bytes).  Last byte is the mode flag:
//   nonzero = SSO mode (the string lives in stk[]).
//   '\0'    = heap mode (the string lives in heap).
// Usable SSO bytes = STR_SSO_SIZE - 1 = 23.
#define STR_SSO_SIZE 24

typedef struct {
    union {
        char* heap;
        char  stk[STR_SSO_SIZE];
    };
    u64           size;
    u64           capacity;
    const wc_allocator* alloc;
} String;


_Static_assert(sizeof(String) == 48, "String must be 48 bytes");


//  Construction / Destruction

// Create an empty String using allocator `a`.
String String_create(const wc_allocator* a) __attribute__((nonnull(1), warn_unused_result));

// Create a String from a C string using allocator `a`.
String String_from_cstr(const wc_allocator* a, const char* cstr) __attribute__((nonnull(1), warn_unused_result));

// Destroy the String's internal buffer
// Safe on a zeroed/moved-from String.
void String_destroy(String* str) __attribute__((nonnull(1)));

// Deep copy src → new String in allocator `a`.
// dest is raw/uninitialized: never reads it before writing.
String String_copy(const wc_allocator* a, const String* src) __attribute__((nonnull(1, 2), warn_unused_result));

// Transfer ownership: dest gets src's contents, src is zeroed.
void String_move(String* dest, String* src) __attribute__((nonnull(1, 2)));

// TODO: just use a StrView for this? can we for hashmap lookup?
// Non-owning, READ-ONLY String over `len` existing bytes: no allocation.
// For lookups only: a String-keyed map or set hashes and compares it like an
// owning String with the same bytes. Never store it in a container.
// Any mutation is fatal (WC_BORROWED cannot allocate); destroy is a no-op.
__attribute__((nonnull(1))) static inline String String_borrow(const char* p, u64 len)
{
    String s;
    memset(&s, 0, sizeof(s)); // stk[STR_SSO_SIZE - 1] == 0: heap mode
    s.heap     = (char*)(uintptr_t)p;
    s.size     = len;
    s.capacity = len ? len : 1; // capacity 0 is the zero state
    s.alloc    = WC_BORROWED;
    return s;
}


//  Capacity

// Ensure capacity >= new_cap (never shrinks).
void String_reserve(String* str, u64 new_cap) __attribute__((nonnull(1)));

// Reserve capacity and fill new slots with c.
void String_reserve_char(String* str, u64 new_cap, char c) __attribute__((nonnull(1)));

// Shrink allocation to exactly fit current size.
void String_shrink_to_fit(String* str) __attribute__((nonnull(1)));


//  Conversion

// Return a buffer (allocated from `a`) holding a NUL-terminated copy — caller
// must free with wc_free(a, ptr, str->size + 1, 1).
char* String_to_cstr(const wc_allocator* a, const String* str) __attribute__((nonnull(1, 2), warn_unused_result));

void String_to_cstr_buf(const String* str, char* buff, u64 n) __attribute__((nonnull(1, 2)));

// Return a raw pointer into the internal buffer (no NUL terminator).
char* String_data_ptr(const String* str) __attribute__((nonnull(1)));

// Guarantee a '\0' sits one byte past the last real character, WITHOUT
// touching str->size. Grows exactly like String_append_char would.
void String_ensure_null_term(String* str) __attribute__((nonnull(1)));


//  Modification

void String_append_char(String* str, char c) __attribute__((nonnull(1)));
void String_append_cstr(String* str, const char* cstr) __attribute__((nonnull(1, 2)));
void String_append_String(String* str, const String* other) __attribute__((nonnull(1, 2)));
// Append other then destroy it (leaves other zeroed). When str is empty and
// both share an allocator, str takes over other's buffer: no copy.
void String_append_String_move(String* str, String* other) __attribute__((nonnull(1, 2)));

char String_pop_char(String* str) __attribute__((nonnull(1)));

void String_insert_char(String* str, u64 i, char c) __attribute__((nonnull(1)));
void String_insert_cstr(String* str, u64 i, const char* cstr) __attribute__((nonnull(1, 3)));
void String_insert_String(String* str, u64 i, const String* other) __attribute__((nonnull(1, 3)));

void String_remove_char(String* str, u64 i) __attribute__((nonnull(1)));

// Remove chars in range [start, start + len)
void String_remove_range(String* str, u64 start, u64 len) __attribute__((nonnull(1)));

// Remove all chars (keep allocation).
__attribute__((nonnull(1))) static inline void String_clear(String* str)
{
    str->size = 0;
}


//  Access

__attribute__((nonnull(1))) static inline char String_char_at(const String* str, u64 i)
{
    WC_ASSERT(i < str->size, "index out of bounds");
    return ((str->stk[STR_SSO_SIZE - 1] != '\0') ? str->stk : str->heap)[i];
}

// UNCHECKED: no bounds check, even in Debug. Caller guarantees i < size.
__attribute__((nonnull(1))) static inline char String_char_at_unsafe(const String* str, u64 i)
{
    return ((str->stk[STR_SSO_SIZE - 1] != '\0') ? str->stk : str->heap)[i];
}

__attribute__((nonnull(1))) static inline void String_set_char(String* str, u64 i, char c)
{
    WC_ASSERT(i < str->size, "index out of bounds");
    ((str->stk[STR_SSO_SIZE - 1] != '\0') ? str->stk : str->heap)[i] = c;
}


//  Comparison

// 0 == equal, <0 == str1 < str2, >0 == str1 > str2
int String_compare(const String* s1, const String* s2) __attribute__((nonnull(1, 2)));
__attribute__((nonnull(1, 2))) static inline bool String_equals(const String* s1, const String* s2)
{
    return String_compare(s1, s2) == 0;
}
bool String_equals_cstr(const String* str, const char* cstr) __attribute__((nonnull(1, 2)));


//  Search

// Returns index, or WC_NOT_FOUND if not found.
u64 String_find_char(const String* str, char c) __attribute__((nonnull(1)));
u64 String_find_cstr(const String* str, const char* substr) __attribute__((nonnull(1, 2)));

// Return a String (in allocator `a`) holding `length` chars starting at `start`.
String String_substr(const wc_allocator* a, const String* str, u64 start, u64 length)
    __attribute__((nonnull(1, 2), warn_unused_result));


//  I/O

void String_print(const String* str) __attribute__((nonnull(1)));


//  Inline helpers

__attribute__((nonnull(1))) static inline u64 String_len(const String* str)
{
    return str->size;
}

__attribute__((nonnull(1))) static inline u64 String_capacity(const String* str)
{
    return str->capacity;
}

__attribute__((nonnull(1))) static inline bool String_empty(const String* str)
{
    return str->size == 0;
}

__attribute__((nonnull(1))) static inline bool String_is_sso(const String* str)
{
    return str->stk[STR_SSO_SIZE - 1] != '\0';
}

// Read-only pointer into the buffer. Unlike String_data_ptr, this never
// returns NULL for an empty String. Internally, it uses String_ensure_null_term(),
// which places a '\0' right after the last valid char without touching the size of the string.
__attribute__((nonnull(1))) static inline const char* String_cstr_view(String* str)
{
    String_ensure_null_term(str);
    return String_is_sso(str) ? str->stk : str->heap;
}


#endif // STRING_H

/* ===== wc_helpers.h ===== */
#line 1 "include/wc_helpers.h"
#ifndef HELPERS_H
#define HELPERS_H

/*
 * wc_helpers.h: Generic container callbacks and typed macros for WCtoolkit
 * =======================================================================
 *
 * ALL functions are static inline to avoid multiple-definition linker
 * errors when this header is included in more than one translation unit.
 *
 * SECTIONS
 * --------
 *   1.  String by value  (sizeof(String) per slot)
 *   2.  String by pointer (sizeof(String*) per slot)
 *   3.  GenVec by value  (sizeof(GenVec) per slot)  — vec of vecs
 *   4.  GenVec by pointer (sizeof(GenVec*) per slot)
 *   5.  Shared ops instances (define once, reference everywhere)
 *
 * RULES FOR WRITING copy/del CALLBACKS
 * -------------------------------------
 *
 * BY VALUE  (slot holds the full struct, sizeof(T) bytes)
 *   copy_fn(const wc_allocator* dst, void* dest, const void* src)
 *     dest  — raw bytes of the slot (uninitialised — treat as blank)
 *     job   — deep-copy src into dest, allocating owned resources from `dst`
 *             (the container's allocator). DO NOT free dest first.
 *
 *   del_fn(void* elm)
 *     job   — free owned resources (with the element's OWN stored allocator)
 *             but NOT elm itself → GenVec_destroy, String_destroy, ...
 *
 * BY POINTER  (slot holds T*, sizeof(T*) = 8 bytes)
 *   copy_fn: *(T**)dest = a new shell from `dst` holding a deep copy (WC_BOX_IN)
 *   del_fn : destroy the pointee, then free the shell with the pointee's own
 *            allocator (shell allocator == child allocator, rule B12)
 */





#include <stdalign.h>
#include <stdio.h>



/* 
 * 1.  STRING BY VALUE
 *
 * String stores its own allocator.
 * str_copy  — copies using dst allocator (so a String follows its outer container)
 * str_del   — delegates to String_destroy() (frees heap buf via str->alloc, NOT the slot)
*/

static inline void str_copy(const wc_allocator* dst, void* dest, const void* src)
{
    *(String*)dest = String_copy(dst, (const String*)src);
}

static inline void str_del(void* elm)
{
    String_destroy((String*)elm); // free data buffer via str->alloc, NOT the slot
}

static inline void str_print(const void* elm)
{
    String_print((const String*)elm);
}


/*
 * 2.  STRING BY POINTER
 *
 * str_copy_ptr — box a deep copy in allocator `dst` (shell + contents from dst)
 * str_del_ptr  — destroy pointee via its own allocator, then free shell
*/

static inline void str_copy_ptr(const wc_allocator* dst, void* dest, const void* src)
{
    // Box a deep copy: shell and contents both from dst
    *(String**)dest = (String*)WC_BOX_IN(dst, String, String_copy, *(const String* const*)src);
}

static inline void str_del_ptr(void* elm)
{
    String* s = *(String**)elm;
    if (!s) {
        return;
    }
    // Read allocator before destroy zeroes the struct
    const wc_allocator* a = s->alloc;
    String_destroy(s);                              // free heap buffer via s->alloc
    wc_free(a, s, sizeof(String), alignof(String)); // free the shell
}

static inline void str_print_ptr(const void* elm)
{
    String_print(*(const String**)elm);
}

static inline int str_cmp(const void* a, const void* b, u64 size)
{
    (void)size;
    return String_compare((const String*)a, (const String*)b);
}

static inline int str_cmp_ptr(const void* a, const void* b, u64 size)
{
    (void)size;
    return String_compare(*(const String**)a, *(const String**)b);
}


/*
 * 3.  GENVEC BY VALUE  (vec of vecs)
*/ 

static inline void vec_copy(const wc_allocator* dst, void* dest, const void* src)
{
    *(GenVec*)dest = GenVec_copy(dst, (const GenVec*)src); // inner vec follows the outer container
}

static inline void vec_del(void* elm)
{
    GenVec_destroy((GenVec*)elm); // frees data with the inner vec's own allocator, NOT the slot
}

static inline void vec_print_int(const void* elm)
{
    const GenVec* v = (const GenVec*)elm;
    printf("[");
    for (u64 i = 0; i < v->size; i++) {
        printf("%d", *(int*)GenVec_get_ptr(v, i));
        if (i + 1 < v->size) {
            printf(", ");
        }
    }
    printf("]");
}


/*
 * 4.  GENVEC BY POINTER  (slot holds GenVec*)
*/

static inline void vec_copy_ptr(const wc_allocator* dst, void* dest, const void* src)
{
    // shell and contents both from dst: the shell allocator equals the child's (D6)
    *(GenVec**)dest = WC_BOX_IN(dst, GenVec, GenVec_copy, *(const GenVec* const*)src);
}

static inline void vec_del_ptr(void* elm)
{
    GenVec* v = *(GenVec**)elm;
    if (!v) {
        return;
    }
    const wc_allocator* a = v->alloc; // read before destroy zeroes it
    GenVec_destroy(v);
    wc_free(a, v, sizeof(GenVec), alignof(GenVec));
}

static inline void vec_print_int_ptr(const void* elm)
{
    vec_print_int(*(const GenVec**)elm);
}


/*
 * 5.  SHARED OPS INSTANCES
 *
 * Define once here as static const. Reference by address wherever needed.
 * No per-instance overhead — all vectors of the same type share the pointer.
 *
 * Usage:
 *   GenVec v = GenVec_create(WC_LIBC, 8, sizeof(String), &wc_str_ops);
 *   HashMap m = HashMap_create(WC_LIBC, ..., &wc_str_ops, &wc_str_ops);
*/

static const wc_container_ops wc_str_ops     = {.copy_fn = str_copy, .del_fn = str_del};
static const wc_container_ops wc_str_ptr_ops = {.copy_fn = str_copy_ptr, .del_fn = str_del_ptr};
static const wc_container_ops wc_vec_ops     = {.copy_fn = vec_copy, .del_fn = vec_del};
static const wc_container_ops wc_vec_ptr_ops = {.copy_fn = vec_copy_ptr, .del_fn = vec_del_ptr};


#endif // HELPERS_H

#ifdef WC_IMPLEMENTATION

#ifndef WC_WC_ALLOCATOR_IMPL
#define WC_WC_ALLOCATOR_IMPL
/* ===== wc_allocator.c ===== */
#line 1 "src/wc_allocator.c"

#include <stddef.h>



/* wc_libc: the only allocator with vt == NULL */

const wc_allocator wc_libc = {.vt = NULL, .ctx = NULL};


/* wc_borrowed: non-owning allocator */

static void* wc_borrowed_alloc(void* ctx, size_t size, size_t align)
{
    (void)ctx;
    (void)size;
    (void)align;
    return NULL;
}

static void wc_borrowed_free(void* ctx, void* p, size_t size, size_t align)
{
    (void)ctx;
    (void)p;
    (void)size;
    (void)align;
}

static const wc_alloc_vtable wc_borrowed_vt = {
    .alloc   = wc_borrowed_alloc,
    .realloc = NULL, // emulated: alloc fails, so growth fails and p stays valid
    .free    = wc_borrowed_free,
};

const wc_allocator wc_borrowed = {.vt = &wc_borrowed_vt, .ctx = NULL};

#endif /* WC_WC_ALLOCATOR_IMPL */

#ifndef WC_WC_ERRNO_IMPL
#define WC_WC_ERRNO_IMPL
/* ===== wc_errno.c ===== */
#line 1 "src/wc_errno.c"



#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>


/* One definition of the thread-local error variable.
 * Every translation unit that includes wc_error.h sees the extern declaration.
 * This file provides the actual storage.
 */
_Thread_local wc_err wc_errno = WC_OK;


/* Diagnostics reporters (common.h). Defined once, out of line and `cold`:
 * the compiler places them, and every branch that calls them, away from hot
 * code. Both write to stderr so diagnostics never mix into program output. */

// The installed fatal handler; NULL means the default (print + exit).
static wc_fatal_fn g_fatal_handler = NULL;

wc_fatal_fn wc_set_fatal_handler(wc_fatal_fn fn)
{
    wc_fatal_fn prev = g_fatal_handler;
    g_fatal_handler  = fn;
    return prev;
}

void wc_fatal_report(const char* file, int line, const char* func, const char* fmt, ...)
{
    fflush(stdout); // keep ordering with anything already printed

    char    msg[512];
    va_list args;
    va_start(args, fmt);
    vsnprintf(msg, sizeof(msg), fmt, args);
    va_end(args);

    if (g_fatal_handler) {
        g_fatal_handler(file, line, func, msg); // must not return
    } else {
        fprintf(stderr, WC_COLOR_RED "[FATAL] %s:%d:%s(): %s\n" WC_COLOR_RESET, file, line, func, msg);
    }
    exit(EXIT_FAILURE); // default, and the backstop for a handler that returns
}

void wc_warn_report(const char* file, int line, const char* func, const char* fmt, ...)
{
    fflush(stdout);
    fprintf(stderr, WC_COLOR_YELLOW "[WARN] %s:%d:%s(): ", file, line, func);
    va_list args;
    va_start(args, fmt);
    vfprintf(stderr, fmt, args);
    va_end(args);
    fprintf(stderr, "\n" WC_COLOR_RESET);
}

#endif /* WC_WC_ERRNO_IMPL */

#ifndef WC_GEN_VECTOR_IMPL
#define WC_GEN_VECTOR_IMPL
/* ===== gen_vector.c ===== */
#line 1 "src/gen_vector.c"





#include <stdio.h>
#include <string.h>


// MACROS

// get ptr to elm at index i
#define GET_PTR(vec, i) (((vec)->data) + ((u64)(i) * ((vec)->data_size)))
// get total size in bytes for i elements
#define GET_SCALED(vec, i) ((u64)(i) * ((vec)->data_size))

// Growth is amortized: rare by construction, so the hint is known-correct.
#define MAYBE_GROW(vec) \
    ((void)(WC_UNLIKELY((vec)->size >= (vec)->capacity) && (GenVec_grow_to((vec), (vec)->size + 1), 0)))

// smallest safe alignment for this element size
#define DATA_ALIGN(vec) wc_align_for_size((vec)->data_size)

// a zeroed vector (moved-from / destroyed) must never allocate
#define ZERO_GUARD(vec) \
    FATAL_IF((vec)->data_size == 0, "GenVec is in the zero state (moved-from or destroyed): re-create it first")

// D4: an input element must not live inside this vector's own storage. Growth
// would free it before it is read. Checked over the whole capacity (Debug only).
#define NOT_ALIASED(vec, p)                                                         \
    WC_ASSERT(!((vec)->data && (const u8*)(p) >= (vec)->data &&                     \
                (const u8*)(p) < (vec)->data + GET_SCALED((vec), (vec)->capacity)), \
              "input element points into this vector's own buffer (rule D4): copy it out first")

// Copy one element INTO raw slot memory: copy_fn if any, else memcpy
static inline void vec_copy_into(const GenVec* vec, u8* dest, const void* src)
{
    wc_copy_fn copy = vec->is_pod ? NULL : VEC_COPY_FN(vec);
    if (copy) {
        copy(vec->alloc, dest, src);
    } else {
        memcpy(dest, src, vec->data_size);
    }
}

// Move one element (always memcpy). The source is left zeroed.
static inline void vec_move_into(const GenVec* vec, u8* dest, void* src)
{
    memcpy(dest, src, vec->data_size);
    memset(src, 0, vec->data_size);
}

// Delete `n` elements starting at `p`.
static inline void vec_delete_range(const GenVec* vec, u8* p, u64 n)
{
    wc_delete_fn del = vec->is_pod ? NULL : VEC_DEL_FN(vec);
    if (del) {
        for (u64 i = 0; i < n; i++) {
            del(p + GET_SCALED(vec, i));
        }
    }
}

// Take element at `slot` out: moved into `out`, or deleted when out == NULL (B7).
// The slot itself is left as garbage: callers drop it from the live range.
static inline void vec_take_out(const GenVec* vec, u8* slot, void* out)
{
    if (out) {
        memcpy(out, slot, vec->data_size);
    } else {
        vec_delete_range(vec, slot, 1);
    }
}


#define IS_POD(vec)   ((vec)->is_pod) // cached at init
#define CALC_POD(ops) ((ops) == NULL) // derive from ops. ONLY valid at init time


// private functions

static void GenVec_grow_to(GenVec* vec, u64 needed);


// API Implementation

#define ALLOC_OR_DIE(a, n, data_size)                                                                            \
    ({                                                                                                           \
        u8* data = NULL;                                                                                         \
        if ((n) != 0) {                                                                                          \
            data = wc_alloc(a, wc_mul(n, data_size), wc_align_for_size(data_size));                              \
            FATAL_IF(!data, "GenVec: allocation of %llu x %u bytes failed", (unsigned long long)(n), data_size); \
        }                                                                                                        \
        data;                                                                                                    \
    })


GenVec GenVec_create(const wc_allocator* alloc, u64 n, u32 data_size, const wc_container_ops* ops)
{
    FATAL_IF(data_size == 0, "GenVec: data_size can't be 0");

    return (GenVec){
        .data      = ALLOC_OR_DIE(alloc, n, data_size),
        .ops       = ops,
        .size      = 0,
        .capacity  = n,
        .alloc     = alloc,
        .data_size = data_size,
        .is_pod    = CALC_POD(ops),
    };
}


GenVec GenVec_create_val(const wc_allocator* alloc, u64 n, const void* val, u32 data_size, const wc_container_ops* ops)
{
    WC_ASSERT(n != 0, "cant init with val if n = 0");

    GenVec v = GenVec_create(alloc, n, data_size, ops);

    if (v.is_pod || !VEC_COPY_FN(&v)) {
        // First element by copy, then double the filled prefix: O(log n) memcpy calls of
        // growing length instead of n calls of runtime length.
        memcpy(v.data, val, data_size);
        for (u64 filled = 1; filled < n;) {
            u64 chunk = filled < n - filled ? filled : n - filled;
            memcpy(GET_PTR(&v, filled), v.data, chunk * data_size);
            filled += chunk;
        }
    } else {
        for (u64 i = 0; i < n; i++) {
            vec_copy_into(&v, GET_PTR(&v, i), val);
        }
    }
    v.size = n;

    return v;
}


GenVec GenVec_create_buf(void* buf, u64 n, u32 data_size, const wc_container_ops* ops)
{
    FATAL_IF(n == 0 || data_size == 0, "GenVec_create_buf: n/data_size can't be 0");

    return (GenVec){
        .data      = buf,
        .ops       = ops,
        .size      = 0,
        .capacity  = n,
        .alloc     = WC_BORROWED,
        .data_size = data_size,
        .is_pod    = CALC_POD(ops),
    };
}


void GenVec_destroy(GenVec* vec)
{
    if (vec->data) {
        vec_delete_range(vec, vec->data, vec->size);
        wc_free(vec->alloc, vec->data, GET_SCALED(vec, vec->capacity), DATA_ALIGN(vec));
    }
    memset(vec, 0, sizeof(*vec));
}

void GenVec_clear(GenVec* vec)
{
    if (vec->data) {
        vec_delete_range(vec, vec->data, vec->size);
    }
    vec->size = 0;
}

void GenVec_reset(GenVec* vec)
{
    if (vec->data) {
        vec_delete_range(vec, vec->data, vec->size);
        wc_free(vec->alloc, vec->data, GET_SCALED(vec, vec->capacity), DATA_ALIGN(vec));
    }
    vec->data     = NULL;
    vec->size     = 0;
    vec->capacity = 0;
}


void GenVec_reserve(GenVec* vec, u64 new_capacity)
{
    if (new_capacity <= vec->capacity) {
        return;
    }
    ZERO_GUARD(vec);

    u8* new_data = wc_realloc(vec->alloc, vec->data, GET_SCALED(vec, vec->capacity),
                              wc_mul(new_capacity, vec->data_size), DATA_ALIGN(vec));
    FATAL_IF(!new_data, "GenVec_reserve: realloc to %llu elements failed", (unsigned long long)new_capacity);

    vec->data     = new_data;
    vec->capacity = new_capacity;
}


void GenVec_reserve_val(GenVec* vec, u64 new_capacity, const void* val)
{
    WC_ASSERT(new_capacity >= vec->size, "new_capacity must be >= current size");
    NOT_ALIASED(vec, val);

    GenVec_reserve(vec, new_capacity);

    u64 count = new_capacity - vec->size; // elements to fill
    if (count == 0) {
        return;
    }
    if (vec->is_pod || !VEC_COPY_FN(vec)) {
        // Plain bytes: first element by copy, then double the filled run (O(log n) memcpy calls
        // of growing length instead of one runtime-length call per element).
        memcpy(GET_PTR(vec, vec->size), val, vec->data_size);
        for (u64 filled = 1; filled < count;) {
            u64 chunk = filled < count - filled ? filled : count - filled;
            memcpy(GET_PTR(vec, vec->size + filled), GET_PTR(vec, vec->size), chunk * vec->data_size);
            filled += chunk;
        }
    } else {
        for (u64 i = vec->size; i < new_capacity; i++) {
            vec_copy_into(vec, GET_PTR(vec, i), val);
        }
    }
    vec->size = new_capacity;
}


void GenVec_shrink_to_fit(GenVec* vec)
{
    u64 min_cap  = vec->size > GENVEC_MIN_CAPACITY ? vec->size : GENVEC_MIN_CAPACITY;
    u64 curr_cap = vec->capacity;

    if (curr_cap <= min_cap) {
        return;
    }

    u8* new_data =
        wc_realloc(vec->alloc, vec->data, GET_SCALED(vec, curr_cap), GET_SCALED(vec, min_cap), DATA_ALIGN(vec));
    FATAL_IF(!new_data, "GenVec_shrink_to_fit: realloc failed");

    vec->data     = new_data;
    vec->capacity = min_cap;
}


void GenVec_push(GenVec* vec, const void* data)
{
    NOT_ALIASED(vec, data);
    MAYBE_GROW(vec);
    vec_copy_into(vec, GET_PTR(vec, vec->size), data);
    vec->size++;
}

void GenVec_push_move(GenVec* vec, void* data)
{
    NOT_ALIASED(vec, data);
    MAYBE_GROW(vec);
    vec_move_into(vec, GET_PTR(vec, vec->size), data);
    vec->size++;
}

void GenVec_pop(GenVec* vec, void* popped)
{
    WC_SET_RET(WC_ERR_EMPTY, vec->size == 0, );

    vec->size--;
    vec_take_out(vec, GET_PTR(vec, vec->size), popped);
}

void GenVec_swap_pop(GenVec* vec, u64 i, void* out)
{
    WC_ASSERT(i < vec->size, "index out of bounds");

    vec_take_out(vec, GET_PTR(vec, i), out);

    // the last element takes slot i (a relocation: memcpy)
    vec->size--;
    if (i != vec->size) {
        memcpy(GET_PTR(vec, i), GET_PTR(vec, vec->size), vec->data_size);
    }
}

void GenVec_swap(GenVec* vec, u64 i, u64 j)
{
    WC_ASSERT(i < vec->size && j < vec->size, "index out of bounds");

    if (i == j) {
        return;
    }

    // Swap through a small stack buffer in chunks: no growth, no spare slot
    u8* a = GET_PTR(vec, i);
    u8* b = GET_PTR(vec, j);
    u8  tmp[64];
    for (u64 left = vec->data_size; left > 0;) {
        u64 n = left < sizeof(tmp) ? left : sizeof(tmp);
        memcpy(tmp, a, n);
        memcpy(a, b, n);
        memcpy(b, tmp, n);
        a += n;
        b += n;
        left -= n;
    }
}


void GenVec_get(const GenVec* vec, u64 i, void* out)
{
    WC_ASSERT(i < vec->size, "index out of bounds");
    vec_copy_into(vec, out, GET_PTR(vec, i));
}

const void* GenVec_get_ptr(const GenVec* vec, u64 i)
{
    WC_ASSERT(i < vec->size, "index out of bounds");
    return GET_PTR(vec, i);
}

void* GenVec_get_ptr_mut(GenVec* vec, u64 i)
{
    WC_ASSERT(i < vec->size, "index out of bounds");
    return GET_PTR(vec, i);
}


void GenVec_replace(GenVec* vec, u64 i, const void* data)
{
    WC_ASSERT(i < vec->size, "index out of bounds");
    NOT_ALIASED(vec, data);

    u8* to_replace = GET_PTR(vec, i);
    vec_delete_range(vec, to_replace, 1);
    vec_copy_into(vec, to_replace, data);
}

void GenVec_replace_move(GenVec* vec, u64 i, void* data)
{
    WC_ASSERT(i < vec->size, "index out of bounds");
    NOT_ALIASED(vec, data);

    u8* to_replace = GET_PTR(vec, i);
    vec_delete_range(vec, to_replace, 1);
    vec_move_into(vec, to_replace, data);
}


void GenVec_insert(GenVec* vec, u64 i, const void* data)
{
    WC_ASSERT(i <= vec->size, "index out of bounds");
    NOT_ALIASED(vec, data);

    MAYBE_GROW(vec);

    u8* slot = GET_PTR(vec, i);
    memmove(GET_PTR(vec, i + 1), slot, GET_SCALED(vec, vec->size - i));
    vec_copy_into(vec, slot, data);
    vec->size++;
}


void GenVec_insert_move(GenVec* vec, u64 i, void* data)
{
    WC_ASSERT(i <= vec->size, "index out of bounds");
    NOT_ALIASED(vec, data);

    MAYBE_GROW(vec);

    u8* slot = GET_PTR(vec, i);
    memmove(GET_PTR(vec, i + 1), slot, GET_SCALED(vec, vec->size - i));
    vec_move_into(vec, slot, data);
    vec->size++;
}


// Open a gap of `n` slots at index i (grows geometrically). Returns the gap.
static u8* vec_open_gap(GenVec* vec, u64 i, u64 n)
{
    if (vec->size + n > vec->capacity) {
        GenVec_grow_to(vec, vec->size + n);
    }
    u8* gap = GET_PTR(vec, i);
    if (i < vec->size) {
        memmove(GET_PTR(vec, i + n), gap, GET_SCALED(vec, vec->size - i));
    }
    vec->size += n;
    return gap;
}


void GenVec_insert_multi(GenVec* vec, u64 i, const void* data, u64 num_data)
{
    WC_ASSERT(num_data != 0 && i <= vec->size, "num_data can't be 0 / index out of bounds");
    NOT_ALIASED(vec, data);

    u8* gap = vec_open_gap(vec, i, num_data);

    if (vec->is_pod || !VEC_COPY_FN(vec)) {
        memcpy(gap, data, GET_SCALED(vec, num_data));
    } else {
        for (u64 j = 0; j < num_data; j++) {
            vec_copy_into(vec, gap + GET_SCALED(vec, j), (const u8*)data + GET_SCALED(vec, j));
        }
    }
}


void GenVec_insert_multi_move(GenVec* vec, u64 i, void* data, u64 num_data)
{
    WC_ASSERT(num_data != 0 && i <= vec->size, "num_data can't be 0 / index out of bounds");
    NOT_ALIASED(vec, data);

    u8* gap = vec_open_gap(vec, i, num_data);

    // one block move: memcpy the whole range, then zero the source range
    memcpy(gap, data, GET_SCALED(vec, num_data));
    memset(data, 0, GET_SCALED(vec, num_data));
}


void GenVec_remove(GenVec* vec, u64 i, void* out)
{
    WC_ASSERT(i < vec->size, "index out of bounds");

    vec_take_out(vec, GET_PTR(vec, i), out);

    u64 elements_to_shift = vec->size - i - 1;
    if (elements_to_shift > 0) {
        memmove(GET_PTR(vec, i), GET_PTR(vec, i + 1), GET_SCALED(vec, elements_to_shift));
    }

    vec->size--;
}


void GenVec_remove_range(GenVec* vec, u64 start, u64 len)
{
    if (len == 0) {
        return;
    }
    WC_ASSERT(start < vec->size, "start out of range");

    if (len > vec->size - start) {
        len = vec->size - start;
    }

    vec_delete_range(vec, GET_PTR(vec, start), len);

    u8* dest = GET_PTR(vec, start);
    u8* src  = GET_PTR(vec, start + len);
    memmove(dest, src, GET_SCALED(vec, vec->size - start - len));

    vec->size -= len;
}


const void* GenVec_front(const GenVec* vec)
{
    WC_SET_RET(WC_ERR_EMPTY, vec->size == 0, NULL);
    return GET_PTR(vec, 0);
}


const void* GenVec_back(const GenVec* vec)
{
    WC_SET_RET(WC_ERR_EMPTY, vec->size == 0, NULL);
    return GET_PTR(vec, vec->size - 1);
}


u64 GenVec_find(const GenVec* vec, void* elm, wc_compare_fn cmp_fn)
{
    if (!cmp_fn) {
        cmp_fn = memcmp;
    }
    for (u64 i = 0; i < vec->size; i++) {
        if (cmp_fn(GET_PTR(vec, i), elm, vec->data_size) == 0) {
            return i;
        }
    }

    return WC_NOT_FOUND;
}


GenVec GenVec_subarr(const GenVec* vec, const wc_allocator* alloc, u64 start, u64 len)
{
    WC_ASSERT(start < vec->size, "out of bounds");

    if (len > vec->size - start) {
        len = vec->size - start;
    }

    GenVec out = GenVec_create(alloc, len, vec->data_size, vec->ops);

    if (len > 0) {
        if (vec->is_pod || !VEC_COPY_FN(vec)) {
            memcpy(GET_PTR(&out, 0), GET_PTR(vec, start), GET_SCALED(vec, len));
        } else {
            for (u64 i = 0; i < len; i++) {
                vec_copy_into(&out, GET_PTR(&out, i), GET_PTR(vec, i + start));
            }
        }
        out.size = len;
    }

    return out;
}


void GenVec_print(const GenVec* vec, wc_print_fn fn)
{
    printf("[ ");
    for (u64 i = 0; i < vec->size; i++) {
        fn(GET_PTR(vec, i));
        putchar(' ');
    }
    putchar(']');
}


GenVec GenVec_copy(const wc_allocator* alloc, const GenVec* src)
{
    if (src->data_size == 0) {
        return (GenVec){0}; // copy of a zeroed vector is a zeroed vector
    }

    // size the copy to its contents, not to src's slack.
    u64 cap = src->size == 0 ? 0 : (src->size > GENVEC_MIN_CAPACITY ? src->size : GENVEC_MIN_CAPACITY);

    // Field by field: the allocator comes from the caller, never from src
    GenVec dest = {
        .data      = ALLOC_OR_DIE(alloc, cap, src->data_size),
        .ops       = src->ops,
        .size      = src->size,
        .capacity  = cap,
        .alloc     = alloc,
        .data_size = src->data_size,
        .is_pod    = src->is_pod,
    };

    wc_copy_fn copy = src->is_pod ? NULL : VEC_COPY_FN(src);
    if (copy) {
        for (u64 i = 0; i < src->size; i++) {
            copy(alloc, GET_PTR((&dest), i), GET_PTR(src, i));
        }
    } else if (src->size > 0) {
        memcpy(dest.data, src->data, GET_SCALED(src, src->size));
    }

    return dest;
}


void GenVec_move(GenVec* dest, GenVec* src)
{
    if (dest == src) {
        return;
    }
    memcpy(dest, src, sizeof(GenVec));
    memset(src, 0, sizeof(GenVec));
}


// Grow to hold at least `needed` elements: 0 -> GENVEC_MIN_CAPACITY, then 1.5x,
// or straight to `needed` when that is larger (bulk inserts, F4).
static void GenVec_grow_to(GenVec* vec, u64 needed)
{
    ZERO_GUARD(vec);

    u64 old_cap = vec->capacity;
    u64 new_cap = old_cap == 0 ? GENVEC_MIN_CAPACITY : old_cap + (old_cap / 2); // 0 -> MIN, then 1.5x (F3)
    if (new_cap <= old_cap) {
        new_cap = old_cap + 1; // small capacities: 1.5x rounds down to no growth
    }
    if (new_cap < needed) {
        new_cap = needed;
    }

    u8* new_data =
        wc_realloc(vec->alloc, vec->data, GET_SCALED(vec, old_cap), wc_mul(new_cap, vec->data_size), DATA_ALIGN(vec));
    if (!new_data) {
        FATAL("GenVec: growth to %llu elements failed (arena full, or borrowed buffer)", (unsigned long long)new_cap);
    }

    vec->data     = new_data;
    vec->capacity = new_cap;
}

#undef GET_PTR
#undef GET_SCALED
#undef MAYBE_GROW
#undef DATA_ALIGN
#undef ZERO_GUARD
#undef NOT_ALIASED
#undef IS_POD
#undef CALC_POD
#undef ALLOC_OR_DIE
#endif /* WC_GEN_VECTOR_IMPL */

#ifndef WC_WC_STRING_IMPL
#define WC_WC_STRING_IMPL
/* ===== wc_string.c ===== */
#line 1 "src/wc_string.c"




#include <stdio.h>
#include <string.h>


//  Internal macros

#define GET_STR_PTR(s, i)  (GET_STR(s) + (i))
#define GET_STR_CHAR(s, i) (GET_STR(s)[i])
#define STR_REMAINING(s)   ((s)->capacity - (s)->size)
#define IS_SSO(s)          ((s)->stk[STR_SSO_SIZE - 1] != '\0')
#define GET_STR(s)         (IS_SSO(s) ? (s)->stk : (s)->heap)

// Grow if full.
// D4: capacity == 0 means zeroed / moved-from; mutation is fatal.
#define MAYBE_GROW_STR(s)                                                            \
    ({                                                                               \
        FATAL_IF((s)->capacity == 0, "String mutation on zeroed/moved-from String"); \
        if (WC_UNLIKELY((s)->size >= (s)->capacity)) {                               \
            if (IS_SSO(s)) {                                                         \
                (s)->stk[STR_SSO_SIZE - 1] = '\0';                                   \
                stk_to_heap(s);                                                      \
            } else {                                                                 \
                String_grow(s);                                                      \
            }                                                                        \
        }                                                                            \
    })



//  Private helpers

static inline void stk_to_heap(String* s);
static inline void heap_to_stk(String* s);
static inline void String_grow(String* s);
static inline void ensure_capacity(String* s, u64 needed);

// Initialise the struct to SSO mode. a is stored so all subsequent allocations
// use it.  Does NOT allocate.
static inline void str_init_sso(String* s, const wc_allocator* a)
{
    s->size                  = 0;
    s->capacity              = STR_SSO_SIZE - 1; // 0..30 usable, last byte is mode flag
    s->stk[STR_SSO_SIZE - 1] = 1;                // nonzero = SSO mode
    s->alloc                 = a;
}



//  Construction / Destruction

String String_create(const wc_allocator* a)
{
    String s;
    str_init_sso(&s, a);
    return s;
}

String String_from_cstr(const wc_allocator* a, const char* cstr)
{
    String s;
    str_init_sso(&s, a);

    if (!cstr) {
        return s;
    }

    u64 len = strlen(cstr);
    if (len == 0) {
        return s;
    }

    ensure_capacity(&s, len);
    memcpy(GET_STR(&s), cstr, len);
    s.size = len;
    return s;
}

void String_destroy(String* s)
{
    if (!IS_SSO(s) && s->heap) {
        wc_free(s->alloc, s->heap, s->capacity, 1);
    }
    // Leave zeroed (capacity == 0 → zero state, safe for another destroy)
    memset(s, 0, sizeof(String));
}

String String_copy(const wc_allocator* a, const String* src)
{
    String s;
    str_init_sso(&s, a);

    if (src->size > 0) {
        ensure_capacity(&s, src->size);
        memcpy(GET_STR(&s), GET_STR(src), src->size);
        s.size = src->size;
    }

    return s;
}

void String_move(String* dest, String* src)
{
    *dest = *src;
    memset(src, 0, sizeof(String));
}


//  Capacity

void String_reserve(String* s, u64 new_cap)
{
    FATAL_IF(s->capacity == 0, "String_reserve on zeroed/moved-from String");
    if (new_cap <= s->capacity) {
        return;
    }
    ensure_capacity(s, new_cap);
}

void String_reserve_char(String* s, u64 new_cap, char c)
{
    FATAL_IF(s->capacity == 0, "String_reserve_char on zeroed/moved-from String");
    if (new_cap <= s->capacity) {
        char* buf = GET_STR(s);
        for (u64 i = s->size; i < new_cap; i++) {
            buf[i] = c;
        }
        s->size = new_cap;
        return;
    }

    u64 old_size = s->size;
    ensure_capacity(s, new_cap);

    char* buf = GET_STR(s);
    for (u64 i = old_size; i < new_cap; i++) {
        buf[i] = c;
    }
    s->size = new_cap;
}

void String_shrink_to_fit(String* s)
{
    if (IS_SSO(s)) {
        return; // already optimal
    }

    if (s->size <= STR_SSO_SIZE - 1) {
        // Bring back to SSO.
        // Covers size == 0: heap_to_stk frees the buffer AND restores the SSO flag.
        // (the old size == 0 branch freed the buffer but stayed in heap mode,
        //  leaving heap == NULL with capacity 23; the next append wrote to NULL.)
        heap_to_stk(s);
        return;
    }

    void* new_data = wc_realloc(s->alloc, s->heap, s->capacity, s->size, 1);
    if (!new_data) {
        WARN("shrink_to_fit realloc failed");
        return;
    }
    s->heap     = (char*)new_data;
    s->capacity = s->size;
}


//  Conversion

char* String_to_cstr(const wc_allocator* a, const String* s)
{
    char* out = wc_alloc(a, s->size + 1, 1);
    FATAL_IF(!out, "String_to_cstr: allocation failed");

    if (s->size > 0) {
        memcpy(out, GET_STR(s), s->size);
    }
    out[s->size] = '\0';

    return out;
}

void String_to_cstr_buf(const String* str, char* buff, u64 n)
{
    WC_ASSERT(n >= str->size + 1, "buffer not enough");

    if (str->size > 0) {
        memcpy(buff, GET_STR(str), str->size);
    }
    buff[str->size] = '\0';
}

char* String_data_ptr(const String* s)
{
    if (s->size == 0) {
        return NULL;
    }
    // Cast away const intentionally: caller may mutate via this pointer.
    return (char*)(IS_SSO(s) ? s->stk : s->heap);
}

// Same growth path as String_append_char, minus the size++: writes '\0'
// at index s->size and leaves size untouched. Safe against the SSO
// mode-flag byte because MAYBE_GROW_STR converts to heap (or reallocs
// the heap buffer) whenever size == capacity, before we ever write,
// so the write always lands one past the last real char, never on the
// flag byte at stk[STR_SSO_SIZE - 1].
void String_ensure_null_term(String* s)
{
    MAYBE_GROW_STR(s);
    GET_STR_CHAR(s, s->size) = '\0';
}


//  Modification

void String_append_char(String* s, char c)
{
    MAYBE_GROW_STR(s);
    GET_STR_CHAR(s, s->size++) = c;
}

void String_append_cstr(String* s, const char* cstr)
{
    FATAL_IF(s->capacity == 0, "String_append_cstr on zeroed/moved-from String");
    u64 len = strlen(cstr);
    if (len == 0) {
        return;
    }

    ensure_capacity(s, s->size + len);
    memcpy(GET_STR(s) + s->size, cstr, len);
    s->size += len;
}

void String_append_String(String* s, const String* other)
{
    FATAL_IF(s->capacity == 0, "String_append_String on zeroed/moved-from String");
    if (other->size == 0) {
        return;
    }

    ensure_capacity(s, s->size + other->size);
    memcpy(GET_STR(s) + s->size, GET_STR(other), other->size);
    s->size += other->size;
}

void String_append_String_move(String* s, String* other)
{
    FATAL_IF(s->capacity == 0, "String_append_String_move on zeroed/moved-from String");
    if (s == other) {
        return;
    }

    // Empty destination on the same allocator: take other's buffer instead of
    // copying it (0 allocations, B8: other dies here, so nothing is copied).
    if (s->size == 0 && other->capacity != 0 && wc_same(s->alloc, other->alloc)) {
        String_destroy(s);
        *s = *other;
        memset(other, 0, sizeof(String));
        return;
    }

    if (other->size > 0) {
        String_append_String(s, other);
    }
    String_destroy(other);
}

char String_pop_char(String* s)
{
    WC_ASSERT(s->size != 0, "cannot pop from empty String");

    char c = GET_STR_CHAR(s, --s->size);
    return c;
}

void String_insert_char(String* s, u64 i, char c)
{
    WC_ASSERT(i <= s->size, "index out of bounds");

    MAYBE_GROW_STR(s);

    char* buf = GET_STR(s);
    // Shift right.
    for (u64 j = s->size; j > i; j--) {
        buf[j] = buf[j - 1];
    }
    buf[i] = c;
    s->size++;
}

void String_insert_cstr(String* s, u64 i, const char* cstr)
{
    WC_ASSERT(i <= s->size, "index out of bounds");

    u64 len = strlen(cstr);
    if (len == 0) {
        return;
    }

    ensure_capacity(s, s->size + len);

    char* buf = GET_STR(s);
    // Shift existing chars right by len positions.
    for (u64 j = s->size; j > i; j--) {
        buf[j + len - 1] = buf[j - 1];
    }
    memcpy(buf + i, cstr, len);
    s->size += len;
}

void String_insert_String(String* s, u64 i, const String* other)
{
    WC_ASSERT(i <= s->size, "index out of bounds");

    if (other->size == 0) {
        return;
    }

    WARN_IF_RET(s == other, , "can't insert aliasing(same) Strings");

    u64 len = other->size;
    ensure_capacity(s, s->size + len);

    char* buf = GET_STR(s);
    for (u64 j = s->size; j > i; j--) {
        buf[j + len - 1] = buf[j - 1];
    }
    memcpy(buf + i, GET_STR(other), len);
    s->size += len;
}

void String_remove_char(String* s, u64 i)
{
    WC_ASSERT(i < s->size, "index out of bounds");

    char* buf = GET_STR(s);
    memmove(buf + i, buf + i + 1, s->size - 1 - i);
    s->size--;
}

/*
    0 1 2 3 4 5  (1, 2)
      ^ ^
    start = 1
    len = 2
    end = 2
*/

void String_remove_range(String* s, u64 start, u64 len)
{
    WC_ASSERT(start < s->size, "start out of bounds");

    if (len == 0) {
        return;
    }

    if (start + len >= s->size) {
        len = s->size - start;
    }

    memmove(GET_STR_PTR(s, start), GET_STR_PTR(s, start + len), s->size - start - len);

    s->size -= len;
}


//  Access


//  Comparison

int String_compare(const String* s1, const String* s2)
{
    u64 min_len = s1->size < s2->size ? s1->size : s2->size;

    if (min_len > 0) {
        int cmp = memcmp(GET_STR(s1), GET_STR(s2), min_len);
        if (cmp != 0) {
            return cmp;
        }
    }

    if (s1->size < s2->size) {
        return -1;
    }
    if (s1->size > s2->size) {
        return 1;
    }
    return 0;
}

bool String_equals_cstr(const String* s, const char* cstr)
{
    u64 len = strlen(cstr);

    if (s->size != len) {
        return false;
    }
    if (len == 0) {
        return true;
    }

    return memcmp(GET_STR(s), cstr, len) == 0;
}


//  Search

u64 String_find_char(const String* s, char c)
{
    if (s->size == 0) {
        return WC_NOT_FOUND;
    }
    const char* buf = GET_STR(s);
    const char* p   = memchr(buf, (unsigned char)c, s->size);
    return p ? (u64)(p - buf) : WC_NOT_FOUND;
}

u64 String_find_cstr(const String* s, const char* substr)
{
    u64 len = strlen(substr);
    if (len == 0) {
        return 0;
    }
    if (len > s->size) {
        return WC_NOT_FOUND;
    }

    // memchr (SIMD in libc) jumps to each candidate first byte; memcmp confirms the rest.
    const char* buf = GET_STR(s);
    const char* end = buf + (s->size - len) + 1; // one past the last valid start
    const char* cur = buf;
    while (cur < end && (cur = memchr(cur, substr[0], (size_t)(end - cur))) != NULL) {
        if (memcmp(cur, substr, len) == 0) {
            return (u64)(cur - buf);
        }
        cur++;
    }
    return WC_NOT_FOUND;
}

String String_substr(const wc_allocator* a, const String* s, u64 start, u64 length)
{
    WC_ASSERT(start < s->size, "start out of bounds");

    if (start + length > s->size) {
        length = s->size - start;
    }

    String result = String_create(a);

    if (length > 0) {
        ensure_capacity(&result, length);
        memcpy(GET_STR(&result), GET_STR(s) + start, length);
        result.size = length;
    }

    return result;
}


//  I/O

void String_print(const String* s)
{
    putchar('"');
    fwrite(GET_STR(s), 1, s->size, stdout);
    putchar('"');
}


// Promote SSO buffer to heap allocation.
static inline void stk_to_heap(String* s)
{
    u64 new_cap = (u64)((float)s->capacity * STRING_GROWTH);
    if (new_cap == 0) {
        new_cap = STR_SSO_SIZE;
    }

    char* new_data = wc_alloc(s->alloc, new_cap, 1);
    FATAL_IF(!new_data, "String stk_to_heap: allocation failed");

    memcpy(new_data, s->stk, s->size);

    s->heap     = new_data;
    s->capacity = new_cap;
    // stk[STR_SSO_SIZE - 1] was already set to '\0' by MAYBE_GROW_STR before calling this
}

static inline void heap_to_stk(String* s)
{
    // save the ptr as memcpy on stk will overwrite
    char*               heap = s->heap;
    const wc_allocator* a    = s->alloc;
    u64                 cap  = s->capacity;
    memcpy(s->stk, heap, s->size);
    wc_free(a, heap, cap, 1);
    s->stk[STR_SSO_SIZE - 1] = 1; // mark SSO mode
    s->capacity              = STR_SSO_SIZE - 1;
}

static inline void String_grow(String* s)
{
    u64 new_cap = (u64)((float)s->capacity * STRING_GROWTH);
    if (new_cap <= s->capacity) {
        new_cap = s->capacity + 1;
    }

    char* new_data = wc_realloc(s->alloc, s->heap, s->capacity, new_cap, 1);
    FATAL_IF(!new_data, "String_grow: realloc failed");

    s->heap     = new_data;
    s->capacity = new_cap;
}

static inline void ensure_capacity(String* s, u64 needed)
{
    if (needed <= s->capacity) {
        return;
    }

    // Grow by at least STRING_GROWTH factor
    u64 new_cap = (u64)((float)s->capacity * STRING_GROWTH);
    if (new_cap < needed) {
        new_cap = needed;
    }

    // currently in SSO but SSO cap is not enough
    if (IS_SSO(s)) {
        s->stk[STR_SSO_SIZE - 1] = '\0'; // switch to heap mode
        char* new_data           = wc_alloc(s->alloc, new_cap, 1);
        FATAL_IF(!new_data, "ensure_capacity: allocation failed");
        memcpy(new_data, s->stk, s->size);
        s->heap     = new_data;
        s->capacity = new_cap;
    } else {
        char* new_data = wc_realloc(s->alloc, s->heap, s->capacity, new_cap, 1);
        FATAL_IF(!new_data, "ensure_capacity: realloc failed");
        s->heap     = new_data;
        s->capacity = new_cap;
    }
}

#undef GET_STR_PTR
#undef GET_STR_CHAR
#undef STR_REMAINING
#undef IS_SSO
#undef GET_STR
#undef MAYBE_GROW_STR
#endif /* WC_WC_STRING_IMPL */

#endif /* WC_IMPLEMENTATION */

#endif /* WC_WC_HELPERS_SINGLE_H */
